Store followers and following lists; Add missing aborting; Fix multiple print in Scheduler; Fix unsafe delete_line_from_file
InstaPy/InstaPy pull request #1047
Opened 2017-12-05 06:55 UTC by sionking

* Store followers and following lists:
2 Files (pickles) storing a list contain all original following/followers, good as a starting point and backuip to a new account. Also relevant to dont_include section.'

* Add missing aborting:
Some def missed an aborting check, When we reach max per day it want to abort any task.

*Fix multiple print in Scheduler:
https://github.com/timgrossmann/InstaPy/issues/994

*Fix unsafe delete_line_from_file:
https://github.com/timgrossmann/InstaPy/issues/992

SC.

2017-12-05 07:30 UTC, timgrossmann commented
@sionking Thank you for contributing, we'll check that soon.

Pleas make sure to remove all the drivers (chromedriver, gecko driver, db) from the PR

2017-12-05 09:17 UTC, sionking commented
How do I change the PR files ?

2017-12-05 12:34 UTC, Naramsim commented
@sionking just update your code in your branch Get-followers and push it on to your repo

2017-12-05 14:21 UTC, converge requested changes

2017-12-05 14:21 UTC, converge commented on instapy/util.py
> +def getFollowerList(browser,
get_follower_list

2017-12-05 14:21 UTC, converge commented on instapy/util.py
> +        allfollowing = formatNumber(
all_following

2017-12-05 14:21 UTC, converge commented on instapy/util.py
> +            print("unable to get user information\n", str(e))
logger.warning()

2017-12-05 14:21 UTC, converge commented on instapy/util.py
> +                    # get following
need to clean variables['after'] before new graphql call

2017-12-05 14:21 UTC, converge commented on instapy/util.py
> +                "unable to get followers and following information \n", str(e))
logger.warning

2017-12-05 14:21 UTC, converge commented on instapy/util.py
> +            print(len(all_following))
logger

2017-12-05 14:21 UTC, converge commented on instapy/util.py
> +            with open('./logs/all_following.pkl', 'wb') as output:
(txt, pkl, csv, sqlite) we should focus on sqlite.

2017-12-05 14:21 UTC, converge commented on instapy/util.py
> +            print(len(all_followers))
logger

2017-12-05 14:21 UTC, converge commented on setFollowersing.py
> +from instapy import InstaPy
is this file needed ? we should doc it and move to docs or examples

2017-12-05 14:21 UTC, converge commented on .gitignore
we should avoid it

2017-12-05 14:21 UTC, converge commented on instapy/instapy.py
> +#from .clarifai_util import check_image
unnecessary line

2017-12-05 14:21 UTC, converge commented on instapy/instapy.py
> +from .util import getFollowerList
get_followers_list

2017-12-05 14:21 UTC, converge commented on instapy/instapy.py
> +        if (self.logger.hasHandlers()):
isn't it better to have separate log files ?
tail -f would show every instance log

2017-12-05 14:21 UTC, converge commented on instapy/instapy.py
> +    def getFollowerList_user(self, following=True, followers=False):
get_follower_list_user (can we improve the method name?)

2017-12-05 14:21 UTC, converge commented on instapy/util.py
> +        filepathOld = filepath+".old"
file_path_old

2017-12-05 14:21 UTC, converge commented on instapy/util.py
> +        filepathTemp = filepath+".temp"
file_path_temp

2017-12-05 16:46 UTC, timgrossmann commented
@converge These are some good catches, thank you!

2017-12-06 08:59 UTC, sionking commented on instapy/instapy.py
> +    def getFollowerList_user(self, following=True, followers=False):
sure

2017-12-06 09:01 UTC, sionking commented on instapy/instapy.py
> +        if (self.logger.hasHandlers()):
It is not a threaded run, only an scheduler issue. 
If you have better solution go for it I am not a Python guy by basic.

2017-12-06 09:04 UTC, sionking commented on instapy/util.py
> +                    # get following
It returned an error to me.

2017-12-06 09:04 UTC, sionking commented on instapy/util.py
> +                    # get following
No variables['after] .... exist

2017-12-06 09:06 UTC, sionking commented on setFollowersing.py
> +from instapy import InstaPy
It need to run once, example is good enough.

2017-12-06 13:22 UTC, converge commented on instapy/util.py
> +                    # get following
did you add it after line 291 ?

2017-12-07 04:41 UTC, sionking commented on instapy/util.py
> +                    # get following
I tell you what happened.
The original loop is a for loop on i == 0 and i == 1. (unfollow file)
I call this function with only one param following/followers as true, so this var doesn't exist if I try only i == 1.
My target is to capture any users all followers and ignore the following, so it will be used later as a targeted for likes and follow.

2017-12-08 12:37 UTC, converge commented on instapy/util.py
> +                    # get following
check it out:
https://github.com/timgrossmann/InstaPy/commit/1c16d51eab873b1e3d45f4ac0f04b5fbf2a4a83d

and test it before my bug fix.

2017-12-09 18:03 UTC, sionking commented on instapy/util.py
> +                    # get following
When only want to capture the followers (and not also the following) it will rise an error.

2017-12-09 19:42 UTC, timgrossmann commented
@sionking You still have to make sure that the CI goes through 👍

2017-12-15 07:15 UTC, timgrossmann commented
@sionking Any updates on this?

2017-12-16 11:35 UTC, sionking commented on instapy/util.py
> +            with open('./logs/all_following.pkl', 'wb') as output:
I have no time to learn sqlite, how complex is it >=?

2017-12-16 11:49 UTC, sionking commented
Will update today.
BTW I found another bug:
ERROR - delete_line_from_file error [WinError 32] The process cannot access the file because it is being used by another process: './logs/XXX_followedPool.csv.temp' -> './logs/XXX_followedPool.csv'
Apparently, something is using the file (maybe the storage server) and I found myself with deleted file 👎 .
So I am polling on the file name changing, and the file removal until it done.

2017-12-16 11:56 UTC, sionking reviewed
Done all changes request

2017-12-16 12:29 UTC, sionking commented
I don't understand Y it is not pass the checks ?

2017-12-16 14:14 UTC, sionking reviewed
done

2017-12-16 14:14 UTC, sionking commented on .gitignore
Avoid what?

2017-12-16 14:14 UTC, sionking commented on instapy/instapy.py
> +#from .clarifai_util import check_image
Reverted

2017-12-16 14:14 UTC, sionking commented on instapy/instapy.py
> +from .util import getFollowerList
done

2017-12-16 14:14 UTC, sionking commented on instapy/instapy.py
> +    def getFollowerList_user(self, following=True, followers=False):
named

2017-12-16 14:14 UTC, sionking commented on instapy/util.py
> +        filepathOld = filepath+".old"
named

2017-12-16 14:14 UTC, sionking commented on instapy/util.py
> +        filepathTemp = filepath+".temp"
named

2017-12-16 14:14 UTC, sionking commented on instapy/util.py
> +def getFollowerList(browser,
named

2017-12-16 14:14 UTC, sionking commented on instapy/util.py
> +        allfollowing = formatNumber(
named

2017-12-16 14:14 UTC, sionking commented on instapy/util.py
> +            print("unable to get user information\n", str(e))
done

2017-12-16 14:14 UTC, sionking commented on instapy/util.py
> +                    # get following
working diffrently

2017-12-16 14:14 UTC, sionking commented on instapy/util.py
> +                "unable to get followers and following information \n", str(e))
done

2017-12-16 14:14 UTC, sionking commented on instapy/util.py
> +            print(len(all_following))
done

2017-12-16 14:14 UTC, sionking commented on instapy/util.py
> +            print(len(all_followers))
done

2017-12-16 14:14 UTC, sionking commented on setFollowersing.py
> +from instapy import InstaPy
moved to example

2017-12-16 14:15 UTC, sionking commented
Now pass

2017-12-16 14:15 UTC, sionking commented
Please review

2017-12-16 21:25 UTC, sionking reviewed
done

2017-12-18 12:08 UTC, sionking commented
Can you merge ?

2017-12-21 16:06 UTC, timgrossmann commented
@sionking We also shouldn't deleted the setup.py file.
And can you add documentation to the Readme about the method you implemented as well, please?

2018-01-24 10:38 UTC, GabrieleCalarota commented
You are my hero... thank you so much!!!

2018-01-25 15:40 UTC, sionking commented
GabrieleCalarota 
me ? thanks.
I should add the readme...
I have so many feature developed but I am struggling to merge them since new to git.

2018-01-27 18:55 UTC, timgrossmann commented
@sionking That sounds awesome!

Yeah I know that merging them into this repo can be a pain...
We would love to see them though.

It is easiest to check and merge them if it's completely separated into different PRs

2018-02-04 07:20 UTC, closed without merging

2018-02-04 07:20 UTC, sionking commented
I will recreate PR for each feature one by one