Fix suspicious attempt
InstaPy/InstaPy pull request #1097
Opened 2017-12-14 16:08 UTC by nilkesede

I put together #1079 #1064 in order to solve the `suspicious attempt` problem

2017-12-14 20:54 UTC, Naramsim commented
Could you please change `pickle` with `json`? Reasons:

* Having cookies saved as `json` is much more readable (human-readable). 

* With `json` we can dump/update by ourselves the cookie file if we are running headless.

* `Json` and pickle have basically the same methods (`dumps`, `loads`).

* We don't really need to save cookies as a binary file.

* `Json` is much [faster](https://konstantin.blog/2010/pickle-vs-json-which-is-faster/) and [safer](https://stackoverflow.com/a/2259351/3482533)

2017-12-17 13:36 UTC, converge requested changes
hey mate! nice ideas!

Unfortunatelly it doesn't login for me on my VPS, I receive the wrong login data message.

another point is, we should avoid try to bypass suspicious attempt page every time we login, it increases the delay to login.

2017-12-17 13:36 UTC, converge commented on instapy/instapy.py
> +    def get_dont_like(self):
do we need it ?

2017-12-18 12:45 UTC, nilkesede commented on instapy/instapy.py
> +    def get_dont_like(self):
we don't really need it

2017-12-18 13:01 UTC, nilkesede commented
thanks, man!
it doesn't try to bypass every time, just when we have the suspicious attempt page. but i got you, it really increases the delay to login.

2017-12-22 16:32 UTC, converge commented
#1074 #1125

2017-12-22 16:32 UTC, closed without merging