Add proxy support
InstaPy/InstaPy pull request #1098
Opened 2017-12-14 23:22 UTC by JulienDev

2017-12-15 07:08 UTC, timgrossmann requested changes

2017-12-15 07:08 UTC, timgrossmann commented on instapy/instapy.py
> +            if self.proxy_address is not None and self.proxy_port > 0:
Could we do:
`if self.proxy_address and self.proxy_port > 0:`
?

2017-12-15 07:08 UTC, timgrossmann commented on instapy/instapy.py
> +            if self.proxy_address is not None and self.proxy_port > 0:
Could we do:
`if self.proxy_address and self.proxy_port > 0:`
?

2017-12-15 07:08 UTC, timgrossmann commented on instapy/instapy.py
> +                proxy = '%s:%s' % (self.proxy_address, self.proxy_port)
Could we please use the same format as with the other strings?
`proxy = '{ip}:{port}'.format(ip=self.proxy_address, port=self.proxy_port)`
?

2017-12-15 07:08 UTC, timgrossmann commented on instapy/instapy.py
> +                chrome_options.add_argument('--proxy-server=http://%s' % proxy)
Could we do:
`chrome_options.add_argument('--proxy-server=http://{proxy}'.format(proxy=proxy))`
?

2017-12-15 07:08 UTC, timgrossmann commented
@JulienDev Thank you very much for this!
Could you make these small changes, please and we'll merge that after this.

So awesome, thanks for contributing!

2017-12-15 07:38 UTC, JulienDev commented
Here you are! 
Sorry, it's my first time writing python.

2017-12-15 17:28 UTC, timgrossmann approved these changes

2017-12-15 17:28 UTC, timgrossmann commented
@JulienDev No worries, I'll test it later today to make sure that it works :wink: 
Thank you for contributing!

2017-12-17 14:37 UTC, converge commented
Sounds great ! We just need to fix the suspicious login attempt before merge it.

2017-12-19 21:29 UTC, sionking commented
Working for me ! thanks.

2017-12-22 16:29 UTC, merged

2017-12-22 16:31 UTC, converge commented
thanks @JulienDev !

2017-12-22 16:31 UTC, JulienDev commented
You're welcome :)

Le 22 déc. 2017 17:31, "João Paulo Vanzuita" <notifications@github.com> a
écrit :

> thanks @JulienDev <https://github.com/juliendev> !
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/timgrossmann/InstaPy/pull/1098#issuecomment-353631924>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAEWsWtaAh6jg3RP8bO9Y3l6K56qK-j-ks5tC9lKgaJpZM4RCzgn>
> .
>