Parameter to save log files by username #1149
InstaPy/InstaPy pull request #1150
Opened 2017-12-28 14:32 UTC by dvlpr-life

Fixes#1149 - Add a parameter to determine if the log files should be stored in a separate log file subfolder by username use the existing one log folder structure

2017-12-28 23:07 UTC, converge commented
nice idea, but we should avoid add more complexibility for a simple task.

2017-12-29 15:24 UTC, timgrossmann commented
@converge I think we should make this default so people can easily use multiple accounts while having separate accounts

2017-12-29 16:00 UTC, converge commented
@timgrossmann I agree, the point is, we can do in one line:
```python
file_handler = logging.FileHandler('./logs/{}_general.log'.format(self.username))
```

2017-12-29 16:53 UTC, dvlpr-life commented
A subfolder for each user account makes it easier to manage individual account log sets (move, copy, delete, etc...). "Quickstart" scripts can also be placed in that folder for execution. Making each user, in essence, portable...

2018-01-05 01:17 UTC, timgrossmann requested changes

2018-01-05 01:17 UTC, timgrossmann commented on README.md
> +session.set_comments([u'This post is ?',u'More emojis are always better ?',u'I love your posts ???']);
You have to make sure that you don't break things...

2018-01-05 01:17 UTC, timgrossmann commented on README.md
> +session.set_comments([u'Emoji text codes are also supported :100: :thumbsup: :thumbs_up: \u2764 ??']);
Same here 😉

2018-01-05 01:17 UTC, timgrossmann commented on examples/example.py
> +session = InstaPy(username='test', password='test',multi_logs=True)
I'd say just create a separate example file instead of writing it in the default example file.

2018-01-05 01:17 UTC, timgrossmann commented on instapy/instapy.py
> +            self.logfolder = './logs/' + username +'/'
Could we please use the './logs/{username}'.formt(username=username) format with string concats?

2018-01-05 01:17 UTC, timgrossmann commented on instapy/instapy.py
> +        file_handler = logging.FileHandler(self.logfolder + 'general.log')
Same here, please use format string concat style

2018-01-05 01:17 UTC, timgrossmann commented on instapy/instapy.py
> +            with open(self.logfolder + 'blacklist.csv', 'r') as blacklist:
Same here, please use format string concat style

2018-01-05 01:17 UTC, timgrossmann commented on instapy/login_util.py
> +        for cookie in pickle.load(open(logfolder + '{}_cookie.pkl'
Same here, please use format string concat style

2018-01-05 01:17 UTC, timgrossmann commented on instapy/unfollow_util.py
> +        with open(logfolder + username + '_followedPool.csv') as \
Same here, please use format string concat style

2018-01-05 01:17 UTC, timgrossmann commented on instapy/unfollow_util.py
> +                        delete_line_from_file(logfolder + username +
Same here, please use format string concat style

2018-01-05 01:17 UTC, timgrossmann commented on instapy/unfollow_util.py
> +                        delete_line_from_file(logfolder + username +
Same here, please use format string concat style

2018-01-13 13:28 UTC, dvlpr-life commented
Requested changes had been made. Resolve conflicts with master?

2018-01-15 16:02 UTC, dkbast commented
@timgrossmann did you see the changes?

2018-01-15 21:10 UTC, timgrossmann approved these changes

2018-01-15 21:11 UTC, timgrossmann commented
@dvlpr-life Can you resolve the conflicts one more time, please?

@dkbast Did you double check if everything works?

2018-01-16 00:32 UTC, dvlpr-life commented
@timgrossmann conflicts have been resolved. Thanks!

2018-01-20 22:02 UTC, dvlpr-life commented
@timgrossmann latest conflicts resolved.

2018-01-21 18:43 UTC, CharlesCCC commented
@dvlpr-life merged your branch to my local branch and test it with my account, it seems all working fine (Windows 10 with Chrome)

2018-01-23 16:39 UTC, dvlpr-life commented
I've been using this for a while with no issues, with multiple user scripts running simultaneously. Has anyone had any issues?

@timgrossmann  with it being approved is there anything else to getting it merged it? I have been (and will continue to) keeping my fork in sync with the base.

2018-01-24 06:09 UTC, merged

2018-01-24 06:09 UTC, timgrossmann commented
@dvlpr-life Just wanted to make sure that there are no big complains right away 😉 

Great work, thank you very much for this!
Looking forward to future contributions

2018-01-24 23:57 UTC, ganeshkrishnan1 commented
Was looking forward to this feature. Thank you!