Adding the capability to define a custom `user-agent` on chromedriver
InstaPy/InstaPy pull request #1151
Opened 2017-12-28 23:12 UTC by ArturGrigio

I saw that there was no way to change the `user-agent` other than setting the `headless_browser=True`.

It might look weird to Instagram if the user is logging in with 2 different devices.

I also updated the documentation to reflect the new functionality.

*Note:* I had to add an additional redirect inside `login_util.py` to go around `#reactivated` prompt when logging in using a phone `user-agent`

2017-12-29 15:26 UTC, Naramsim commented
Be careful that in some cases changing UA will also change the rendered DOM, causing Instapy to not properly work. Add a note on the readme.md

2017-12-29 15:29 UTC, timgrossmann commented
@ArturGrigio Thank you for contributing! 
We'll review your PR shortly and get back to you with any changes.

What is the `fan.util` for?

2017-12-29 15:57 UTC, converge requested changes

2017-12-29 15:57 UTC, converge commented on main.py
> +# insta_password = 'al7217'
your passwd

2017-12-29 21:38 UTC, Naramsim commented
This guy...

2018-01-01 11:48 UTC, sionking commented
I don't understand how user agent == Phone while the bot run a PC web.
It will not make sense to Instagram .... Only if you log from phone and choose desktop view.

2018-01-12 07:30 UTC, closed without merging