Update amount of follow
InstaPy/InstaPy pull request #1454
Opened 2018-02-18 09:47 UTC by dar2015

Amount to follow for giving users follow split between each account.
For example if you have 10 different accounts you follow for followers intend of set for 20 each account you can set 200 for all and it will split it automatically.

2018-02-25 18:34 UTC, timgrossmann commented
@dar2015 Thank you for contributing!

However, I don't really understand what this feature does, I'm sorry.
Could you explain it a little bit more?

2018-02-26 13:57 UTC, dar2015 commented
@timgrossmann today, when you set amount to follow it's will replicate the amount for each users you want to follow from his list. for example you set amount 100 and you have 5 different users you follow from the bot will follow 500 users. 
My update will split 100 following between all the 5 users and each list will follow over 20 users.

2018-02-26 13:59 UTC, dar2015 commented
Today
amount=100 
users=5
total follow = 500
5*100 = 500

My update
amount=100 
users=5
total follow = 100
100/5 = 20 * 5

2018-03-02 07:34 UTC, timgrossmann commented
@dar2015 Ok now I get it.
But this most likely will only make sense if we can make it optional.
Could you think about making this a parameter or setting, please?

2018-03-05 14:21 UTC, dar2015 commented
I can do it, how you suggest to implement it?

2018-03-06 06:07 UTC, sionking commented
I think this is great!
I always trim my list to 5 tags (out of 20 let say) to not excceed with total tags amount.
So total is preferred .

2018-03-14 13:17 UTC, GitNees commented
Or put 20 with 5 users = 100 :D #quickmath

2018-03-14 22:00 UTC, Tjorriemorrie requested changes

2018-03-14 22:00 UTC, Tjorriemorrie commented on instapy/instapy.py
> +        amount_per_user = int(ceil(amount / len(usernames)))
please handle zerodivisionerror. Add return above if empty
Does not seem necessary to cast it to int (scroll_bottom casts it)

2018-03-14 22:02 UTC, Tjorriemorrie commented
I'm not sure I understand this change. Just call the method with 20.

2018-03-15 11:20 UTC, dar2015 commented
Fixed for your request added as param

2018-03-15 11:30 UTC, GitNees commented
Still a very confusing option. Its creating a solution for a problem that doesn't exist.

2018-03-18 22:09 UTC, sionking commented
The problem:
The number of tags vary all the time, so if you have now 5 tags and amount 20 you will get **100**.
Tmrw you will had a new tag (6 tags) amount is the same and you will have the **120** instead.

Anyway I thought about it and still prefer to control the amount of tags I am entering.
A better feature will be amount per tag (use tuples).

2018-03-19 08:15 UTC, Tjorriemorrie commented
That's still an implementation detail.

2018-03-19 12:57 UTC, dar2015 commented
Idea of amount is to control how many follow do you want. I use external list of accounts that change for time to time and don't really know how many accounts on the list. the amount of follow changing for me now. this idea solve it.

2018-03-21 08:57 UTC, timgrossmann commented
I'm extremely unsure about this...
We either put this as a parameter (if we don't overdue it) or keep it off...

2018-03-21 10:29 UTC, dar2015 commented
Now i able it as a parameter you can choose to by toggle it.

2018-03-21 10:40 UTC, Tjorriemorrie commented
But you also pass in the usernames: so you have all the info for the calculation which you can do just before you call the function; and pass in the calculated amount.

2018-04-13 08:19 UTC, closed without merging