Respect amount on interact_user_followers
InstaPy/InstaPy pull request #1656
Opened 2018-03-16 11:04 UTC by texmex44

At final of interact_user_followers restart if followed < amount. (if param respectAmount is True)

2018-03-16 18:32 UTC, timgrossmann commented
@texmex44 Thank you for the contribution!
This is a good catch, however I'm not sure if we should use recursion here.
Would you mind changing that to e.g. a while loop?

2018-03-16 22:37 UTC, sionking commented
Recursion with no stop condition == memory overflow
We need to add another stop conditions that is unconditioned in IG response (e,g a counter).

2018-03-16 22:59 UTC, texmex44 commented
@timgrossmann While loop is here 👍 Can you check ? I'm just not sure if i need to put a "break" in the except error or if the return statement do the job ...

2018-03-17 06:08 UTC, timgrossmann commented
@texmex44 Seems to work great!

@sionking Can you please double check that?

2018-03-18 22:54 UTC, Tjorriemorrie requested changes

2018-03-18 22:54 UTC, Tjorriemorrie commented on instapy/instapy.py
> +            userToInteract = []
use snake case for python, e.g. user_to_interact

2018-03-18 22:54 UTC, Tjorriemorrie commented on instapy/instapy.py
> +        while self.valid_users == 0 or (amount - self.valid_users > 0 and respectAmount):
replace `== 0` with `not self.valid_users`

2018-03-18 22:54 UTC, Tjorriemorrie commented on instapy/instapy.py
> +    def interact_user_followers(self, usernames, amount=10, randomize=False, respectAmount=False):
respect_amount

2018-03-18 22:54 UTC, Tjorriemorrie commented on instapy/instapy.py
> +            if respectAmount and self.valid_users > 0 and self.valid_users < amount:
if you make `restart` start with -1 then you don't need the second condition.
If you don't want to change that then you still need to change it to `0 < self.valid_users < amount`. it's also different to the while condition, shouldn't it be the same?

2018-03-19 08:23 UTC, texmex44 commented on instapy/instapy.py
> +            userToInteract = []
i can change but in the master code `userToInteract` is used.

2018-03-19 08:23 UTC, texmex44 commented on instapy/instapy.py
> +        while self.valid_users == 0 or (amount - self.valid_users > 0 and respectAmount):
ok

2018-03-19 08:23 UTC, texmex44 commented on instapy/instapy.py
> +    def interact_user_followers(self, usernames, amount=10, randomize=False, respectAmount=False):
ok

2018-03-19 08:23 UTC, texmex44 commented on instapy/instapy.py
> +            if respectAmount and self.valid_users > 0 and self.valid_users < amount:
ok i prefer to keep restart = 0 but i implement your condition `0 < self.valid_users < amount`

2018-03-21 07:59 UTC, texmex44 commented
@Tjorriemorrie @timgrossmann is it ok ?

2018-07-30 11:00 UTC, timgrossmann commented
@texmex44 Sorry for the long delay... 
Could you give a quick explanation in the README what "respect_amount" does? 
We really need to make sure that the documentation stays descriptive and explains all possible features

2018-07-31 06:56 UTC, texmex44 commented
@timgrossmann sure i will took the time to do this

2018-09-20 21:02 UTC, closed without merging