faster like button search for image liking
InstaPy/InstaPy pull request #1664
Opened 2018-03-16 20:57 UTC by douwevandermeij

First check if there is a like or unlike button via existing spans, next find the like button if it exists, which is much faster.

2018-03-17 06:09 UTC, timgrossmann commented
@douwevandermeij Looks good, thank you very much for the contribution!

Let's just wait for one more approval before we merge this.

2018-03-18 23:40 UTC, Tjorriemorrie requested changes

2018-03-18 23:40 UTC, Tjorriemorrie commented on instapy/like_util.py
>      if len(like_elem) == 1:
can remove this line then. and therefore also just remove `like_elem = []`

2018-03-19 07:52 UTC, douwevandermeij commented on instapy/like_util.py
>      if len(like_elem) == 1:
agree

2018-03-19 16:28 UTC, timgrossmann commented
@douwevandermeij Awesome neat and concise upgrades for InstaPy, I love them!
Thank you very much for your contributions!

2018-03-19 16:28 UTC, merged

2018-03-19 17:29 UTC, douwevandermeij commented
You're welcome!