Unfollow & Like util fixes.
InstaPy/InstaPy pull request #1673
Opened 2018-03-17 23:51 UTC by joanroig

Unfollow util fixes, now it doesn't skip a user after 10 unfollows.
Like util fixes:
- If a non-proper word is detected, it will not crash (solves UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 7: ordinal not in range(128))
- Fix when data is not properly loaded and needs a reload (adapted from [https://github.com/timgrossmann/InstaPy/issues/1338](url) ).

2018-03-19 01:36 UTC, Tjorriemorrie requested changes

2018-03-19 01:36 UTC, Tjorriemorrie commented on instapy/unfollow_util.py
> +                        pass
instead of `pass` just delete the line.

2018-03-19 01:36 UTC, Tjorriemorrie commented on instapy/unfollow_util.py
> +                        pass
same. do you mind adding a comment here as to why it is sleeping (if you can)?

2018-03-19 08:36 UTC, joanroig commented on instapy/unfollow_util.py
> +                        pass
You mean the "logger.info('sleeping for about {}min'.format(int(sleep_delay/60)))"? Or adding a code comment?
I agree that the pass statements can be deleted, I took the suggestion from https://github.com/timgrossmann/InstaPy/issues/1429 and I preferred to leave it explicit.

2018-04-05 10:38 UTC, timgrossmann commented
@joanroig Could you please resolve the conflicts so we can merge this?

2018-04-05 11:01 UTC, joanroig commented
Resolved, tested and merged.

2018-04-05 12:17 UTC, merged

2018-04-05 12:17 UTC, timgrossmann commented
@joanroig Thank you very much for the contribution!
Looking forward to future ones!