Follow Commenters
InstaPy/InstaPy pull request #1682
Opened 2018-03-19 00:30 UTC by justdvl

New method added, to follow all users who commented on speific user(s).
As requested here: https://github.com/timgrossmann/InstaPy/issues/1659#issuecomment-374047686
To run, add to quickstart.py, this:

session.follow_commenters(['mody._.21', 'samofficiel', 'jesus2018m']) 

It works most of the times perfectly but crash on rare occasions, I'd be happy to get help with that.

2018-03-19 08:36 UTC, Tjorriemorrie requested changes
This is good idea, good job, but some issues still outstanding. @CharlesCCC do we not already have a similar function to the `get_user_info` below? Seems duplicated work.

2018-03-19 08:36 UTC, Tjorriemorrie commented on instapy/follow_commenters.py
> +"""Methods to extract the data for the given usernames profile"""
all the files ends with *_util, do you mind changing this to `commenters_util.py`?

2018-03-19 08:36 UTC, Tjorriemorrie commented on instapy/follow_commenters.py
> +  container = browser.find_element_by_class_name('_mesn5')
You cannot use css class names. It's generated and will break everytime IG make a release.

2018-03-19 08:36 UTC, Tjorriemorrie commented on instapy/follow_commenters.py
> +  followers = infos[1].text.split(' ')[0].replace(',', '').replace('.', '')
this has been done. refer `format_number` from util.py

2018-03-19 08:36 UTC, Tjorriemorrie commented on instapy/follow_commenters.py
> +  """Get the basic user info from the profile screen"""
4 spaces. not 2. follow pep8

2018-03-19 08:36 UTC, Tjorriemorrie commented on instapy/follow_commenters.py
> +  #print('BEFORE IMG')
remove

2018-03-19 08:36 UTC, Tjorriemorrie commented on instapy/follow_commenters.py
> +
max 1 line space inside function. follow pep8

2018-03-19 08:36 UTC, Tjorriemorrie commented on instapy/instapy.py
> +    def follow_commenters(self, nicknamegetarr):
what is getarr? Do you mind renaming this please? `nicknames` should be fine?

2018-03-19 08:36 UTC, Tjorriemorrie commented on instapy/instapy.py
> +        print ("running fc")
please do not use abbreviations.

2018-03-19 08:36 UTC, Tjorriemorrie commented on instapy/instapy.py
> +          self.nicknameget = nicknameget
Please do not assign loop variables to the instance.

2018-03-19 08:36 UTC, Tjorriemorrie commented on instapy/instapy.py
> +        for nicknameget in nicknamegetarr:
just `nickname` should be fine.

2018-03-19 08:36 UTC, Tjorriemorrie commented on instapy/instapy.py
> +          if (len(user_commented_list))>0:
space around ` > `. If you are using pycharm they have a Reformat code utility.

2018-03-19 08:36 UTC, Tjorriemorrie commented on instapy/instapy.py
> +
undo: only 1 space line between functions in a class. pep8 is your friend.

2018-03-19 10:48 UTC, justdvl commented
Thank you Tjorriemorrie for the comments, I am working on fixing these issues.

I found out my script was crashing on some occasions, because of self aborting line in:

    def follow_by_list(self, followlist, times=1): 
        """Allows to follow by any scrapped list"""
        print ("started")
        self.follow_times = times or 0
        if self.aborting:
            return self

This return self should be printing something to terminal, so we know why the script suddenlty ends.
If I uncomment return self, all works great.
Can somone explain to me what is the function of self aborting? (I am new to this project)

Thanks

2018-03-19 11:32 UTC, justdvl commented on instapy/follow_commenters.py
> +  container = browser.find_element_by_class_name('_mesn5')
how to replace:
    post = browser.find_element_by_class_name('_622au') ?
because:    
    post = browser.find_element_by_xpath("/html/body/div[4]/div/div[2]/div/article")
doesnt work.

2018-03-19 18:20 UTC, justdvl commented
All suggestions fixed.

Added customizations:

Call by:

 session.follow_commenters(array, amount, daysold, max_pic)

array = array of usernames, to scan
amount = max amount of people to follow
daysold = maximum age of pictures  to analyze
max_pic = maximum number of pictures to analyze

2018-03-19 19:46 UTC, CharlesCCC commented on instapy/commenters_util.py
> +def f7(seq):
what `f7` stand for ?

2018-03-19 20:03 UTC, justdvl commented on instapy/commenters_util.py
> +def f7(seq):
Its a function that:
#remove duplicates from array while preserving order

It is because I am getting users who commented on number of posts, and I decided to sort them by frequency - to have users who comments the most be the first ones to follow; but at the same time removing duplicates.

2018-03-19 20:25 UTC, CharlesCCC commented on instapy/commenters_util.py
> +def f7(seq):
@justdvl yea, I can read the comment and I can read that part of code to. I'm just questioning the function naming itself  why named this method `f7`,  like why not `f8` `f9`... ??? For code readability point, I think we should only need left comment if it really necessary and there is no way to find a good method name to explain itself.

2018-03-19 20:40 UTC, justdvl commented on instapy/commenters_util.py
> +def f7(seq):
Can be changed, it's minor function copied from internet. Name was given to it because of speed..
I tried to comment a lot because the code seems to be bit too long..

2018-03-19 22:16 UTC, justdvl commented on instapy/commenters_util.py
> +def f7(seq):
You are right. I have renammed the function.

2018-03-19 22:21 UTC, justdvl commented
Added function follow_likers, which will get the _amount_ of users who liked specific photo by _url_
Next functions can be build on top of this.

Use:

    session.follow_likers("https://www.instagram.com/p/BgO7uCihPl8/", amount = 50)

where amount is how many users to follow (and how many likes to scrap)

as requested: https://github.com/timgrossmann/InstaPy/issues/1680

2018-03-19 22:24 UTC, justdvl commented
I am also thinking, why are we following users by going to each profile one by one, if we could be just clicking Follow buttons when we have dialog with user's list opened.
It is also more natural way, coming from Instagram bot detection place.

2018-03-20 11:51 UTC, justdvl commented
Added module: Follow_user_likers  … example to put into quickstart.py:

` session.follow_user_likers (['natgeotravel' , 'jesus2018m'], photos_grab_amount = 2, follow_likers_per_photo = 2, randomize=True)
`

2018-03-20 13:26 UTC, timgrossmann commented
@justdvl Please make sure to also include explanation in the README file.

2018-03-21 02:43 UTC, Tjorriemorrie requested changes

2018-03-21 02:43 UTC, Tjorriemorrie commented on instapy/instapy.py
> +    def follow_likers(self, photo_url_arr, amount=10):
Please don't use Hungarian notation, `photo_urls` is more pythonic.
FYI: you can also add supporting a string by:
```
if not isinstance(photo_urls, list):
    photo_urls = [photo_urls]
```

2018-03-21 14:32 UTC, CharlesCCC commented on instapy/commenters_util.py
> +    browser.get('https://www.instagram.com/' + nick)
In here you used `nick` for username ?  Can we keep it consistent to use `username` as well, so we don't confuse others.  thank you.

2018-03-21 14:50 UTC, timgrossmann commented
@justdvl You changed it the wrong way 🙈
Please keep it as `username` and remove the `nick`

2018-03-21 14:55 UTC, justdvl commented
Sorry, I dont underatand, didnt I just do it? I replaced nick for username.
My laptop battery just run oit so Ill be able to do it later at evening.
I will also split long code into more smaller functions to make it easier to read and easier to customize.

2018-03-21 15:05 UTC, CharlesCCC commented
@justdvl Yea I saw you did, thank you for the change. 
maybe @timgrossmann looked at the wrong commit  😕 ?

2018-03-21 15:25 UTC, timgrossmann commented on instapy/instapy.py
> +    def follow_commenters(self, nick_array, amount=100, daysold=365, max_pic = 100):
I just saw this... Sorry for not pointing out what I saw right away

2018-03-23 18:13 UTC, timgrossmann commented on README.md
> +def follow_likers(self, photo_url_arr, amount=10):
Could you please also paste the actual way to call this method in the quickstart here?

2018-03-23 18:14 UTC, timgrossmann commented
@justdvl Sorry for the many changes and resolves...
Just one more thing then we can finally add this to InstaPy!

Thank you very much for the hard work

2018-04-08 15:50 UTC, gaikaz commented
Hi. I'm just wondering, why is this still not pulled to master?

2018-04-09 07:52 UTC, timgrossmann commented
@gaikaz Because no-one has resolved the merge conflicts, yet...

2018-04-13 08:33 UTC, merged

2018-05-29 20:08 UTC, argentgagner commented
It doesn't seem to be working... See #2025

2018-05-31 17:26 UTC, justdvl commented
I have fixed the changes instagram did

https://github.com/timgrossmann/InstaPy/pull/2134