Logs in separate files for every start
InstaPy/InstaPy pull request #1743
Opened 2018-03-25 09:11 UTC by denisemenov

Change "general.log" to "general_2018_03_02_16_34_48.log".
This helps to find the correct log if necessary.  
For me it was much more useful than a single large file.

2018-03-25 10:54 UTC, sionking commented
please make it optional

2018-03-26 03:14 UTC, Tjorriemorrie requested changes
Can also make that the default, with a setting to keep it one file.

I can pick this up and make the change if you can wait a week or two.

2018-03-26 03:14 UTC, Tjorriemorrie commented on instapy/instapy.py
> +            file_handler = logging.FileHandler('{}'.format(self.logfolder) + 'general' + datetime.now().strftime('_%Y_%m_%d_%H_%M_%S') + '.log')
Use TimedRotatingFileHandler. Probably need to set the `suffix` and `extMatch` as well.

2018-03-27 14:39 UTC, CharlesCCC commented
@Tjorriemorrie I would agree with @sionking on this one, consider we only look at the log when we need debug and checkout. so I would say default is one file and you have the option to log it day by day(run by run) as necessary.

2018-03-28 07:40 UTC, denisemenov commented
I agree that it's right to make this an additional option, but I do not have enough knowledge to do so ... :)

2018-07-06 20:10 UTC, HansDaigle commented
It dosen't have to be in instapy, you can just add the handler yourself if you need to.

2018-07-30 10:54 UTC, closed without merging