Skip private users, skip no profile pic, minimum media count when follow
InstaPy/InstaPy pull request #2242
Opened 2018-06-14 00:11 UTC by marcomokastyle

session.set_skip_users(skip_private=True, skip_no_profile_pic=True, min_media=25)
- Skip private profile
- Skip users with less posts than a specific number
- Skip user without a profile pic. (not fully tested yet)

Fix problem in clarifi_util.py, changed the part of the code to retrieve the image url, using graphql.shortcode_media.display_url.

2018-06-14 09:27 UTC, timgrossmann commented
@marcomokastyle This is awesome! Thank you very much for those features!
One thing I noticed is that there is no documentation update to the README. Could you maybe also add a section in the README for your features? Would be perfect.

Also, do you think it might be possible to also add `max_media` to your implementation so that users can also upper restrict the amount of posts, please? 

You're awesome!

2018-06-14 09:29 UTC, timgrossmann commented on instapy/util.py
> +    link = 'https://www.instagram.com/'+username+'/'
Would you mind changing this to the `.format()` version, please?

2018-06-14 09:29 UTC, timgrossmann commented on instapy/util.py
> +    link = 'https://www.instagram.com/'+username+'/'
Would you mind changing this to the .format() version, please?

2018-06-14 09:29 UTC, timgrossmann commented on instapy/util.py
> +    link = 'https://www.instagram.com/'+username+'/'
Would you mind changing this to the .format() version, please?

2018-06-14 11:42 UTC, marcomokastyle commented on instapy/util.py
> +    link = 'https://www.instagram.com/'+username+'/'
Do you mean, something like link = 'https://www.instagram.com/{}/'.format(username)?

2018-06-14 12:03 UTC, timgrossmann commented on instapy/util.py
> +    link = 'https://www.instagram.com/'+username+'/'
Sorry, I simply could've put in the comments right away...
Yes exactly, that's what I propose. Thank you

It's just the basic way that is used in the whole codebase.

2018-06-14 12:12 UTC, marcomokastyle commented on instapy/util.py
> +    link = 'https://www.instagram.com/'+username+'/'
Ok perfect, I'll change as soon as I can :)

2018-06-14 12:19 UTC, marcomokastyle commented
@timgrossmann Sure, I'll add it to the README. 
Yes, add the parameter max_media is a great idea! And I'm thinking to another change based on an observation of @ljacobo when used in conjunction of follow_likers if the first N element taken from the like of the current user are all private profile, you don't interact with likers of this user at all. Maybe, I can do something like, if user is private, and is set skip_private=True private user is not counted and move on the the next, so if you want grab 5 users from likes, count 5 users excluding private profile.

2018-06-14 14:43 UTC, marcomokastyle commented
@timgrossmann made the changes you suggested. Still thinking about the issue of N private users, I looked at the code, and actually is taken from the list a fixed number of users, maybe to do what i suggested is needed to refactor as a loop, this is my first week that I develop in Python! I have a lot of things to learn yet. But is a big start! I already love Python :)

2018-06-14 15:51 UTC, marcomokastyle commented
Just a quick question, I'm pretty new on Git, if I understand correctly, when i commit & push on my branch is automatically added to the PL? :)

2018-06-14 16:31 UTC, marcomokastyle commented
For now I stop here. Maybe later I'll start to thinking how to change/refactor the code to exclude private profiles from the list of taken users. If anyone has any suggestions for this issue, is appreciated. :)

2018-06-15 11:48 UTC, timgrossmann commented
@marcomokastyle Yes exactly, if you update your own branch from which this PR is created, the PR will automatically update as well.

Thank you, we'll review it and merge it when we're ready, thank you very much for this awesome contribution!

2018-06-15 14:18 UTC, marcomokastyle commented
I'm not sure if is a good idea anymore, interact with only valid users and skip the others, it seems a little bit unnatural. One good thing about this project, that the behavior of this bot, is pretty natural. What do you think? If is a bad idea, I'll back to previous commits. And stop it here.

2018-06-18 12:29 UTC, timgrossmann commented
@marcomokastyle Oh, I'm sorry to hear that you are not sure whether this is a good idea or not, anymore... 
I still think this is a very good idea.

I think there are two things I might adjust here before merging.
1. It feels like the min and max media parameters are better suited for the `session.set_relationship_bounds`-method.
2. It would be awesome to also include business accounts in this method, do you know whether it is as "easy" to get that information?
3. Would love to also have this as a base for further ignore user things like the, hopefully in the future, added gender/sex "separation".

I think targeting people more is a very important feature for this project.
Considering your statement about the "pretty natural"-behaviour of the bot, I think people are the ones who should be able to decide what they want to do. Especially if it is to ignore private and business accounts as well as "spammy" accounts that have a ton of posts.
If people don't want to use those features, they don't have to but having them being able to use is crucial.

Would you be willing to make the proposed changes to this PR?
If it motivates you, I could also add a small bounty to an issue that is pointed to this PR.
Would love to have these features merged ASAP.

Thank you very much
Best
Tim

2018-06-18 12:49 UTC, marcomokastyle commented
@timgrossmann thanks, your opinion is important to me. I'll try to do what I can, I'm still learning Python, so, maybe I need a little bit of time. All your suggestions are very helpful. I'll continue on my free time and I'll share the progress made here :) P.S. I'm italian so if my english is not perfect that's the reason :P

2018-06-18 13:10 UTC, timgrossmann commented
@marcomokastyle Awesome to hear that! I'm looking forward to it. 
I think since most of your logic is already there it should mostly be refactoring. 

Thank you @marcomokastyle 

Best 
Tim

2018-06-20 16:19 UTC, marcomokastyle commented
@timgrossmann I'm experimenting, on this. I had a good idea, but not taking in consideration, that if a want grab more users, the next time i open the likes page, i have to take more followers.

Is not ideal, but for now I'm trying to do this in this way. Maybe, the better way, is in likers_from_photo to scroll down on the previous position and take likes after that position. 

```python
                while grab_success is False or attempts > max_attempts:
                    likers = users_liked(self.browser, photo_url, likers_amout*attempts)
                    if len(previous_likers) > 0:
                        likers = [element for element in likers if element not in previous_likers]
                    previous_likers.extend(likers)
```

2018-06-21 08:32 UTC, timgrossmann commented
@marcomokastyle Thank you for investing so much time into making this feature ready for instapy!

Your current approach sounds good, maybe @uluQulu could throw in some other opinion on this 😉

2018-06-21 13:26 UTC, marcomokastyle commented
@timgrossmann Thanks! Yes, all the tips I can get is appreciated. Though I still have no idea how to detect if a profile is a business profile. Some help for this issue is also appreciated. :)

2018-06-24 09:59 UTC, ArdySan2012 commented
Does it mean that "private users skipping" feature is in the main version now, or does it still need approval?

2018-06-24 13:33 UTC, marcomokastyle commented
@ArdySan2012 It's not merged yet in the master repo. I'm still working on it.

2018-06-24 19:38 UTC, timgrossmann commented
@marcomokastyle I'm trying to figure out a way as well... 
Do you know whether personal accounts are able to "highlight" stories like business accounts are?

2018-07-01 20:35 UTC, marcomokastyle commented
@timgrossmann @sionking @uluQulu I think I found a way to get the info about: if is a business account and get username from userid at this endpoint.

https://i.instagram.com/api/v1/users/[userid]/info/ where userid is the userid of the user

2018-07-02 12:40 UTC, timgrossmann commented
@marcomokastyle Looks like it's an idea worth investigating!

2018-07-07 19:59 UTC, ljacobo commented
Hi @marcomokastyle, have you merged yet the skip_private function? haven't heard in a while.

Thnks.

2018-07-08 14:23 UTC, sionking commented
@marcomokastyle this is really great.
But still I don't recommend normal use of this api, it is not natural.
We can make a server that will give us the result for a given username .... that will work under a fake account. REST API is easy in python.

2018-07-09 13:03 UTC, marcomokastyle commented
@sionking You're right, it seems that this API is used internally, never seen this call inspecting the server calls with Chrome dev tools. But your idea could be work.

2018-07-13 21:05 UTC, ArdySan2012 commented
Skip private is really useful, maybe merge that first and make a separate one for business? Seems like it is a different level of complexity, that one...

2018-07-13 21:45 UTC, timgrossmann commented
@ArdySan2012 That's true, can you second that this PR is fully functional?

Also, I'm actually not sure if the part with the media isn't better suited in the "relationship bounds" method. 
I feels like the user will be kind of confused to see another "restriction" based on min max of some value in another method.
Do you think you could "quickly" refactor that part to be part of the relationship bounds method? 

Would be awesome if we could merge this soon 👍 

Thank you
Best
Tim

2018-07-19 14:49 UTC, ArdySan2012 commented
@timgrossmann Hey there. It is not functional, unfortunately, the script being changed that much since June. And I am afraid my modest skills are quite insufficient to fix it :(

2018-07-25 14:13 UTC, meinert commented
Hope to have this merged into master......this functionality is really good

2018-07-25 14:37 UTC, marcomokastyle commented
@meinert @ArdySan2012 @timgrossmann I was quite busy, but as soon as I can I'll try to finish this.

2018-07-26 12:00 UTC, nimrodlavi commented
This could be one of the best upgrades here, and it's finished. Any idea when it'll be merged to the master branch?

2018-07-26 12:38 UTC, timgrossmann commented
@marcomokastyle Let's resolve the conflicts and merge it.
We can move the features around later on if we really want to.

Thank you all for the participation!

2018-07-26 13:32 UTC, uluQulu commented
Hi guys!
I will share my opinions on this work.
First of all I would like to sincerely thank @marcomokastyle for this great work shared with us!

In the prospect of the user it is unnoticeable but regarding the future programmers while either enhancing or revisioning it will have troubles with this structure in certain spots.
And it will not be easy to clean up the structure again.
Maybe I have overstated but it was my first impression.

I really like all of the capabilities brought by @marcomokastyle a lot. It is very impressive! Hope it gets merged soon as @timgrossmann says- "_as safely as possible_" 😁.

#### What can be done?
The structure can be revised- using an efficient design pattern where arguments' and definitions' functionalities do not conflict with each other and all have simple and unique duties WHILST keeping the same capabilities operate.

2018-07-26 13:42 UTC, marcomokastyle commented
@uluQulu Thank you! I was a programmer for a while, but is not my main job anymore, and is only a couple o months that I develop in Python, so I have a lot of things to learn yet. And yes, maybe my programmer skills are a little bit rusted :D If you have suggestion how to refactor the code is awesome, also because I can learn a lot from who have better skills than me!

2018-07-26 13:54 UTC, uluQulu commented
Your programming knowledge is outstanding, @marcomokastyle!  
And I am also very new to programming 😂😂!!
All I meant is the matter of design patterns cos it is gonna be integrated into InstaPy where there is an existent style of coding.  

I got your proposal, right now in my free times I am work on a database normalization which will solve truly huge noticeable and unnoticeable problems that's why all I think currently is to find an efficient solutions for it.  
But once finishes it, I will hopefully have time to look at this piece and maybe offer some revisions.


Chill 🤩🎉🎉

2018-08-05 13:24 UTC, uluQulu requested changes
I think there are lesser revisions needed than I have thought after seeing the code in details, @marcomokastyle.  
Let's agree on those topics I have mentioned in comments.  
If needs help, I can help you write 'em.

_This is gonna be an amazing PR once merged!_

Cheers 😁

2018-08-05 13:24 UTC, uluQulu commented on instapy/instapy.py
> +                                max_relationship_ratio=None,
@marcomokastyle,
For the most efficient usage I have set `potency_ratio` to only have one limit.  
In other words, for example, once you set it `2.5`, you want to interact with the potential users with relationship ratio of more than `2.5` (e.g. _2501 followers & 1000 following_). That's it.

Well, I see `max_relationship_ratio` here.

I think I have also thought of having a boundary for potency ratio and it was gonna be a tuple.
`potency_ratio(min, max)` but I remember I have thought it is not gonna be that efficient and would cross people's mind 😁 cos of multi ratios.  

But if you insist to use `max_relationship_ratio` - in other words, min and max values for `potency_ratio`, then that tuple value set must be used for a better code.

2018-08-05 13:24 UTC, uluQulu commented on instapy/instapy.py
> +                                min_media=0,
@marcomokastyle 
As it can be read `set_relationship_bounds` is setting the parameters for relationship which means the people you have a relationship, e.g. "_whom you follow_", "_who follows you_", etc.  
And setting max and min **media** boundary of a profile has nothing to do with the relationship, rather, it's kind of a standalone USER DATA.  


I think having this set in `set_skip_users` is better for now.

2018-08-05 13:24 UTC, uluQulu commented on instapy/util.py
> +        except WebDriverException:
Here should also be a selenium way of finding it either by CSS selectors or XPATH - which is faster.

2018-08-05 13:24 UTC, uluQulu commented on instapy/util.py
> +        except WebDriverException:
Also, another option to find from loaded page elements, will make this function more stable.

2018-08-05 13:24 UTC, uluQulu commented on instapy/util.py
> +        except WebDriverException:
Same for another option using page elements to get that information.

2018-08-05 13:24 UTC, uluQulu commented on instapy/instapy.py
> +    def set_skip_users(self, skip_private=False, skip_no_profile_pic=False, max_attempts=2, logging_enabled=False):
@marcomokastyle, 
`logging_enabled` is impressive! ~skipping the logger messages from the skipped users (_reasons, etc., sometimes you want a clearer output_ 🙂) due to preset configurations. Amazing!  
But I think it should have a friendlier name in the user interface, such as `notify`.  
What do you think about it all?  
@timgrossmann @sionking @CharlesCCC @AreaHints

Also having talked it, I think 
`skip_private` should also named as `private_users`,
`skip_no_profile_pic` >> `no_profile_pic`  
The people using it will read documentation and docs will explain it, and the feature itself has a `skip` in its name, why duplication?

2018-08-05 13:24 UTC, uluQulu commented on instapy/instapy.py
> +                attempts = 1
Wow @marcomokastyle! 
I see lots of efforts for this feature.  
Have you had troubles using it, I really wonder, cos I also used it sometimes and it worked nicely.

2018-08-05 13:24 UTC, uluQulu commented on instapy/instapy.py
> +            followed = follow_given_user(self.browser,
`follow_restriction` verification seems to be missing here.
@marcomokastyle, is it intentional?
_I think, even following from a predefined list should respect follow times._

2018-08-05 15:34 UTC, marcomokastyle commented on instapy/instapy.py
> +            followed = follow_given_user(self.browser,
I do this check in validate_likers_list. First I validate users, so is not counted if is skipped, than build a list of users.

2018-08-05 15:45 UTC, marcomokastyle commented on instapy/instapy.py
> +                attempts = 1
I used this for a while, and never had a problem :)

2018-08-05 15:49 UTC, marcomokastyle commented on instapy/instapy.py
> +                attempts = 1
@uluQulu as soon as I can I'll start to make this changes. I think I can do it by my self, but if I need help, I'll ask :)

2018-08-05 15:56 UTC, marcomokastyle commented on instapy/instapy.py
> +                                max_relationship_ratio=None,
Maybe this was not well explained, I don't know if you get it right. The current behavior is: once is set potency ratio, let's say we want people who have more followers than following, you can have something like relationship ratio 15. But if you want a limit, let's say maximum 3, this set a maximum limit.

2018-08-05 15:59 UTC, marcomokastyle commented on instapy/instapy.py
> +                                max_relationship_ratio=None,
Well, maybe we are talking about the same thing. I had to read once more to understand :P

2018-08-05 16:54 UTC, uluQulu commented on instapy/instapy.py
> +                                max_relationship_ratio=None,
Yes @marcomokastyle,
currently it is a vector but we can make it 
**NOW** (_endless vector_):
`potency_ratio=2.5`
**-∞** ----------------- `2.5` ++++++++++ **+∞**
`potency_ratio = -2.5`
**-∞** ++++++++++ `-2.5` ----------------- **+∞**
IF TUPLE (_within boundaries (_if any_)_):
`potency_ratio=(-2.5, 2.5)`
**-∞** --------- `-2.5`  ++++++++ `2.5` --------- **+∞**
`potency_ratio=(None, 2.5)`
**-∞** ++++++++++ `2.5` --------- **+∞**

Within boundaries it will be more complex to understand and with simple vector it is amazing cos negative value points to `massive followers` and positive value to `potential users`.
It can also be achieved for tuples, needs to think, do you think we really need boundaries?

2018-08-05 17:09 UTC, uluQulu commented on instapy/instapy.py
> +                attempts = 1
I know that you can, @marcomokastyle 🤩
I mean if has no time and needs help, I am ready to code something needed 🎊
> Just wants this PR pass ASAP 🤝🏼💪🏼✌🏼

2018-08-05 18:26 UTC, marcomokastyle commented on instapy/instapy.py
> +                attempts = 1
@uluQulu If you have time and want help to speed up it's ok for me. After all is one good thing about open source :) we can collaborate.

2018-08-05 18:36 UTC, marcomokastyle commented on instapy/instapy.py
> +                attempts = 1
@uluQulu I want to add another thing, part of this work was built to optimize follow_likers, the idea, is validate people first, make a list of valid people, and to maximize and take only valid people, i changed also the way we grab likers, to make sure, if you want for example 5 likers, grab all the possible users, that's why i increase the number of likers to grab in the next try. So, this concept to me seems very nice, I don't know very well all the others methods to follow people (just because I never used) but if this method is suitable also for other parts, would be nice extend this method also on other methods the have similar usage.

2018-08-05 18:55 UTC, marcomokastyle commented on instapy/instapy.py
> +    def set_skip_users(self, skip_private=False, skip_no_profile_pic=False, max_attempts=2, logging_enabled=False):
@uluQulu logging_enabled I think was an idea that I had, but not fully implemented, but yeah, the idea was exactly for this reason. Have the choice to keep log more clean if you want to.

2018-08-05 19:09 UTC, uluQulu commented on instapy/instapy.py
> +                attempts = 1
Yes @marcomokastyle 
It is interesting to write at common code 😁
Just let's finalize the discussion on the changes requested, then you might let me know which part I can work on.  
That idea is familiar to me, I have also added some personal lines for getting links from a profile, where I interact ~2 times and while it grabs ~3 photos and in case of those photos are inappropriate, I end up interacting nothing at all after a follow!  
So I did amount*5 in source files so it get 10 links when I give 2 in amount 😁 Most of time it finds 2 appropriate links from them. 

The thing is it is a performance related issue, since lots of people will like it, some may not like cos it will take much more time than default- "_get links and do it, it inappropriate or not valid, just go ahead!_"
But I like your implementation on that feature, it is a sophisticated approach and I think if it be successful it can be merged into other features 🎉

2018-08-05 19:17 UTC, marcomokastyle commented on instapy/util.py
> +        except WebDriverException:
I think, you can do this, and the other similar to this, you are better in this kind of optimizations :)

2018-08-05 19:19 UTC, marcomokastyle commented on instapy/instapy.py
> +                                min_media=0,
This I can do it,i'll  move to set_skip_users

2018-08-05 19:20 UTC, marcomokastyle commented on instapy/instapy.py
> +    def set_skip_users(self, skip_private=False, skip_no_profile_pic=False, max_attempts=2, logging_enabled=False):
I'll check if logging_enabled is to finish, and rename parameters as suggested

2018-08-05 19:22 UTC, marcomokastyle commented on instapy/instapy.py
> +            followed = follow_given_user(self.browser,
Here, I have to check, maybe is better to rename this function, something like validated_list, and check if is needed also elsewhere.

2018-08-05 19:26 UTC, marcomokastyle commented on instapy/util.py
> +        except WebDriverException:
@uluQulu you can do this one.

2018-08-05 19:26 UTC, marcomokastyle commented on instapy/util.py
> +        except WebDriverException:
@uluQulu and this one.

2018-08-05 19:26 UTC, marcomokastyle commented on instapy/util.py
> +        except WebDriverException:
@uluQulu and this one.

2018-08-05 19:59 UTC, marcomokastyle commented
@uluQulu I thinking to open maybe a new PL, just to be more clear, and maybe more easy to resync with the new codebase.

2018-08-05 20:13 UTC, uluQulu commented
Don't worry about the conflicts, @marcomokastyle 
I will solve them now 🧐

There is really no need for a new PR. Now commit anything you find useful and after all of the changes, you would `rebase` it to be more clearer and it will be done,

2018-08-05 20:40 UTC, uluQulu commented on instapy/instapy.py
> +            followed = follow_given_user(self.browser,
Hmm, here is a problem.
`follow_likers` uses `follow_by_list`, right. But `follow_by_list` itself is a standalone feature.  
You can't remove it's validation and follow restriction lines.  

Just noticed this while merging the conflicts 😟

2018-08-05 20:48 UTC, marcomokastyle commented on instapy/instapy.py
> +            followed = follow_given_user(self.browser,
@uluQulu one of my early versions, solved this issue using a simple boolean parameter, that is True by default, something like validate=True, but if you set False, just ignore the validation.

2018-08-05 20:56 UTC, uluQulu commented on instapy/instapy.py
> +            followed = follow_given_user(self.browser,
i see
cos of it is a feature adding a parameter to it will be messy.
thinks of adding a new class var named such as `self.ignore_user_validation` to solve this issue.

2018-08-05 20:57 UTC, marcomokastyle commented on instapy/instapy.py
> +            followed = follow_given_user(self.browser,
It's a great idea! and do basically the same

2018-08-05 22:06 UTC, uluQulu commented
@marcomokastyle 
I couldn't update the files in here but you can do it as an owner of your repo.
Here are the conflicted files solved:
[archive.zip](https://github.com/timgrossmann/InstaPy/files/2260719/instapy.zip)


I merged them as safe as possible and they still needs revision but there won't be conflicts.

2018-08-05 23:24 UTC, marcomokastyle commented
@uluQulu thank you! this is already a great help!

2018-08-06 05:18 UTC, uluQulu commented
Welcome, @marcomokastyle   
I see the new conflicts are super easy to solve, can  you solve them and also revert the changes of `database_engine` and `Settings` class to InstaPy defaults cos those changes belong to the commit for my latest PR 😁

Also I think rebasing will be good at this stage.  
>This is the best quick tutorial on ["How to rebase"](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) I use all the time.

2018-08-06 10:03 UTC, timgrossmann commented
@marcomokastyle @uluQulu You guys rock!
Thank you very much for the work, looking forward to merging this once the remaining conflicts are resolved.

2018-08-06 13:25 UTC, marcomokastyle commented
@uluQulu thanks, this is a really good tutoria. I'll continue my work later.

2018-08-06 17:03 UTC, uluQulu commented on instapy/clarifai_util.py
> -    try:
Me wonders why you've removed these blocks, @marcomokastyle.
They were good, weren't they?

2018-08-06 17:15 UTC, marcomokastyle commented
@uluQulu I think maybe I need to rebase now, I had a bit of time, and I have done another couple of things, I'll continue in few hours. My original fork was very long ago, so, I thinks is what we really need now. I'll try later, this is the first time I try a rebase on git. I'll write here if I need help or if I have progress :)

2018-08-06 20:31 UTC, marcomokastyle commented
@uluQulu @timgrossmann I have done the rebase, and resolved conflicts. Is the first time that i do this operation, so a confirm that is all ok, would be great :)

2018-08-06 20:34 UTC, marcomokastyle commented on instapy/instapy.py
> +                                max_relationship_ratio=None,
I'm still thinking about this @uluQulu maybe i'll restore it how it was. Maybe is too complicated, and indeed not sure if really needed.

2018-08-07 09:52 UTC, timgrossmann commented on instapy/util_old.py
> +import csv
I think you can remove this file from the PR.

Thank you

2018-08-07 10:15 UTC, uluQulu commented
That's coming along nicely, @marcomokastyle.
I knew you could do it 🤓
There is one more challenge now to solve- `git` **diff** sees whole **instapy.py** file as changed but its not.  
It should only show the differences off your work.

-------

Cheers 😁

2018-08-07 13:11 UTC, marcomokastyle commented on instapy/util_old.py
> +import csv
Yes, i forgot to delete this file :)

2018-08-07 13:14 UTC, marcomokastyle commented
@uluQulu yes, this is strange, I don't know how I can solve this issue, git should see only differences. What I can do about this?

2018-08-07 20:49 UTC, uluQulu commented
Sorry for closing, 😂 my browser is lagging 😟 too much!

I think, @marcomokastyle, it is a line ending issue.  
What is the system in the machine pushed that change?  
If it is UNIX/Linux, then it uses LF (Line Feed)- "`\n`"
or if is Windows, uses CR/LF (Carriage Return/Line Feed)- "`\r\n`"
And I don't think you can use a Macintosh with `CR` 🤤

To solve it, the file (_so, the changes you have brought_) has to have the same line ending as before (_default_). Which may cost - removing file /correcting LE / adding it (_again_).

@timgrossmann, here raises a need to have a good `.gitattributes` file in the repo to overcome this problem for the future AND the question will be which LE to choose- CRLF is what I (_and the SO pioneers_) would recommend. ☄

-------

Cheers 😁

2018-08-07 20:59 UTC, marcomokastyle commented
@uluQulu I'm working on a Mac (10.11.6) and as IDE for Python PyCharm CE.

2018-08-07 21:08 UTC, uluQulu commented
It's clear, I think the files wants to be in **CR**/**LF**.
>BTW with Macintosh I meant _MAC OS_ `9` and older 🤓 cos newer _MAC_s use **LF**.

Can you try the changes?

Just open that file in a text editor and change its _LE_ from **LF** to **CR**/**LF** and **add again**.

_I hope I am right about the diagnosis 🧐_

-------

Cheers 😁

2018-08-07 21:09 UTC, marcomokastyle commented
@uluQulu PyCharm is a nice IDE, I have easily found how to change the line ending. Just at the bottom of the window :)

2018-08-07 21:19 UTC, uluQulu commented
Hm, @marcomokastyle that's weird 🤓
Maybe it needs to be in "_LF_"?
Some tests wouldn't hurt 😎

2018-08-07 21:22 UTC, marcomokastyle commented
@uluQulu instapy.py I think was already with CRLF because you merged few hours ago.  Because, my default LE is LF.

2018-08-07 23:57 UTC, uluQulu commented
In my latest comment, I asked to try to convert **instapy.py** to LF and **add again**.
Now I am very sure about the situation, @marcomokastyle 
Why?
+ See the **util.py** and **clarifai_util.py** files after your last commit, those files look like whole file changed- the same situation with current **instapy.py**.  
It means the LE of those files is **LF** and the same is with **instapy.py** file.

So what is the root of this problem?
+ I think it is cos I after I merged commits and shared them in archived zip and then they had **CR**/**LF** cos of I work on a Windows machine.
And then you pushed them somehow where Github couldnt handle the _LE_s. (_remember util.py file also had that problem until you changed it_)
And while you change a file Github handles _LE_ automatically.

So, waiting for the new tests, @marcomokastyle 😎
It is up to you now, cos I can only edit files using Github's web editor where it does not touch LEs.


So why are the files in **LF**?
+ Cos @timgrossmann opened them first in a Macbook?
+ So it means the files such as **database_engine.py**, **relationship_tools.py** added by me has **CRLF** _LE_s cos of my Windows box 🤔
+ If above is false, then Github has default _LE_ of **LF** cos we don't have any _LE_ handler in `git` configuration files (_although they say Github has not defaults in this matter_).

-------

Cheers 😁

2018-08-08 00:24 UTC, uluQulu commented
@marcomokastyle 
How have you done it for **clarifai_util.py** and **util.py**, recently?
Can you try like that for **instapy.py**? (_but with **LF**_)

2018-08-08 00:31 UTC, marcomokastyle commented
@uluQulu I was testing just to see if now can see only the differences. And it seems it does. Now I try to change LE in LF in instapy.py

2018-08-08 00:39 UTC, marcomokastyle commented
@uluQulu I just remembered a thing, I don't know if is related, but maybe... I solved some conflicts, in the last stage, after the rebase here in the web editor, just to solve quick. But still, can be an issue related to the Line Ending.

2018-08-08 06:38 UTC, timgrossmann commented
@marcomokastyle @uluQulu Looks like you guys are close to resolving this, looks like the instapy.py file now works.

However the util.py and clarifai_util.py have the problem.

@uluQulu Thank you for pointing out the `.gitattributes` thing, I will read up on that today and add one asap.

Best
Tim

2018-08-08 06:55 UTC, timgrossmann commented
@uluQulu Haha, nice little commits you made there 😉 
Just merge #2627 so @marcomokastyle definitely needs to do one more rebase.
This might also solve the LE problem.

2018-08-08 07:14 UTC, uluQulu commented
Wow! What a timing, @timgrossmann 😂
I really like uniqueness.  
>BTW, about `.gitattributes`- a git fella told me that converting **CR**/**LF** to **LF**  is more trouble prone (_for the programmers_) vs converting **LF** to **CR**/**LF**.  That's why my prior recommendation on chosen _LE_ model- **CR**/**LF** needs to be reconsidered.

Congratulations, @marcomokastyle 🎉
You did that very well, perfect!
Now needs to convert both **clarifai_util.py** and **util.py** files' _LE_ to their prior default- **LF**.

Then we can **finalize** the code, **rebase** it one more time and **merge** your superior work!

------

Cheers 😁

2018-08-08 12:44 UTC, marcomokastyle commented
@uluQulu @timgrossmann perfect! I'll do it in a few hours, we are close to the end :)

2018-08-08 17:10 UTC, uluQulu commented on instapy/instapy.py
> +                                max_relationship_ratio=None,
@marcomokastyle 
Yes, but if you could the the `potency_ratio` within boundaries could be awesome.
The syntax should be the same as I wrote in my previous comment.
`potency_ratio` = (min_double, max_double)
```python
# positive values means "potential uses"
potency_ratio = (1, 7.2)

## negative values means "massive followers"
potency_ratio = (-2.4, -9)

### some boundary can be skipped with the value of `None`
potency_ratio = (None, 7.2)
```

What do you think about this, @timgrossmann?
@marcomokastyle, I think this is gonna be a useful addition 🎉

But third option is to use one logic and simple ratio since there will be boundaries
```python
# choose only with followers/following ("potential users" logic) ratio
potency_ratio = (min_double, max_double)
```
E.g. to apply **massive followers** logic into this set, one can use,
followers=100, following=1200, followers/following = 0.083
`potency_ratio = (0.083, 1)`
But as you can see, not using negative value separating the logic makes it a little bit hard.

2018-08-08 17:36 UTC, marcomokastyle commented on instapy/instapy.py
> +                                max_relationship_ratio=None,
@uluQulu @timgrossmann I like the first proposal. To me is not too much different one implementation or the other, but I think, something like you said:
```python
# positive values means "potential uses"
potency_ratio = (1, 7.2)

## negative values means "massive followers"
potency_ratio = (-2.4, -9)

### some boundary can be skipped with the value of `None`
potency_ratio = (None, 7.2)
```
Could be very flexible. Let me know what to do :)

2018-08-08 17:46 UTC, uluQulu commented on instapy/instapy.py
> +                                max_relationship_ratio=None,
yes @marcomokastyle 
that's so right!
also, people using it already understood the positive and negative value logic so won't be hard to accommodate into this usage.
moreover, if people want to use it like before, it is flexible as you said to support it
**OLD**:  `potency_ratio = 3.5` 
is the same with
**NEW**:  `potency_ratio = (3.5, None)`

Thanks for the hard work, @marcomokastyle 

-----

Cheers 😁

2018-08-08 18:02 UTC, marcomokastyle commented
@timgrossmann @uluQulu another thing. Here I merged two functions that do the same thing, but I'm not sure, about the following parameter, that wasn't done by me. It seem redundant to me. 
```python
def is_private_profile(browser, logger, following=True, username=None):
    if username is not None:
        profile_page = 'https://www.instagram.com/{}/'.format(username)
        web_adress_navigator(browser, profile_page)
    try:
        is_private = browser.execute_script(
            "return window._sharedData.entry_data."
            "ProfilePage[0].graphql.user.is_private")
    except WebDriverException:   # handle the possible `entry_data` error
        try:
            browser.execute_script("location.reload()")
            is_private = browser.execute_script(
                "return window._sharedData.entry_data."
                "ProfilePage[0].graphql.user.is_private")
        except WebDriverException:
            is_private = None

    # double check with xpath that should work only when we not following a user
    if is_private is True and not following:
        try:
            logger.info("Is private account you're not following.")
            body_elem = browser.find_element_by_tag_name('body')
            is_private = body_elem.find_element_by_xpath(
                '//h2[@class="_kcrwx"]')
        except NoSuchElementException:
            logger.info("Failed to double check with xpath if is a private profile")

    return is_private
```

I know, that if a private profile is already followed, we can't check if is private with XPATH, but we can do it only with graphql. Instead of using a parameter following, we can use another function that tells if we follow the user. And in this case we use only graphql. And maybe, the function is_private_profile can return a tuple, something like is_private, followed_by_viewer

2018-08-09 18:28 UTC, timgrossmann commented
@marcomokastyle You're absolutely right about the following parameter.
Feel free to adjust the method in a way that fits your code.

Looking forward to merging this, I'm sure a lot of people will love using this!
Thank you very much for the work!

2018-08-10 02:57 UTC, marcomokastyle commented
@uluQulu @timgrossmann Guys, I did everything I could. For a few days I will not be able to use my laptop, because I will be away from home.If you want, you can finish the job, if you want the merge soon ;)

2018-08-10 15:45 UTC, ilmetu commented
hey guys why not check also the bio ? we can filter for min 15 words in bio for example ...

what do you think about this ?

2018-08-10 15:46 UTC, ilmetu commented
and also for identify business profile we ca check for links in the bio ?

2018-08-12 20:06 UTC, timgrossmann commented
@ilmetu Very good points, do you think you would be able to implement this?

Best
Tim

2018-08-15 17:53 UTC, uluQulu commented
@timgrossmann is right about it, @marcomokastyle, I think you should make an optimal usage of that definition since it is a work by @sionking (_`following` parameter_) WHO could help you in that SINCE I really have limited time to see into it BUT will try to have a look soon, too AND thinks you can accomplish that problem successfully as well as others.

@marcomokastyle, like you, I have had a few OFFLINE days where I couldn't help you on this PR more, and I worked on Quota Supervisor and prepared it to share with the community, again.
Soon I will try to do some additions in your PR, too, hopefully.

@ilmetu, checking bio is highly desired, I thought of it lots of times, it could be amazing to realize it.
 Checking _business_ is also cool which is also hard cos that information is not shared in the webpage content.

@timgrossmann, I just saw @marcomokastyle's last commit it solved 3 cases at once. I think we should check this work one more time in details and merge it ASAP.
>I will also use the very helpful `no_pic` parameter 😎

------

Cheers 😁
----

2018-08-15 21:44 UTC, ilmetu commented
Hi @uluQulu and @timgrossmann , i am using this piece of code (pr) already (i merged all 10 days ago), my version of instapy is hevily customized and i developed already the bio check , for words and for links and telephone numbers, i will share it as soon as possible ... but i am very busy at the moment, there is no ETA sorry.

2018-08-16 09:09 UTC, timgrossmann commented on instapy/instapy.py
> -    def set_mandatory_words(self, tags=None):
We definitely need a rebase before merging it.

2018-08-16 09:12 UTC, timgrossmann commented
@marcomokastyle @uluQulu Absolutely, we should really merge this. I just saw that even though all checks have passed, we need to rebase this first, otherwise the `.set_mandatory_words` method will be removed by this PR.

Also, @ilmetu looking forward to those incredible changes of the bio check!
Considering that you're using this code, did you encounter any problems regarding the missing checks for CSS or XPATH selectors if the graphql calls should fail?

2018-08-16 09:14 UTC, ilmetu commented
@timgrossmann no i have no problem with that.
i hope today to merge my work into this pr

2018-08-16 09:24 UTC, timgrossmann commented
@ilmetu This would be incredible!

Thank you very much for the information.
You rock!

2018-08-16 11:04 UTC, uluQulu approved these changes

2018-08-17 10:46 UTC, ilmetu commented
@timgrossmann how can i push my changes to this pr ? :( i try but i fail ... i'm not used to do this kind of collaborations sorry.
for now i clone the repo master , then i swithc to this PR and i made the modifications at the code ,then i commit the modifications. how can i push ?
sorry for the inconvenience ...

2018-08-17 12:03 UTC, uluQulu commented
@ilmetu 
You can PR it in @marcomokastyle's fork's corresponding branch and then it can be merged into that fork so that can appear in this PR 🤓
OR if you share your work, I or @timgrossmann- who can edit the files of this PR  can add your work into it.

But I suggest you, @ilmetu, to open a new PR 😎 and sharing in there cos this PR is gonna be merged soon.
>I think it is close to ready, gonna check the changes for the last time now and will report, maybe @timgrossmann can merge it today 🎊

-----

Cheers 😁
-----

2018-08-17 12:39 UTC, uluQulu commented on instapy/util.py
> +        logger.info('User: {} >> media: {}  |  followers: {}  |  following: {}  |  relationship ratio: {}'.format(
Moving this logger message to the end, hm..
It will print only for the valid users but I think it should print it for all of the checked users cos it is good to see why someone was not validated in details.

2018-08-17 12:39 UTC, uluQulu commented on instapy/instapy.py
> +                       logging_enabled=False,
Needs to write about `logging_enabled` in README

2018-08-17 12:51 UTC, ilmetu commented
sorry, i cant do anything ... i don't know why ... it keep saying i cannot modify the pr , this one or the one from marco ...

anyway  ... this zip contains the two files, you can easily diff and merge :+1: 

[modifications.zip](https://github.com/timgrossmann/InstaPy/files/2297232/modifications.zip)

i hope i will become an active part of this community
(i want the write access!)

:1st_place_medal: 

haha ciao

2018-08-17 13:44 UTC, uluQulu commented
@ilmetu,
To do it you should make a fork of @marcomokastyle's fork and pull a request in his branch.


Try hard to achieve it 😉

2018-08-18 17:29 UTC, tuliosousa25 commented
Can someone tell me exactly what I need to do to put that work??

2018-08-22 15:20 UTC, timgrossmann commented
@uluQulu I'd really like to merge it. 
However I'd also really like to merge it from this PR rather than a new one I pushed myself since it's @marcomokastyle work...

I also don't know whether he's still active so I don't know if creating a PR at his Repo makes sense...

What do you guys think?
We should really merge this 😅

2018-08-22 15:29 UTC, marcomokastyle commented
@timgrossmann @uluQulu I'll be back very soon. Let me know what to do.

2018-08-23 12:35 UTC, uluQulu commented
Can you rebase it for the last time, @marcomokastyle?

2018-08-23 14:41 UTC, timgrossmann commented
@marcomokastyle Glad to hear that!
Once you find some time to would be great if you, as @uluQulu already mentioned, rebase the PR to the current version of Master so we can finally merge this PR 🙈

2018-08-25 10:13 UTC, uluQulu commented
@ilmetu 
"_Hi There, the method follow_through_dialog does not validate the user, i think it might be update also to use this function, or the user will still follow private users , no pic users ecc ..._"
- `follow_through_dialog` definition is only used for **simulated follows** and has no any other usage throughout the source code AND it has no access to `validate_user` definition like others COS it is outside the InstaPy class and passing all of the required variables would look ugly. But it still validate the user after returning to the InstaPy class and there if that user is not valid it does unfollow it immediately- **simulated unfollow**.

-------

Cheers 😁
-------

2018-09-13 18:42 UTC, sionking commented
Hi all,
We now have more info in graphql:
`{"logging_page_id":"profilePage_62919","show_suggested_profiles":false,"graphql":{"user":{"biography":"","blocked_by_viewer":false,"country_block":false,"external_url":null,"external_url_linkshimmed":null,"edge_followed_by":{"count":87},"followed_by_viewer":false,"edge_follow":{"count":0},"follows_viewer":false,"full_name":"Sion Yang","has_channel":false,"has_blocked_viewer":false,"highlight_reel_count":0,"has_requested_viewer":false,"id":"62919","is_business_account":false,"business_category_name":null,"business_email":null,"business_phone_number":null,"business_address_json":null,"is_private":false,"is_verified":false,"edge_mutual_followed_by":{"count":0,"edges":[]},"profile_pic_url":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/f6eaadbb28f6948126e242da55804467/5C26D77C/t51.2885-19/11821778_944414462268342_1970812124_a.jpg","profile_pic_url_hd":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/f6eaadbb28f6948126e242da55804467/5C26D77C/t51.2885-19/11821778_944414462268342_1970812124_a.jpg","requested_by_viewer":false,"username":"sion","connected_fb_page":null,"edge_owner_to_timeline_media":{"count":24,"page_info":{"has_next_page":true,"end_cursor":"AQA5eAgImyIzl8im8_X6gDxoCMSOStz6Pb9M7MOEE-1TX9IgCo7TmNzJHCv0s_1nfuQjPYojhGHYLUR3L4kxLor070ofOaQn1XM030_Qwt9lnQ"},"edges":[{"node":{"__typename":"GraphImage","id":"6251317","edge_media_to_caption":{"edges":[]},"shortcode":"X2M1","edge_media_to_comment":{"count":36},"comments_disabled":false,"taken_at_timestamp":1290802486,"dimensions":{"height":612,"width":612},"display_url":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/439cfd09e8fb1041fa697b081ad68d90/5C30ED9B/t51.2885-15/e15/11176192_357083507819902_1864690513_n.jpg","edge_liked_by":{"count":30},"edge_media_preview_like":{"count":30},"gating_info":null,"media_preview":null,"owner":{"id":"62919"},"thumbnail_src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/439cfd09e8fb1041fa697b081ad68d90/5C30ED9B/t51.2885-15/e15/11176192_357083507819902_1864690513_n.jpg","thumbnail_resources":[{"src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/42d725012f27689a8867baf9e41d8585/5C25C9D5/t51.2885-15/e15/s150x150/11176192_357083507819902_1864690513_n.jpg","config_width":150,"config_height":150},{"src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/bb4555e15c59e5ea58ca43cef66becce/5C18388A/t51.2885-15/e15/s240x240/11176192_357083507819902_1864690513_n.jpg","config_width":240,"config_height":240},{"src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/6fd4266c764c6a3cd5d991a6bd220717/5C198D51/t51.2885-15/e15/s320x320/11176192_357083507819902_1864690513_n.jpg","config_width":320,"config_height":320},{"src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/a750deace7035f3bfffd33aeb1f8b57c/5C14F040/t51.2885-15/e15/s480x480/11176192_357083507819902_1864690513_n.jpg","config_width":480,"config_height":480},{"src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/439cfd09e8fb1041fa697b081ad68d90/5C30ED9B/t51.2885-15/e15/11176192_357083507819902_1864690513_n.jpg","config_width":640,"config_height":640}],"is_video":false,"accessibility_caption":null}},{"node":{"__typename":"GraphImage","id":"2802191","edge_media_to_caption":{"edges":[]},"shortcode":"KsIP","edge_media_to_comment":{"count":2},"comments_disabled":false,"taken_at_timestamp":1289045334,"dimensions":{"height":612,"width":612},"display_url":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/cd887c4d0305db11f39bdcca76c71d4c/5C3B2EFD/t51.2885-15/e15/11123752_1596506107254806_728568224_n.jpg","edge_liked_by":{"count":14},"edge_media_preview_like":{"count":14},"gating_info":null,"media_preview":null,"owner":{"id":"62919"},"thumbnail_src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/cd887c4d0305db11f39bdcca76c71d4c/5C3B2EFD/t51.2885-15/e15/11123752_1596506107254806_728568224_n.jpg","thumbnail_resources":[{"src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/c6a01e9e7acfd7158dea4a346fbd9b1c/5C168DB3/t51.2885-15/e15/s150x150/11123752_1596506107254806_728568224_n.jpg","config_width":150,"config_height":150},{"src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/3ab12e30c4c02cd28eff57f62e2d96f3/5C3ACBEC/t51.2885-15/e15/s240x240/11123752_1596506107254806_728568224_n.jpg","config_width":240,"config_height":240},{"src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/00ef10d9a25d59dfba2c1cbfc5462630/5C30F537/t51.2885-15/e15/s320x320/11123752_1596506107254806_728568224_n.jpg","config_width":320,"config_height":320},{"src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/6e105b019a7d5542081252394f128b14/5C274B26/t51.2885-15/e15/s480x480/11123752_1596506107254806_728568224_n.jpg","config_width":480,"config_height":480},{"src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/cd887c4d0305db11f39bdcca76c71d4c/5C3B2EFD/t51.2885-15/e15/11123752_1596506107254806_728568224_n.jpg","config_width":640,"config_height":640}],"is_video":false,"accessibility_caption":null}},{"node":{"__typename":"GraphImage","id":"2600327","edge_media_to_caption":{"edges":[]},"shortcode":"J62H","edge_media_to_comment":{"count":0},"comments_disabled":false,"taken_at_timestamp":1288942830,"dimensions":{"height":612,"width":612},"display_url":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/409e13e996ea2cecce1db025e4a4ef6b/5C1556DA/t51.2885-15/e15/924742_1435671580066643_194664569_n.jpg","edge_liked_by":{"count":10},"edge_media_preview_like":{"count":10},"gating_info":null,"media_preview":null,"owner":{"id":"62919"},"thumbnail_src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/409e13e996ea2cecce1db025e4a4ef6b/5C1556DA/t51.2885-15/e15/924742_1435671580066643_194664569_n.jpg","thumbnail_resources":[{"src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/8a32733d5303209962103afc6c4e2eb1/5C2C2A74/t51.2885-15/e15/s150x150/924742_1435671580066643_194664569_n.jpg","config_width":150,"config_height":150},{"src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/768a9e9c331b4e2844d7a9d1bbcc595e/5C1C0EAB/t51.2885-15/e15/s240x240/924742_1435671580066643_194664569_n.jpg","config_width":240,"config_height":240},{"src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/0067ade1c6a639a37cd1ea9c190bee16/5C37E5F8/t51.2885-15/e15/s320x320/924742_1435671580066643_194664569_n.jpg","config_width":320,"config_height":320},{"src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/1957eee23170cdfff3b987a8866f8b5c/5C215D34/t51.2885-15/e15/s480x480/924742_1435671580066643_194664569_n.jpg","config_width":480,"config_height":480},{"src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/409e13e996ea2cecce1db025e4a4ef6b/5C1556DA/t51.2885-15/e15/924742_1435671580066643_194664569_n.jpg","config_width":640,"config_height":640}],"is_video":false,"accessibility_caption":null}},{"node":{"__typename":"GraphImage","id":"2600222","edge_media_to_caption":{"edges":[]},"shortcode":"J60e","edge_media_to_comment":{"count":0},"comments_disabled":false,"taken_at_timestamp":1288942770,"dimensions":{"height":612,"width":612},"display_url":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/4ef4e72ec9e347f89db574219cf8b28b/5C1C75CD/t51.2885-15/e15/11142842_363567810508688_209399287_n.jpg","edge_liked_by":{"count":6},"edge_media_preview_like":{"count":6},"gating_info":null,"media_preview":null,"owner":{"id":"62919"},"thumbnail_src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/4ef4e72ec9e347f89db574219cf8b28b/5C1C75CD/t51.2885-15/e15/11142842_363567810508688_209399287_n.jpg","thumbnail_resources":[{"src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/946c01b507b66f400b1c465ea8a0ed56/5C1810A3/t51.2885-15/e15/s150x150/11142842_363567810508688_209399287_n.jpg","config_width":150,"config_height":150},{"src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/eb135fefe69bc6cbc4758be1bf3c05db/5C1795FF/t51.2885-15/e15/s240x240/11142842_363567810508688_209399287_n.jpg","config_width":240,"config_height":240},{"src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/52622a88e7e257e335203d2d546f954e/5C1B0F05/t51.2885-15/e15/s320x320/11142842_363567810508688_209399287_n.jpg","config_width":320,"config_height":320},{"src":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/23d561a5353793f7dc3779173d3da946/5C2862B2/t51.2885 [...]

2018-09-13 18:51 UTC, CharlesCCC commented
a little bit more readable version @sionking 
```json
{
   "logging_page_id":"profilePage_62919",
   "show_suggested_profiles":false,
   "graphql":{
      "user":{
         "biography":"",
         "blocked_by_viewer":false,
         "country_block":false,
         "external_url":null,
         "external_url_linkshimmed":null,
         "edge_followed_by":{
            "count":87
         },
         "followed_by_viewer":false,
         "edge_follow":{
            "count":0
         },
         "follows_viewer":false,
         "full_name":"Sion Yang",
         "has_channel":false,
         "has_blocked_viewer":false,
         "highlight_reel_count":0,
         "has_requested_viewer":false,
         "id":"62919",
         "is_business_account":false,
         "business_category_name":null,
         "business_email":null,
         "business_phone_number":null,
         "business_address_json":null,
         "is_private":false,
         "is_verified":false,
         "edge_mutual_followed_by":{
            "count":0,
            "edges":[

            ]
         },
         "profile_pic_url":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/f6eaadbb28f6948126e242da55804467/5C26D77C/t51.2885-19/11821778_944414462268342_1970812124_a.jpg",
         "profile_pic_url_hd":"https://instagram.fsdv3-1.fna.fbcdn.net/vp/f6eaadbb28f6948126e242da55804467/5C26D77C/t51.2885-19/11821778_944414462268342_1970812124_a.jpg",
         "requested_by_viewer":false,
         "username":"sion",
         "connected_fb_page":null,
         "edge_owner_to_timeline_media":{
            "count":24,
            "page_info":{
               "has_next_page":true,
               "end_cursor":"AQA5eAgImyIzl8im8_X6gDxoCMSOStz6Pb9M7MOEE-1TX9IgCo7TmNzJHCv0s_1nfuQjPYojhGHYLUR3L4kxLor070ofOaQn1XM030_Qwt9lnQ"
            },
```

2018-09-14 08:54 UTC, timgrossmann commented
@sionking @CharlesCCC Wow, this is incredible!
This makes things much more easier.

Does anyone know what the `business_category_name` contains?
This one would be really interesting

2018-09-14 15:27 UTC, ilmetu commented
for one of my client the business_category_name is "Home Services"

2018-09-19 21:31 UTC, sionking commented
Created a PR.

2018-09-20 08:38 UTC, timgrossmann commented
#2957

2018-09-20 08:39 UTC, closed without merging

2018-09-20 09:22 UTC, uluQulu commented
#😥

2018-09-20 10:23 UTC, timgrossmann commented
@uluQulu ?

2019-06-24 07:57 UTC, AKwoKWH commented
Hi @timgrossmann
I am checking the ref pull request
If the bio check created by @ilmetu being implemented ?