Fix for issue - #225
InstaPy/InstaPy pull request #245
Opened 2017-05-10 14:30 UTC by CodeMaster1

This change is to create log files based on the account's username from
which the program is run. It creates three files based on username -
logfile_<username>.txt, followRestriction_<username>.json,
followed_<username>.txt.

2017-05-10 15:52 UTC, timgrossmann commented
@CodeMaster1 @littleswany I actually think this is a V1 feature...
This will break the current versions feature of following only a defined number of times...

2017-05-10 16:27 UTC, CodeMaster1 commented
@timgrossmann So, you think we should not commit to this version's branch or should we copy existing followrestriction.json to followrestriction_{username}.json to commit feature in this branch?

2017-05-10 16:33 UTC, pekapa commented
I think it would be better to work this as a v1 as well.
@CodeMaster1 could you try to implement it based on the dev branch? I think it still needs some work on the follow feature (that is undone at the moment) but it could be re-written in order to accommodate this changes.

2017-06-19 14:08 UTC, timgrossmann requested changes

2017-06-19 14:08 UTC, timgrossmann commented on instapy/instapy.py
> +    logfile_name = './logs/logfile_' + self.username + '.txt'
Please use python's formatted strings for this...e.g.  ''.format()

2017-06-19 14:08 UTC, timgrossmann commented on instapy/instapy.py
> +    follow_res_json = './logs/followRestriction_' + self.username + '.json'
Please use python's formatted strings for this...e.g.  ''.format()

2017-06-19 14:08 UTC, timgrossmann commented on instapy/instapy.py
> +    followed_logfile_name = './logs/followed_' + self.username + '.txt'
Please use python's formatted strings for this...e.g.  ''.format()

2017-06-19 14:08 UTC, timgrossmann commented on instapy/print_log_writer.py
> +  follower_logfile_name = './logs/followerNum_' + username + '.txt'
Please use python's formatted strings for this...e.g.  ''.format()

2017-06-19 14:08 UTC, timgrossmann commented on instapy/unfollow_util.py
> +  follow_res_json = './logs/followRestriction_' + username + '.json'
Please use python's formatted strings for this...e.g.  ''.format()

2017-06-19 14:08 UTC, timgrossmann commented on instapy/unfollow_util.py
> +  follow_res_json = './logs/followRestriction_' + username + '.json'
Please use python's formatted strings for this...e.g.  ''.format()

2017-08-08 07:05 UTC, closed without merging

2017-08-08 07:08 UTC, CodeMaster1 commented
I'll add the changes to the latest branch,