Implement proxy
InstaPy/InstaPy pull request #273
Opened 2017-05-24 17:43 UTC by trompx

Hey @timgrossmann @Albertmoiseev,

As quickly discussed here (https://github.com/timgrossmann/InstaPy/pull/92), I thought it was about time to implement proxy.
I did this really quickly and did not have a setup to test it right away but it could be a good starting point to implement the feature.

Feel free to test and iterate. I'll try to test it tommorrow if I get some time.

Cheers

2017-05-25 12:05 UTC, timgrossmann commented
@trompx Hey there, Awesome!

If you tested it, I'd be happy to merge this, thank you for Contributing!

2017-05-25 12:06 UTC, timgrossmann requested changes

2017-05-25 12:06 UTC, timgrossmann commented on quickstart.py
> +# InstaPy(proxy="xx.xx.xx.xx:port")
I wouldn't put this in the quickstart file...
Please remove that

2017-05-25 12:06 UTC, timgrossmann commented on README.md
> +```
Could you also add that part to docs/index, please?

2017-05-31 19:53 UTC, timgrossmann commented
@trompx Could you please fix and resolve?

2017-06-02 02:08 UTC, trompx commented
Hello @timgrossmann,

Sorry I did not have anytime lately for this lately, I could fix it quickly but finally I don't feel like it is of a great use in that state (a proxy without auth could mean you use a public proxy which is really a bad idea and would increase chances of being banned).

I will try when I have a bit more time to implement the proxy but with authentification. Once I have something more solid and battle tested I'll make a new pull request.

2017-07-30 22:53 UTC, bardascat commented
What is the status of this task? It's already older than 1 month...
Right now is it possible to run instapy for multiple instagram accounts without getting banned? 
If yes, how ?

2017-07-31 06:38 UTC, timgrossmann commented
@bardascat Just clone InstaPy multiple times.

2017-07-31 08:30 UTC, bardascat commented
@timgrossmann 
I know it's possible to clone InstaPy multiple time to use multiple instagram accounts.
In this case my concern is  if I login with multiple instagram accounts from the same ip I will get banned by instagram? Is this a real concern?
If it is what can I do, to avoid this?

Thanks

2017-07-31 18:16 UTC, timgrossmann commented
@bardascat Haven't had any problems with it yet.

2017-08-05 22:27 UTC, closed without merging