Rich Emoji Support
InstaPy/InstaPy pull request #275
Opened 2017-05-25 00:57 UTC by atomhax

Added rich emoji support. It was kinda a hackish solution to force the react core to update. Comments and critiques are always welcome.

2017-05-25 00:59 UTC, atomhax commented
I only tested this via macOS terminal. I'm requesting help from anyone willing to test this feature as well.

2017-05-25 12:08 UTC, timgrossmann commented
@atomhax Awesome, thank you!

Could you please remove the .DS_Store File?

2017-05-25 12:10 UTC, timgrossmann requested changes

2017-05-25 12:10 UTC, timgrossmann commented on README.md
> +1. You have to convert your comment to Unicode. This can safely be done by adding an u in front of the opening apostrophe:
Could you please also add this to the docs/index.md file?

2017-05-25 16:39 UTC, atomhax commented
@timgrossmann oops. I removed the .DS_Store files from the PR.

2017-05-25 16:58 UTC, atomhax commented on README.md
> +1. You have to convert your comment to Unicode. This can safely be done by adding an u in front of the opening apostrophe:
all set

2017-05-26 09:05 UTC, timgrossmann approved these changes

2017-05-26 09:05 UTC, merged