Allow skipping private users when grabbing following list
InstaPy/InstaPy pull request #3078
Opened 2018-10-04 20:13 UTC by photogsy

I've found it really useful to be able to grab a list of the people I'm following that are _not_ private. I can then use this list as a starting point which I can filter further, then use for unfollowing.

Very small changes but a really useful (IMHO) feature.
I've been using this for a week or so with expected behaviour.

2018-10-07 06:56 UTC, sionking commented
I like private users :)

2018-10-07 10:19 UTC, timgrossmann commented
@photogsy Could you elaborate a little bit more on why this is useful?
What is the reason you don't want to unfollow private users?

Thank you very much for PRing your feature!

2018-10-08 09:59 UTC, photogsy commented
Basically its useful to be able to grab a user's following list but ignore private users since you don't want to worry about how many requests to follow you are sending to private accounts.

The problem before was that if you ask InstaPy to grab 500 of a users following list but only want to interact with public accounts, then you end up with far fewer useful users in your list than 500 since you are then going to skip the private ones later.

Hope that makes sense!

I am going to PR a similar change for grabbing a user's followers.

2018-10-23 20:55 UTC, timgrossmann commented
@photogsy What is the reason this is called `ignore_private` at one place and `skip_private` at the other?

Also we would need some documentation before merging this. Do you think you could add a quick section about it in the README?

2018-12-08 09:35 UTC, timgrossmann commented
@photogsy Any updates on this?

2019-01-11 15:14 UTC, timgrossmann commented
@photogsy Any updates on this? 😊

2019-01-12 10:16 UTC, photogsy commented
Sorry I haven't had time.
There is no reason for the parameter naming difference, my Python knowledge is limited so I wasn't sure about scope, so to avoid possible issues I named them differently.

2019-01-12 10:24 UTC, timgrossmann commented
@photogsy No worries, thank you for the response.

I think it's a good idea to allow something like this, we just need to make sure that the logic is right.
Also, the naming should be unified so it should be called `skip_private` everywhere. 

Thank you very much for proposing this

2019-01-12 10:28 UTC, timgrossmann requested changes

2019-01-12 10:28 UTC, timgrossmann commented on instapy/relationship_tools.py
> +        graphql_endpoint + '?query_hash=c56ee0ae1f89cdbd1c89e2bc6b8f3d18')
Double check this GraphQL query hash

2019-01-12 10:28 UTC, timgrossmann commented on instapy/relationship_tools.py
> +                if (skip_private == False or user['node']['is_private'] == False):
boolean checking in python should be done with `is True/False` instead of `== True/False`

2019-02-06 16:18 UTC, closed without merging

2019-02-06 16:20 UTC, timgrossmann commented
@photogsy Sorry to see that we could not get this features merged.
If at one point you can update this to the latest state of InstaPy and apply the adjustments, we can definitely merge this. I'm sure a lot of users will find this useful.

Thank you very much