add Docker support :)
InstaPy/InstaPy pull request #32
Opened 2017-04-05 23:07 UTC by stephane-archer

2017-04-05 23:55 UTC, jaycegregg0 requested changes
Great way to pitch in by Dockerizing the project Stephane!

Hope you don't mind some suggestions on how to take your Dockerfile to the next level by implementing some of Docker's official best practices.

https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/

2017-04-05 23:55 UTC, jaycegregg0 commented on Dockerfile
> +
Add a MAINTAINER line with your name and email.

2017-04-05 23:55 UTC, jaycegregg0 commented on Dockerfile
> +RUN apt-get install -y google-chrome-stable
Since InstaPy doesn't use pepperflash, the Hangouts plugin, or other video codecs there's no reason to use the proprietary Chrome over the free Chromium.

2017-04-05 23:55 UTC, jaycegregg0 commented on Dockerfile
> +WORKDIR /InstaPy
Changing WORKDIR numerous times in a Dockerfile creates substantial layer bloat so try and reduce how many times you change directory. Same goes for switching users.

2017-04-05 23:55 UTC, jaycegregg0 commented on Dockerfile
> +FROM ubuntu
Specify a specific version of the base image. Use something like ubuntu:xenial or ubuntu:16.04.

2017-04-05 23:55 UTC, jaycegregg0 commented on Dockerfile
> +RUN apt-get update
Optimize your layer usage with something like the following:

```bash
RUN apt-get update && apt-get install -yqq --no-install-recommends \
  python \
  python-pip \
  unzip \
  wget \
&& rm -rf /var/lib/apt/lists/*
```

Also, putting your dependencies into alphabetical order makes it easier to scan them and add/remove from the list.

2017-04-06 00:21 UTC, stephane-archer commented
Dear @jaycegregg0,
I'm really happy to get feedback and advice :)
I will made these changes :)

2017-04-06 00:37 UTC, stephane-archer commented on Dockerfile
> +RUN apt-get update
What is the point of using -yqq? Just reduce the log? :) if there is error we need log for the user so is it ok? :)

2017-04-06 00:59 UTC, stephane-archer commented
Dear @jaycegregg0,
I hope you will love my changes
If you have any feedback please tell me :)

2017-04-06 05:26 UTC, timgrossmann commented
@stephane-archer First of all, thank you for participating!

Could you do one more thing?
- Add a comment a description to the PR on what you did. (It could be as short as "Added Dockerfile with default linux64 chromedriver".)

Did you test if this works?

2017-04-06 18:00 UTC, stephane-archer commented
Are you already using in your script pyvirutaldisplay?
Actually I'm using VNC to launch the script because the script need to launch Chrome.

I will have a look to: http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/
I hope to improve the process :)

2017-04-06 18:02 UTC, timgrossmann commented
@stephane-archer yes, when running on e.g. a server, pyvirutaldisplay is used.

I don't have enough experience on how it works with docker.

2017-04-07 23:21 UTC, jaycegregg0 commented on Dockerfile
> +RUN apt-get update
-y to not require interaction to confirm the install and -qq to quiet the output. If you buy into the UNIX philosophy as described in TAOUP silence should be preferred and output should only happen when there's something exceptional going on or when the user requests verbose output.

Log size usually isn't an issue with containers and VMs since they are starting to log to the stderr console rather than a file in many environments.

There's no problem with dropping the -qq though if you want to see the output but keep in mind that when using Docker via a CI/CD system like Travis, Jenkins, etc that all of the extraneous output can make quickly scanning the logs for the build or deployment more tedious.

2017-04-07 23:29 UTC, jaycegregg0 commented
It works pretty much the same way with Docker. pyvirtualdisplay or xvfb are usually how you deal with the GUI bit when working on headless CI/CD environments.

@stephane-archer You could easily use xvfb via [this Docker image](https://hub.docker.com/r/markadams/chromium-xvfb/).

2017-04-08 06:59 UTC, timgrossmann commented
@jaycegregg0 Yes, I just realised, that you can go through the whole process just as if it was a Droplet on DO. 
Let's see if stephane will take care of it, else I'll add the Dockerfile soon

2017-04-11 19:47 UTC, closed without merging

2017-04-12 17:16 UTC, stephane-archer commented
Sorry I was busy these few days :/
Hope I can help you more next time :)

2017-04-12 18:52 UTC, timgrossmann commented
@stephane-archer You helped a lot!
The only thing is, you're not listed as collaborator by now... 
Maybe you could add another PR 😉

2017-04-13 20:52 UTC, stephane-archer commented
I don't care about collaborator, just want to contribute to cool project :D 
Probably soon ;)