#324 Added - like feed feature
InstaPy/InstaPy pull request #345
Opened 2017-06-28 07:05 UTC by saurabh-kumar-vit

I have added the function to get the like buttons in **feed_util.py** so that we can extend it some time in the future. 
The function to be used by the API is in InstaPy named **like_feed**.

Please review my patch and tell what else needs to be done. This is my first PR ever so I apologize if my code is not up to standards. I am ready to change the code upon request.

2017-06-28 14:53 UTC, timgrossmann requested changes

2017-06-28 14:53 UTC, timgrossmann commented on instapy/instapy.py
> +  def like_feed(self, amount):
Could you refactor this to `like_by_feed` to keep the api consistent with the `like_by_tag` an `like_by_location`, please.

2017-06-28 14:53 UTC, timgrossmann commented on instapy/instapy.py
> +    _ = raw_input()
Why do you need an input here?

2017-06-28 14:53 UTC, timgrossmann commented on logs/followerNum.txt
>  0
Please remove this file => don't push your changes

2017-06-28 14:53 UTC, timgrossmann commented on logs/logFile.txt
> +Session started - 2017-06-25 21:49:06
Please remove this file => don't push your changes

2017-06-28 17:09 UTC, timgrossmann commented
@saurabh-kumar-vit Could you also add some documentation for this feature, please?

2017-06-29 06:23 UTC, saurabh-kumar-vit commented
I have updated the code as requested. I will write the documentation as soon as the code is merged.

2017-06-29 06:24 UTC, saurabh-kumar-vit commented on instapy/instapy.py
> +  def like_feed(self, amount):
code has been updated

2017-06-29 06:25 UTC, saurabh-kumar-vit commented on instapy/instapy.py
> +    _ = raw_input()
I used the input for debugging to ensure that the like were performed as expected. It has been removed since it is not needed in the deployed version.

2017-06-29 06:28 UTC, saurabh-kumar-vit commented on logs/logFile.txt
> +Session started - 2017-06-25 21:49:06
I have removed them from my commit by doing `git rm --cached <filename>`. I am not sure that is the correct way of doing this. If I am wrong I will change it again.

2017-06-29 08:11 UTC, saurabh-kumar-vit commented
One more thing that I wanted to know is how long should the delay be between two consecutive likes. At the moment I have set the delay to be 3 seconds.

2017-06-29 13:58 UTC, timgrossmann requested changes

2017-06-29 13:58 UTC, timgrossmann commented on instapy/feed_util.py
> +	global SLEEP_AMOUNT
What does this do?

2017-06-29 13:58 UTC, timgrossmann commented on instapy/feed_util.py
> +	browser,
Could you move the params to a single line, please?

2017-06-29 13:58 UTC, timgrossmann commented on instapy/feed_util.py
> +			exit(0)
I don't think the program should "exit" here.
In the other methods the `self.abort`-flag is normally set to true, which will lead to a clean exit.

Could you explain this quickly?

2017-06-29 14:00 UTC, timgrossmann commented
@saurabh-kumar-vit 
Thank you so much for that feature!
I'm sorry to request some more changes I overlooked the first time, but these should be quickly fixed.

3 seconds seems long enough 😉

Looking forward to merging this.
Thank you

2017-06-30 06:24 UTC, saurabh-kumar-vit commented
I have updated the code as requested.

2017-06-30 06:26 UTC, saurabh-kumar-vit commented on instapy/feed_util.py
> +	browser,
I did that because I initially wanted to give a comment next to each variable but later saw how your code was written but forgot to update it. Sorry for this.

2017-06-30 06:29 UTC, saurabh-kumar-vit commented on instapy/feed_util.py
> +	global SLEEP_AMOUNT
Initially the delay was included in the generator function of feed_util.py but later moved to the caller function in instapy.py. SLEEP_AMOUNT was the global variable I used to set the delay between each like button. It is not needed anymore and so I have removed it from feed_util.py.

2017-06-30 06:30 UTC, saurabh-kumar-vit commented on instapy/feed_util.py
> +			exit(0)
Updated. Now when the function does not find any like buttons it will break from the loop and stop generating buttons for the like_by_feed.

2017-06-30 06:58 UTC, saurabh-kumar-vit commented
I have also updated the documentation in README.md.

2017-07-01 09:24 UTC, timgrossmann approved these changes

2017-07-01 09:25 UTC, timgrossmann commented
@saurabh-kumar-vit Awesome! thank you so much for this!

2017-07-01 09:25 UTC, merged

2017-07-02 05:48 UTC, saurabh-kumar-vit commented
thank you @timgrossmann I will always remember you for accepting my first pull request ever. I wish to able to contribute and help this community more in the future.

2017-07-03 18:53 UTC, ujazzz commented
now thats its approved can we add more? like posts based on followings and followers maybe?

So much appreciate your work @saurabh-kumar-vit