Pool followed
InstaPy/InstaPy pull request #349
Opened 2017-06-28 15:50 UTC by jungfish

2017-06-28 15:51 UTC, jungfish commented
I've made the functionnality test it and tell me all about it !

2017-06-28 17:09 UTC, timgrossmann requested changes

2017-06-28 17:09 UTC, timgrossmann commented on instapy/print_log_writer.py
> +        followPool.close()
You don't need to close of the fileDescriptor when using `with`

2017-06-28 17:09 UTC, timgrossmann commented on instapy/unfollow_util.py
> +locale.setlocale( locale.LC_ALL, 'en_US.UTF-8' )
Why do we need this? 
Shouldn't this be covered with the `chrome_options`?

2017-06-28 17:09 UTC, timgrossmann commented on instapy/unfollow_util.py
> +            print("--> Total unfollowNum exeeded the pool of automated followed ", unfollowNum)
Does this mean, that once our pool is empty, we can't unfollow any more people?

2017-06-28 17:09 UTC, timgrossmann commented on instapy/unfollow_util.py
> +            average_sleep(600)
Actually, the `.time_util.py` already includes some randomness

2017-06-28 17:09 UTC, timgrossmann commented on instapy/unfollow_util.py
> +def follow_user(self, user_name):
I'm not 100% sure, but I think we should keep the unpacked version to keep the codebase a bit consistent

2017-06-28 17:09 UTC, timgrossmann commented on instapy/unfollow_util.py
> +    average_sleep(10)
Same here, the `sleep()` already included randomness

2017-06-28 17:09 UTC, timgrossmann commented on instapy/util.py
> +def average_sleep(average_sec):
`.time_util.py`

2017-06-28 17:30 UTC, jungfish commented on instapy/print_log_writer.py
> +        followPool.close()
oh cool I didn't know !

2017-06-28 17:30 UTC, jungfish commented on instapy/unfollow_util.py
> +locale.setlocale( locale.LC_ALL, 'en_US.UTF-8' )
It's to translate numbers 1,000 to 1 thousand

2017-06-28 17:31 UTC, jungfish commented on instapy/unfollow_util.py
> +            average_sleep(600)
ok

2017-06-28 17:32 UTC, jungfish commented on instapy/unfollow_util.py
> +            print("--> Total unfollowNum exeeded the pool of automated followed ", unfollowNum)
yes, so that you can't unfollow people that haven't been followed automatically.

2017-06-28 17:33 UTC, jungfish commented on instapy/unfollow_util.py
> +def follow_user(self, user_name):
no problem, I just did it so that we won't too many arguments

2017-06-28 17:34 UTC, jungfish commented on instapy/unfollow_util.py
> +locale.setlocale( locale.LC_ALL, 'en_US.UTF-8' )
I mean just to be clear  "1,000" >> int 1000

2017-06-28 17:45 UTC, timgrossmann commented on instapy/unfollow_util.py
> +            print("--> Total unfollowNum exeeded the pool of automated followed ", unfollowNum)
This is actually really cool.

The only thing is, that we should keep the other unfollow as well to make sure people can still unfollow accounts.

E.g. they start out with 6k Following and want to get rid of them

2017-07-01 09:31 UTC, timgrossmann commented
@jungfish Could you please fix these changes, we are then ready to merge this.
Thank you for contributing!

2017-07-01 14:43 UTC, jungfish commented
Hey @timgrossmann I was currently very busy but I have practically finished the review. You will get it tomorow, I hope you understand.

2017-07-02 17:09 UTC, jungfish commented
check it out. It should be ready

2017-07-03 06:43 UTC, timgrossmann approved these changes

2017-07-03 06:44 UTC, timgrossmann commented
@jungfish Awesome! Looks good and worked with my tests.
Let's see how this works out!

Thank you!

2017-07-03 06:44 UTC, merged