PEP8 layout changes
InstaPy/InstaPy pull request #3637
Opened 2018-12-27 18:48 UTC by w4ngel

This PR deals with pushing InstaPy to a cleaner code base with PEP8 as in the roadmap, a step towards the PEP8 format is to do spacing correctly, have the correct amount of blank lines after a function, at the end of the file etc, having spaces after the start of comments. This PR only deals with that, it does not attempt to do anything outside of formatting for PEP8 to give a much more readable codebase.

All files edited are done as separate commits. No changes par the ones stated will be in this branch.

2018-12-28 12:00 UTC, w4ngel commented
Just to reiterate, this does not change any logic, just format cleans up the code to match PEP8 formatting guidelines.

2018-12-28 20:00 UTC, timgrossmann commented
@w4ngel Thank you for clarifying, we still have to discuss if we should do all the changes in one step or introduce it one after each other.
We had PRs like this before,  I have to admit I really like this separation of refactors per commit. 

Thank you for this, let me discuss this with the other core devs.

2018-12-28 20:37 UTC, w4ngel commented
> @w4ngel Thank you for clarifying, we still have to discuss if we should do all the changes in one step or introduce it one after each other.
> We had PRs like this before, I have to admit I really like this separation of refactors per commit.
> 
> Thank you for this, let me discuss this with the other core devs.

Yeah just let me know, if you ever want to get closer to PEP8, honestly going one step at a time won't be the way as the code base is so extensive, at least a massive formatting change like this gets rid of one of the large parts of PEP8 which is merely simple layout. The more complex parts like the logic changes should be done step by step as things like `if condition:` aren't necessarily applicable to all functions in InstaPy.

2018-12-28 23:07 UTC, uluQulu commented
Nice job, @w4ngel!

Just wonder, have you used auto formatter for that?

Also, as @timgrossmann mentioned, file-specific commits makes it too much easier to differentiate.
Will try to look at the changes in depth, soon as possible.

--- 

Cheers :grin: 
---

2018-12-28 23:33 UTC, w4ngel commented
> Nice job, @w4ngel!
> 
> Just wonder, have you used auto formatter for that?
> 
> Also, as @timgrossmann mentioned, file-specific commits makes it too much easier to differentiate.
> Will try to look at the changes in depth, soon as possible.
> 
> ## Cheers 😁

We have a few auto format tools for work that a colleague made, they go to varying degrees of detail, but the best one to use just does formats it in PEP8 layout :)

2018-12-29 00:36 UTC, w4ngel commented
The last few commits are just similar changes for all the quickstart files, proxy extension files and setup. So the changes would be uniform across the whole project now :D

2018-12-29 10:58 UTC, timgrossmann commented
@w4ngel @uluQulu Alright, I've looked though every commit to make sure that there are no logical changes (or malicious additions. Nothing personal @w4ngel just making sure 🙈) 

Everything looks good and much cleaner now, thank you for this PR.

As soon as @uluQulu approves this PR, we should be ready to go. 
Considering that @sionking is also fine with the changes made here, I know he has a lot of local changes to his InstaPy version.

2018-12-29 10:58 UTC, timgrossmann approved these changes

2018-12-29 21:38 UTC, w4ngel commented
> @w4ngel @uluQulu Alright, I've looked though every commit to make sure that there are no logical changes (or malicious additions. Nothing personal @w4ngel just making sure 🙈)
> 
> Everything looks good and much cleaner now, thank you for this PR.
> 
> As soon as @uluQulu approves this PR, we should be ready to go.
> Considering that @sionking is also fine with the changes made here, I know he has a lot of local changes to his InstaPy version.

Any changes that @sionking has I can also format appropriately as and when they are committed.

2018-12-30 14:07 UTC, w4ngel commented
Resolved Merge conflicts. Can I suggest this is merged sooner rather than later so I won't have to keep resolving them?

2018-12-30 14:14 UTC, timgrossmann commented
@w4ngel If no-one shouts out with a big no, I'll merge it this evening (8pm German time)

2018-12-30 18:31 UTC, uluQulu commented on instapy/text_analytics.py
> -                                  1 if pol == "NEU"else
a bit strange here

2018-12-30 18:38 UTC, w4ngel commented on instapy/text_analytics.py
> -                                  1 if pol == "NEU"else
The way that is done is PEP8 visual under indentation- believe it or not the previous version follows PEP8 to the dot but is harder to read.

2018-12-30 18:39 UTC, uluQulu commented on instapy/unfollow_util.py
> +                                                                                       '{} seconds'.format(
a lot of spacing here,,

2018-12-30 18:43 UTC, w4ngel commented on instapy/unfollow_util.py
> +                                                                                       '{} seconds'.format(
Yeah, I believe it's these if statements that are not necessarily following PEP8 convention themselves causing the format to do some strange things.

2018-12-30 18:46 UTC, uluQulu commented on instapy/util.py
> +                                     in ["complete" or "loaded"])
ow 16 spaces..

2018-12-30 18:47 UTC, w4ngel commented on instapy/util.py
> +                                     in ["complete" or "loaded"])
> ow 16 spaces..

Yeah that's due to it being inline with the browser.execute_script statement as that's the statement that it's part of.

2018-12-30 19:20 UTC, uluQulu commented
I have a busy schedule but spent a few minutes to review this PR in details.

I have checked whole code else than those 3 comments, everything is amazing.
_Those comments are not necesary but just for good visual look_..

@w4ngel, if your auto formatter makes it look ugly either by PEP 8 rules or not, it must be changed.
Remember, PEP 8 is just for making code look good, readable,..

BTW if you said all of the changes here were ONLY **spacing** and **lining**, then it would be much cooler to review. I know you said but there you say "_etc._" .. 🙂

It is difficult to prepare such change list, so, you have done a really good job.
I use `AutoPEP8` in my _Sublime Text_, but I don't think I can configure it to just pepize spacing and lining, you got a nice tool 😎 there..

Also, how many spaces did you take the line length limit?

---

Cheers 😁
---

2018-12-30 19:32 UTC, w4ngel commented
> I have a busy schedule but spent a few minutes to review this PR in details.
> 
> I have checked whole code and else than those 3 comments, everything is amazing.
> _Those comments are not necesary but just for good visual look_..
> 
> @w4ngel, if your auto formatter makes it look ugly either by PEP 8 rules or not, it must be changed.
> Remember, PEP 8 is just for making code look good, readable,..
> 
> BTW if you said all of the changes here were ONLY **spacing** and **lining**, then it would be much cooler to review. I know you said but there you say "_etc._" .. 🙂
> 
> It is difficult to prepare such a huge change list, so, you have done a really good job.
> I use `AutoPEP8` in my _Sublime Text_, but I don't think I can configure it to just pepize spacing and lining, you got a nice tool 😎 there..
> 
> Also, how many spaces did you take as the line length limit?
> 
> ## Cheers 😁

Gotcha, and 121 is the line length limit I have on my current laptop.

2018-12-30 19:34 UTC, w4ngel commented
@timgrossmann let me know if you want me to make any changes before merge!

2018-12-30 20:06 UTC, timgrossmann commented
@w4ngel Just making sure that this really is standard PEP8 without any highly modified custom styling.
It will be hard for people to contribute if this is something you configured without sharing your linter config

2018-12-30 20:14 UTC, uluQulu commented
@w4ngel 
https://pep8.org/#maximum-line-length
 - "_Limit all lines to a maximum of 79 characters._"

It explains clearly there and I now, solely, agree with those rules if not earlier times.

2018-12-30 20:33 UTC, timgrossmann commented
@w4ngel Thank you very much @uluQulu for referencing.

I think this PR should stay open a little bit longer. I won't merge anything that is not crucial to bug fixing until we've merged this.

@w4ngel Could you reason about the changes you have done to the PEP8 standard definition and why you adjusted them.

2018-12-30 20:52 UTC, w4ngel commented
> @w4ngel Just making sure that this really is standard PEP8 without any highly modified custom styling.
> It will be hard for people to contribute if this is something you configured without sharing your linter config

The linter is using standard definition library for PEP8 without optimisations/code cleanup options.



> Could you reason about the changes you have done to the PEP8 standard definition and why you adjusted them.

The only thing that I have customised is line length but that is set auto to my screen size! Which if I reset, I'll just need to make some adjustments to the merge to make it fit. Certain stuff hasn't been formatted, mainly if you have a string such as `foo = "Some very long string"` it will not split up the string to multiple lines. Other than that no problem.

I am just gonna do a recheck of all the files with the PEP8 line length and do a re-review.

2018-12-30 20:59 UTC, w4ngel commented
Just a note, biggest things flagged on making the lines shorter are the following;

1. Variable and parameter naming conventions should all be lower case, in some instances they aren't - this hasn't been changed in this commit.

2. Lines too long - as mentioned above, can be fixed but would suggest a staged approach for this unless it's obvious. (Don't want to go through every string and extend them over multiple lines)

3. And last; continuation lines missing indentation or being outdented, i.e. due to the above, some strings that are formatted and put over multiple lines then get weird auto-indentation. 

@timgrossmann @uluQulu If you want I can reformat with line limit of 79, will need to go through to solve issue 3, but I can do that easily. Just need to know before I do it.

2018-12-30 21:07 UTC, w4ngel commented
Here is an example of what things would look like with corrected issues above (Par the naming change): https://gist.github.com/w4ngel/117bb223c398b2ba9d89379f9955cf65

2018-12-30 21:22 UTC, timgrossmann commented
@w4ngel Thank you very much for the quick response.
You're absolutely right, we need to, iteratively, adjust the naming and too long lines.

I think the line length is hard to decide, in my opinion, 80 chars is a little bit short, but it's PEP standard and it's probably best to keep everything at default so people won't have to adjust the definition when they are creating PRs.

> Thanks for mentioning your way of listing. We will link that in the contributors guide once we're done with this.

2018-12-30 21:26 UTC, w4ngel commented
> @w4ngel Thank you very much for the quick response.
> You're absolutely right, we need to, iteratively, adjust the naming and too long lines.
> 
> I think the line length is hard to decide, in my opinion, 80 chars is a little bit short, but it's PEP standard and it's probably best to keep everything at default so people won't have to adjust the definition when they are creating PRs.
> 
> > Thanks for mentioning your way of listing. We will link that in the contributors guide once we're done with this.

If you like the look of the example file given above, I will set about making those changes across the board, I do agree with having it as a default. But I also agree that it's really short! If you have a monitor larger than 13in it looks ridiculous :D

2018-12-30 22:31 UTC, uluQulu commented
>1-) Variable and parameter naming conventions should all be lower case. 

I agree that it is a usual regulation.
But having constant variables upper cased is better.
And there are very less parameters with uppercase letter in its name and one of them is
```pyhon
interruption_handler(SIG_type=signal.SIGINT, handler=signal.SIG_IGN, notify=None, logger=None)
```
That is intentional for technical [not logical] reasons and should not be renamed.

If you try to lowercase names, it wouldn't be not be a trivial change.

---

@timgrossmann @w4ngel 
For example, there are lots of companies with every programmer having wide-screen displays and they are clearly right to choose 100 ll. But it's different here, e.g. my display is `1366x768` and such as, while opening multi tabs in a TE/IDE, and can't see longer lines fullly.
Majority of userbase should be taken into account for this.

---

Cheers 😁
---

2018-12-30 22:53 UTC, w4ngel commented
> @timgrossmann @w4ngel
> For example, there are lots of companies with every programmer having wide-screen displays and they are clearly right to choose 100 ll. But it's different here, e.g. my display is `1366x768` and such as, while opening multi tabs in a TE/IDE, and can't see longer lines fullly.
> Majority of userbase should be taken into account for this.

Ok, with that being said, @timgrossmann do you want me to go about reformatting with the PEP8 line standard? Will be able to get it done tomorrow.

2018-12-31 09:03 UTC, timgrossmann commented
@w4ngel @uluQulu I think we should try sticking to PEP8 as close as possible.
I'm a little bit worried about the sometimes really long xPaths. We don't want any line breaks in the urls themselves.

Please feel free to adjust this to the actual PEP8 line length. 
Thank you very much
Sorry for the long discussion

2018-12-31 10:43 UTC, w4ngel commented
> @w4ngel @uluQulu I think we should try sticking to PEP8 as close as possible.
> I'm a little bit worried about the sometimes really long xPaths. We don't want any line breaks in the urls themselves.
> 
> Please feel free to adjust this to the actual PEP8 line length.
> Thank you very much
> Sorry for the long discussion

I will commit changes to the actual PEP8 Line length, though I would suggest another review as things like XPaths/URLs can now be over multiple lines.

2018-12-31 14:06 UTC, converge requested changes
I couldn't review all the code, but added some quick comments.

2018-12-31 14:06 UTC, converge commented on instapy/browser.py
> +        # chrome_options.add_argument("--disable-infobars")
if not used, we can remove it

2018-12-31 14:06 UTC, converge commented on instapy/clarifai_util.py
>  def check_image(
the old version is correct..
in this way we're adding 8 tabs indentation.

2018-12-31 14:06 UTC, converge commented on instapy/database_engine.py
> +                .format(name, str(exc).encode("utf-8")))
the old version is correct..

2018-12-31 14:06 UTC, converge commented on instapy/database_engine.py
> +                .format(name, str(exc).encode("utf-8")))
the old version is correct..

2018-12-31 14:06 UTC, converge commented on quickstart_templates/friends_last_post_likes_and_interact_with_user_based_on_hashtahs.py
> +    friends = InstaPy(username=insta_username, password=insta_password,
one argument per line is better

2018-12-31 14:11 UTC, w4ngel commented on instapy/clarifai_util.py
>  def check_image(
Can I please have a line ref? The changes with this file have all been to fit with the 79 char limit.

2018-12-31 14:25 UTC, w4ngel commented on instapy/clarifai_util.py
>  def check_image(
Wait I see.

2018-12-31 14:28 UTC, w4ngel commented on instapy/clarifai_util.py
>  def check_image(
Made it fit much better and corrected additonal comma that was there for some reason...

2019-01-01 18:19 UTC, converge commented
we can add E712 (PEP8) to travis setup later.

E712 (^) | comparison to True should be ‘if cond is True:’ or ‘if cond:’

2019-01-01 18:40 UTC, converge approved these changes

2019-01-01 19:06 UTC, merged

2019-01-01 19:06 UTC, timgrossmann commented
Love the team work here!
Thank you very much for this, guys! ✌️

2019-01-01 21:32 UTC, uluQulu commented
>           we can add E712 (PEP8) to travis setup later.
> E712 (^) | comparison to True should be ‘if cond is True:’ or ‘if cond:’

@converge 
We have discussed it several times with @sionking and @timgrossmann before.
It will break logic and code. If you want it, you must change behaviours of affected functions which changes the way they work.
I am against that regulation on this project.


---

Cheers 😁
---

2019-01-02 09:14 UTC, converge commented
@uluQulu can you show me an example ?

2019-01-02 15:07 UTC, uluQulu commented
sure @converge - such as `verify_action()` function;

If you wanna find more code that relies on multi-type return values without reading whole source code line by line, then run this short code which I just wrote to find an example for you,
```python
target_file = "unfollow_util.py"
k = ["def ", "return ", "if ", "elif ", "while ", "True", "False", "None"]

with open(target_file, 'r') as f:
    c = f.readlines()

for e, l in enumerate(c):
    if "def " in l:
        print('\n')

    if any(i in l for i in k):
        print("{}\t{}".format(e, l))
```


---

Cheers 😁
---

2019-01-02 16:44 UTC, converge commented
I see, but isn't a real situation, I can't see the point of parsing a .py file to check if the reserved word is inside the .py file.

Can you point it where will it break in InstaPy ?

2019-01-14 16:18 UTC, uluQulu commented
Sorry for a very late reply, @converge 
I have been very busy last days.

>"_Can you point it where will it break in InstaPy ?_"


For example, in the function- `verify_action()` that I talked about before,
![image](https://user-images.githubusercontent.com/33269249/51124587-15884c80-1838-11e9-9c71-fec1843b58c4.png)
`action_state` variable takes either a _Boolean_ or `None` type value.
And checking `action_state` as _PEP_ advices,
`if not action_state:`
will trigger both _Boolean_ `False` and `None` type values which will cause a misbehaviour.

>"_.. can't see the point of parsing a .py file .. _"

By printing those key lines, you can easily find out which statements rely on multi-type values.
Sorry for my basic techniques, I have not much tooling experience 😊

---

Cheers 😁
---

2019-01-15 10:10 UTC, converge commented
I see @uluQulu, the point is.. in the end, it's just the same verification with the same result, it's just a "PEP8 thing".

```python
x = None
if x is True:
    print('ok')

if x is False:
    print('ok')

if x == False:
    print('ok')

if x == True:
    print('ok')
# ---
if x is None:
    print('ok')
output: ok
if x == None:
    print('ok')
output: ok
```

Does it make sense.. ?

2019-01-15 10:17 UTC, timgrossmann commented
@converge Ahh, just checked that and I think you're right.

I think the point was the assumption that python coerces `None` to `False` when checking for `is False`.
So the assumption was this output
```python
if None is False:
    print('ok')
# will print ok

if False is False:
    print('ok')
# will print ok
```

When testing this in the console, the actual output is
```python
if None is False:
    print('ok')
# will NOT print ok

if False is False:
    print('ok')
# will print ok
```

2019-01-20 23:18 UTC, sionking commented
@w4ngel hi what tool did you use to align the whole code ?

2019-01-20 23:28 UTC, w4ngel commented
I use a custom linter that a colleague built in my IDE - PyCharm it uses pep8.py tool

2019-02-04 12:09 UTC, uluQulu commented
caveat
a warning to consider something before acting further, or a statement that limits a more general statement:  He agreed to the interview, with the caveat that he could approve the final article.  → 

@converge @timgrossmann 

Sorry for delay, but it is a very sensitive logic in Python, so I could not write easily.

**1**-) @converge your tool that says is checking PEP8 is misleading cos actually PEP8 [as of today] highly disgraces that style of usage.
![image](https://user-images.githubusercontent.com/33269249/52206051-7bde1900-2892-11e9-8d0d-c240507b85e1.png)
What PEP8 actually says is,
![image](https://user-images.githubusercontent.com/33269249/52206216-f60e9d80-2892-11e9-907a-6cd051e8788c.png)

It's the same with my linter - **pycodestyle** (_latest version - 2.5.0 [as of today]_).
![image](https://user-images.githubusercontent.com/33269249/52206422-9b297600-2893-11e9-9e84-abff0e9eca32.png)
I was shocked by it once learnt, I will look for another linter now.

So, why PEP8 does not like `'is'` to compare booleans?
There are several reasons I am unaware of. But it is fact that `'is'` must be used only for checking `None`.

Fine, what is `'is'`?
'is' is not checking the value itself. It checks for identity.
```python
if zx is True:
```
is roughly equal to
```python
if id(zx) == id (True)
```

Drawbacks of using '==' to compare bools:
There is 1 case there it behaves differently;
```python
1 == True
0 == False
```
Yes, it's cos True and False are themselves integers...
That's the **only** caveat to be cautious while using direct comparisons on Booleans in python.


Further,
 Before booleans became part of Python they were often defined as part of a program. Even now (_Python `2.7.15`_) they are only names that can be pointed to different objects:
```python
True 👉🏼 <type 'bool'>
True = 1 👉🏼 <type 'int'>
None = 1 👉🏼 SyntaxError: cannot assign to None
```
If so,
```
>>> True = 1
>>> (2 > 1)
True
>>> (2 > 1) == True
True
>>> (2 > 1) is True
False
```

If you try to assign a value to `True` in a newer Python e.g. v3.7.1,
```python
True = 1 👉🏼 SyntaxError: can't assign to keyword
None = 1 👉🏼 SyntaxError: can't assign to keyword
```

#### So, shortly.
 - Booleans **must** be checked/compared as `if cond:` as PEP8 rules.
 - It isn't a strict rule, we can compare it differently UNLESS fully covered.

To have the `if cond:` style applied to our code base:
As I have previously said, bunch of blocks, their logic has to be converted into the single-type return values.
Or _type_+`None` pair.
RATHER THAN multi-type return values.


#### Conclusion
Why there are lots of that situations?
 - I can say, most of them are written by me xD (_sorry for that :P_)
 - I have used multi-type return values JUST FOR the simplicity and flexibility.
 - I really think the future of the programming is going towards [working with] multi-type return values [EVEN THOUGH many masters might disagree].
 - People think multi-type return values are unsafe and dangerous.
 - I agree with people but I have taken care of all of the possible situations.
 - It's just a bit difficult to understand for some programmers when your function returns multi-type values and if not fully covered, it can misbehave.

### Also
You should also know the confusion about the identity of big integers ..
```python
256 is 256
True

256 == 256
True

256 is (255+1)
True

256 == (255+1)
True

257 is (257+1)
False

257 == (257+1)
True
---

Cheers 😁
---

2019-02-07 12:19 UTC, converge commented
alright, PEP8 is our master, let's use if cond: in case cond is True/False. :D