Runtime and skeleton implementation
InstaPy/InstaPy pull request #3705
Opened 2019-01-09 11:40 UTC by lucanello

**For easier use of the script and better multi-account implementation I wrote a runtime which should have every function in it and a skeleton which contains the configuration.**

When running the runtime with `python3 runtime.py <username> <mode (e.g. "only_unfollow" to skip all commands and just execute)>`, the configuration file is loaded and the bot is executed. This configuration file should be like skeleton.py and must be named `run_<username>.py`.

It is important that this runtime contains all commands that InstaPy has to offer in the future. Since I was unfortunately quite inactive lately, I could not implement some things.
This includes e.g. @uluQulu's Quota Supervisor. But I also couldn't finish the unfollow commands properly.

But I added more features like an integration to Pushover. I will extend this in the future. With Pushover it is possible to get a notification on your mobile phone about the last run bot.

Please ignore the `write_result` command at the bottom. This feature will be added later. It will add the possibility to write the results to a database in order to monitor your bots.

In the next step I would like to extend this runtime and the skeleton in such a way that we gradually approach an API. 

Thanks for your help!
Best regards,
Luca

2019-01-09 13:07 UTC, uluQulu commented
Awesome, @lucanello 
I will read it soon.

---

Cheers 😁
---

2019-01-09 17:28 UTC, w4ngel requested changes
run_skeleton.py - why is this a python file? It could just be a JSON file then you load it in the runtime.py

runtime.py - things should be run `with smart_run` this is due to that handling a load of errors and making sure the program closes properly, you can put the try/finally code. Though it isn't necessary I would highly recommend it, otherwise you can encounter issues like hanging processes etc.

2019-01-09 21:41 UTC, lucanello commented
Hi @w4ngel, thanks for your feedback. It was easier for me to load the configuration from a python file. I think I had some problems with JSON decoding. I'm sure you can do better and help me with that :)

Also, what do you mean with smart_run?

2019-01-09 23:49 UTC, w4ngel commented
> Hi @w4ngel, thanks for your feedback. It was easier for me to load the configuration from a python file. I think I had some problems with JSON decoding. I'm sure you can do better and help me with that :)
> 
> Also, what do you mean with smart_run?

Smart_run is a feature that most of the quickstart templates use. If you can add me as a collaborator I will be able to edit your fork for you.

2019-01-11 11:55 UTC, w4ngel commented
@lucanello if you let me know when you have added me so I can make the change.

2019-01-11 17:14 UTC, w4ngel commented
Ok, so the reason your JSON wasn't working is that it wasn't formatted like JSON properly. I am correcting this now as well as implementing smart_run on the skeleton.

2019-01-11 17:24 UTC, w4ngel commented on runtime.py
> +from plugins.statistics import write_result
Are these two plugin.stats and plugin.mail_support modules custom?

2019-01-11 17:24 UTC, w4ngel commented on runtime.py
> +from plugins.mail_support import mail_result
And here as well...

2019-01-11 17:24 UTC, w4ngel commented on runtime.py
> +    session.end()
Did you do all of this on a separate branch or your master branch?

2019-01-11 19:34 UTC, lucanello commented on runtime.py
> +from plugins.statistics import write_result
Yes, I'm planning to create a PR as soon as possible. Unfortunately it seems like everyone was writing on an analytics dashboard. And I don't think we need 4.

2019-01-11 19:34 UTC, lucanello commented on runtime.py
> +from plugins.mail_support import mail_result
Look above :)

2019-01-11 19:34 UTC, lucanello commented on runtime.py
> +    session.end()
I did these changes on my master branch.

2019-01-15 11:22 UTC, w4ngel commented
@lucanello I am going through the runtime skeleton right now, and I am not exactly too sure what you are trying to achieve... There is a lot of bespoke configuration for your PC here. Along with unnecessary logging, parsing etc. When you have used InstaPy in the past have you managed to use any quickstart templates or tried to?

2019-01-17 20:25 UTC, lucanello commented
Hi @w4ngel, the skeleton file is only a template to setup the runtime. The runtime and skeleton are meant to replace the quickstart scripts.

2019-04-02 16:18 UTC, closed without merging