Added all the possible xpath to find login button
InstaPy/InstaPy pull request #4218
Opened 2019-03-27 14:15 UTC by CharlesCCC

Currently running into issue when login into account. looks like instagram is changed their xpath again for login button.

2019-03-28 03:07 UTC, timgrossmann commented
@CharlesCCC Awesome, thank you very much for this update! 
Could you please make sure that the CI passes? :blush:

2019-03-28 11:43 UTC, CharlesCCC commented
@timgrossmann  I would love to, but TBH, I have no idea how to fix that, As I view the log,it failed to call ` tox` command ??? Is there anyway I can kick off the build again ?

2019-03-31 00:12 UTC, converge requested changes

2019-03-31 00:12 UTC, converge commented on instapy/login_util.py
>              "//div[text()='Log in']")
I believe the "Log in" way doesn't exist, am I wrong?

I'm just able to find "Log In" button.

2019-03-31 00:12 UTC, converge commented on .gitignore
> +.bak
In this for Mysql Workbench backup file?

2019-03-31 00:34 UTC, CharlesCCC commented on instapy/login_util.py
>              "//div[text()='Log in']")
You probably right, I was accumulated all the possible option from the previous changes.

2019-03-31 00:43 UTC, CharlesCCC commented on .gitignore
> +.bak
actually, it was from Notepad++ file.  but it could be others as well.

2019-04-02 01:16 UTC, hugio55 commented on .gitignore
> +.bak
I am pretty new to this whole world. Where is this .gitignore file?

2019-04-02 17:01 UTC, timgrossmann commented
@CharlesCCC @converge which changes do you exactly want for this PR?
I think it's good to cover "every" possible combination here.

Please define so we can merge this 😊

2019-04-02 17:58 UTC, CharlesCCC commented
@timgrossmann I would say keep all the possible. There should be nothing to hurt. worst case is it take couple more second to login the user, but (it just one second every 3 months, since the cookie are cached).

2019-04-03 11:58 UTC, converge commented
It's all good for me, I just don't know how to deal with the "Log In" vs "Log in". It's hard to test it because it just catches "Log In" on my side, and I don't know if people catch "Log in".

2019-04-04 11:32 UTC, mkhattar commented
I changed "Log in" to "Log In", seems the text on the button changed. Please can someone else test it to confirm?

2019-04-04 14:25 UTC, CharlesCCC commented
@mkhattar @converge I have replaced "log in" with "Log In".

2019-04-04 17:23 UTC, converge approved these changes

2019-04-04 21:10 UTC, orhan-drsn commented
What about:
`from selenium.webdriver.common.keys import Keys`

`(ActionChains(browser)`
`        .move_to_element(input_password[0])`
        `.click()`
        `.send_keys(Keys.ENTER)`
        `.perform())`

Maybe this is the best way to don't have problems in future

2019-04-04 22:35 UTC, CharlesCCC commented
@orhan-drsn Seems a good idea, Have you tested it ? if yes, I will make the update to implement that . thank you

2019-04-05 04:51 UTC, orhan-drsn commented
@CharlesCCC yes it works for me.
It's like a real human would do it. After entering the passwort to push enter

2019-04-05 14:56 UTC, CharlesCCC commented
@orhan-drsn Thank you for confirming that, I made the change and also tested it locally, seems working really well.

2019-04-05 17:43 UTC, converge commented
@orhan-drsn great idea!

2019-04-06 02:52 UTC, merged

2019-04-06 02:53 UTC, timgrossmann commented
@CharlesCCC @orhan-drsn Thank you very much for this, guys! This will remove a lot of problems in the future 🙌