XPath Isolation
InstaPy/InstaPy pull request #4301
Opened 2019-04-11 11:14 UTC by analyticsdept

The goal of this is to remove reliance on any hardcoded XPath values by moving them into a separate file, minimizing risk to the code when edits are made and enabling simpler maintenance.

- Created new XPath reader function (read_xpath) to handle parsing of a JSON file containing the necessary XPaths; done this way to easily transition to a hosted XPaths file in the future

- Added an XPath JSON compiler util - maintain the XPaths in this Python file; when run it will overwrite the existing xpath.json file in the instapy directory. The JSON structure follows the pattern `function name: { xpath name: xpath value [, ...] } [, ...]`

- Updated all of the functions within InstaPy to use the read_xpath function instead of relying on hard-coded values

2019-04-11 20:27 UTC, breuerfelix commented
I really like this refactor !! finally instapy is getting split up part by part into a nice project :)

I got 2 suggestions:  
1) not binding xpaths to a function name, rather grouping them by the pages they are on.   example groups: `login_page`, `profile`, `story`, `post` so if we look at the groups, we know to which kind of page they belong on instapy. since xpaths are related to the instagram web page, for me it makes sense to Group them by these pages :)

let me know what you think ! (but this refactor could be also done in the future !)

2) we read in the json file for every xpath, I would delete the json file for now :) since you overwrite it on every start anyways, why don't just keep the xpaths in memory ? we can save a lot of disk reads :)  
just import the xpath object directly in the xpath.py file and we are done :) 

btw this work is awesome ! I can imagine this being a lot of work separating all these xpaths and it was really needed ! this will be so damn handy in the future :) thanks !!

2019-04-11 20:28 UTC, breuerfelix requested changes

2019-04-11 20:28 UTC, breuerfelix commented on instapy/xpath.py
> +def read_xpath(function_name, xpath_name):
just import xpath object from xpath_compile here, and use it directly from memory :)

2019-04-11 20:28 UTC, breuerfelix commented on instapy/xpath_compile.py
> +with open('xpath.json', 'w') as outfile:
delete this

2019-04-11 20:28 UTC, breuerfelix commented on instapy/xpath.py
> +    with open(fn) as json_file:
delete that

2019-04-11 20:28 UTC, breuerfelix commented on instapy/xpath.py
> +def read_xpath(function_name, xpath_name):
just import xpath object from xpath_compile.py and use it directly from memory

2019-04-11 20:28 UTC, breuerfelix commented on instapy/xpath.json
> +{"get_comments_on_post": [{"unlike_button_full_XPath": "//div/span/button/span[@aria-label='Unlike']", "like_button_full_XPath": "//div/span/button/span[@aria-label='Like']", "comments_block": "//div
delete this file

2019-04-12 06:36 UTC, analyticsdept commented
> 1. not binding xpaths to a function name, rather grouping them by the pages they are on.   example groups: `login_page`, `profile`, `story`, `post` so if we look at the groups, we know to which kind of page they belong on instapy. since xpaths are related to the instagram web page, for me it makes sense to Group them by these pages :)
> 
> let me know what you think ! (but this refactor could be also done in the future !)

I was a little hesitant to do this since some of the functions that used XPaths are out of context and to be honest I have no idea which screen they relate to. I'm happy to do this, but is there a place on here that we can document which function relates to which screen? For now I'm going to make all of the other changes and commit them and continue that work as an enhancement if that's cool?

> 1. we read in the json file for every xpath, I would delete the json file for now :) since you overwrite it on every start anyways, why don't just keep the xpaths in memory ? we can save a lot of disk reads :)
>    just import the xpath object directly in the xpath.py file and we are done :)

You're totally right about the disk reads - if we ever move to hosted/CDN XPaths this can be looked at again!

> btw this work is awesome ! I can imagine this being a lot of work separating all these xpaths and it was really needed ! this will be so damn handy in the future :) thanks !!

No problem at all! It definitely took a minute or two :P

2019-04-12 06:48 UTC, analyticsdept commented on instapy/xpath.py
> +def read_xpath(function_name, xpath_name):
Cool, I've made this change - it'll be in my new commit

2019-04-12 07:50 UTC, breuerfelix reviewed
thanks for the refactor! looks way clear now :)  
the most important thing is, that each xpath is resolved by the same function, because with that refactor its really easy in the future to refactor it to a cdn !

I am so sorry I just read over it one more time cause I wanted to propose the merge for dev branch and then I saw another thing...

I made comments in the code :) why do you made a list in that case ? maybe my idea with the nested key value store might be not that good because I don't think about some details you thought about in the past :D but until now I would suggest just doing this key value store cause we don't need the list anyways.

But btw of course we could keep the names as they are right now ! thats just something we could change in the future :D

2019-04-12 07:50 UTC, breuerfelix commented on instapy/xpath.py
> +        xpath_val = p[xpath_name]
this would be easier:
return xpath[function_name][xpath_name]

2019-04-12 07:50 UTC, breuerfelix commented on instapy/xpath_compile.py
> +xpath['bypass_suspicious_login'] = []
since you only got one element in the array, and its one big key values store you can do it more easily:
xpath['bypass_suspicious_login'] = {
     "bypass_with_mobile_choice":"//label[@for='choice_0']",
     "bypass_with_mobile_button":"//label[@for='choice_0']",
     "choice":"//label[@for='choice_1']",
     "choice_no_such_element":"//label[@class='_q0nt5']",
     "choice_exception":"//label[@class='_q0nt5 _a7z3k']",
     "close_button":"[text()='Close']",
     "security_code_field":"//input[@id='security_code']",
     "send_security_code_button":"//button[text()='Send Security Code']",
     "submit_security_code_button":"//button[text()='Submit']",
     "this_was_me_button":"//button[@name='choice'][text()='This Was Me']",
     "wrong_login":["//p[text()='Please check the code we sent you and try ","again.']"]
 }

2019-04-12 08:04 UTC, analyticsdept commented on instapy/xpath.py
> +        xpath_val = p[xpath_name]
Cool, done - thanks for simplifying it :)

2019-04-12 09:13 UTC, analyticsdept commented on instapy/xpath_compile.py
> +xpath['bypass_suspicious_login'] = []
Way cleaner! Thanks for the suggestion - added to the new commit :)

2019-04-12 09:23 UTC, analyticsdept commented
> I made comments in the code :) why do you made a list in that case ? maybe my idea with the nested key value store might be not that good because I don't think about some details you thought about in the past :D but until now I would suggest just doing this key value store cause we don't need the list anyways.

A key/value store is cool - I just like neat groups so its easier to identify relationships between things in the code. That said, it's totally just a personal preference!

I think there's even more work that can be done from a cleanliness perspective - like having a predefined template for the objects... In a few cases there are alternate XPaths for NoSuchElement exceptions, and there's also no naming conventions for buttons, inputs, etc - so it may be a good idea to document a standard for how to deal with capturing those. In some cases XPaths are referenced inline and others are stored in local variables at the top of a function, so all of that could be cleaned up :)

```
function_name: {
element_name: {
xpath: "",
exception_xpath: ""
}
}
```

Thanks for all the feedback! Hopefully I've covered everything in my latest commit but let me know if I've missed something :)

2019-04-13 13:56 UTC, breuerfelix approved these changes

2019-04-13 14:30 UTC, breuerfelix commented
> A key/value store is cool - I just like neat groups so its easier to identify relationships between things in the code. That said, it's totally just a personal preference!

No I was talking about the array inside the first key value :P I love the idea of the grouped key value store ! really cool idea :)

thanks for the refactor, it looks really clean and neat now :P 

now its up to @timgrossmann to merge this one !

2019-04-15 01:33 UTC, timgrossmann commented
@analyticsdept @breuerfelix Awesome guys, looks much cleaner now and I really like the structure of the xPaths! :raised_hands: 

In terms of code it's definitely ready to be merged.
We just need to make sure we test it before releasing it to the people.

Thank you very much!

2019-04-15 14:29 UTC, timgrossmann commented
Just gave it a quick test and seems to work fine! 
I'll do more testing before we merge the dev branch into master.

Thank you very much for isolating the xPaths from the codebase :blush:

2019-04-15 15:12 UTC, merged

2019-04-15 15:31 UTC, analyticsdept commented
@timgrossmann thanks to you and @breuerfelix for reviewing and the helpful comments... and you're totally welcome :) Hopefully it's going to save a few headaches in the future!

2019-04-16 03:49 UTC, ishandutta2007 reviewed
?

2019-04-16 03:49 UTC, ishandutta2007 commented on instapy/xpath.json
> +{"get_comments_on_post": [{"unlike_button_full_XPath": "//div/span/button/span[@aria-label='Unlike']", "like_button_full_XPath": "//div/span/button/span[@aria-label='Like']", "comments_block": "//div
My understanding from the discussion under #4279 was that we are to going to fetch this file over the network than hardcoding into codebase such that code instapy don't have to be updated for every xpath changes. @breuerfelix correct me if my understanding is wrong. @breuerfelix I agree with you on the part that this can be fetched from a CDN than a data store since it is static.

2019-04-16 07:24 UTC, breuerfelix commented on instapy/xpath.json
> +{"get_comments_on_post": [{"unlike_button_full_XPath": "//div/span/button/span[@aria-label='Unlike']", "like_button_full_XPath": "//div/span/button/span[@aria-label='Like']", "comments_block": "//div
@ishandutta2007 you are totally right ! but this PR is the first step towards this :)
now we call a function for each xpath so we just have to change this function and we are done, it will be kinda easy now, this step HAS to be done no matter what.

So this PR was like a preparation for the CDN :) maybe I got time to finish it or got time to make a proper issue describing the behaviour in the next days :)

2019-04-16 08:09 UTC, ishandutta2007 commented on instapy/xpath.json
> +{"get_comments_on_post": [{"unlike_button_full_XPath": "//div/span/button/span[@aria-label='Unlike']", "like_button_full_XPath": "//div/span/button/span[@aria-label='Like']", "comments_block": "//div
cool, just wanted to be sure I am on same page as I haven't gone through rest of the discussing in the CR. @breuerfelix was discussing a usecase for CDN with @timgrossmann for pods feature as well but for now will use DB.

2019-04-16 08:22 UTC, analyticsdept commented on instapy/xpath.json
> +{"get_comments_on_post": [{"unlike_button_full_XPath": "//div/span/button/span[@aria-label='Unlike']", "like_button_full_XPath": "//div/span/button/span[@aria-label='Like']", "comments_block": "//div
@ishandutta2007 yeah, once it's decided which CDN is right for this project, we can build the pull mechanism.