Blacklist refactor
InstaPy/InstaPy pull request #4602
Opened 2019-07-01 12:34 UTC by anthonymartin

- fixes blacklist feature (won't follow or add comments if blacklist entry exists)
- refactors blacklist
- blacklist class created
- blacklist unit tests

2019-07-03 05:49 UTC, timgrossmann commented
@anthonymartin Could you please check if you can make the ci succeed and fix the codacy issues? 😊

2019-07-04 17:02 UTC, anthonymartin commented
Do you know if I put an underscore _ for the variable that's not used will pass the linter? https://app.codacy.com/app/timgrossmann/InstaPy/file/36015097899/issues/source?bid=11848437&fileBranchId=13282535#l34

and do you or anyone else have suggestions for how to handle this issue? 
https://app.codacy.com/app/timgrossmann/InstaPy/file/36015097899/issues/source?bid=11848437&fileBranchId=13282535#l14

I need to instantiate the InstaPy class to make my test run, but I don't need it to actually connect to instagram

2019-07-08 19:08 UTC, breuerfelix commented
> Do you know if I put an underscore _ for the variable that's not used will pass the linter? https://app.codacy.com/app/timgrossmann/InstaPy/file/36015097899/issues/source?bid=11848437&fileBranchId=13282535#l34
>
 
Yes that works :). 
according to [this](https://stackoverflow.com/questions/24928585/python-for-loop-without-index-and-item/24928645) SO post that works.

> and do you or anyone else have suggestions for how to handle this issue?
> https://app.codacy.com/app/timgrossmann/InstaPy/file/36015097899/issues/source?bid=11848437&fileBranchId=13282535#l14
> 
> I need to instantiate the InstaPy class to make my test run, but I don't need it to actually connect to instagram

We gonna disable this warning because we also have this warning in the main repo.

Codacy is not as important as Travis :) Do you know why you have this many travis Errors ?  
3.7 is running fine but all other version are getting alot of errors.

2019-07-09 08:11 UTC, breuerfelix requested changes

2019-07-09 08:11 UTC, breuerfelix commented on tests/blacklist_test.py
> +        cls.session = InstaPy(username=username, password=password, bypass_suspicious_attempt=True, headless_browser=True)
you dont need to create an instapy class here, I guess if you would remove this, all tests would run fine again.

you don't reuse the session anyways in your tests so it doesn't matter :)

2019-10-20 13:00 UTC, closed without merging