adds posts post threshold (time) to settings
InstaPy/InstaPy pull request #4651
Opened 2019-07-12 17:01 UTC by converge

- minor adjustment to remove the hardcoded hour threshold/limit.
- I did identify a bug in how we're collecting the post date, going to fix it on next PR.

2019-07-13 11:41 UTC, ishandutta2007 requested changes

2019-07-13 11:41 UTC, ishandutta2007 commented on instapy/settings.py
> +    pods_active_post_hour_limit = 12
Lets make it 2 or 3 hours, that's what instagram uses to decide if a post needs to go viral or not. Initially we had set it high as we were not sure how much traffic we may get, but now we are getting hundreds of post each hour.

2019-07-13 11:41 UTC, ishandutta2007 commented on instapy/instapy.py
> +                    # FIXME: datetime HTML TIME element is different
Yes I noticed this long back. For 12.5 hour window it wasn't a big issue, when we reduce the window we will need to use local time.

2019-07-16 17:55 UTC, converge commented
going to update this PR soon, please don't merge it just yet.

2019-07-17 09:29 UTC, breuerfelix commented
please remove the tag when we are ready to merge it ! so its easier to know which PRs are ready to merge when having a look at the PR list :)

2019-08-12 19:04 UTC, ishandutta2007 commented
@converge where are we on this, I thought you said you will address the timezone issue and resubmit?

2019-08-12 20:20 UTC, converge commented
hey @ishandutta2007 , sorry for the delay, I'll postpone it, I have been working to make instapy more stable for now. I will reach it soon.

2019-08-13 01:53 UTC, ishandutta2007 commented
Lets merge the rest then ? Create a separate issue to track the timezone issue ?

2019-10-20 13:02 UTC, closed without merging