Feature/stories v2
InstaPy/InstaPy pull request #4673
Opened 2019-07-17 23:46 UTC by christophe-duc

- added code to parse and understand the JSON story request
- fix various bugs (non existent page, or private page reported by @converge) 
- fix documentation (removed the word try reported by @converge )

passed testing:
  - interact OK
  - story_by_tags OK
  - story_by_users OK

2019-07-18 10:01 UTC, breuerfelix commented
could you fix the travis bug maybe ? I don't know 100% what's wrong there but I think you first have to combine the args and then pass it as one list to the function :) correct me if I am wrong !

2019-07-18 11:55 UTC, christophe-duc commented
> could you fix the travis bug maybe ? I don't know 100% what's wrong there but I think you first have to combine the args and then pass it as one list to the function :) correct me if I am wrong !

corrected and re-tested

2019-07-19 07:27 UTC, breuerfelix commented on instapy/story_util.py
> +        if (cookie['name'] == "urlgen") or (cookie['name'] == "rur"):
just to avoid duplicate code (cause I hate that :D)

what about:

```python
all_args = {
                 'name': cookie['name'],
                 'value': cookie['value'],
                 'domain': cookie['domain'],
                 'secure': cookie['secure'],
                 'rest': {'HttpOnly': cookie['httpOnly']},
                 'path': cookie['path']
             }
if not (cookie['name'] == "urlgen") and not (cookie['name'] == "rur"):
             all_args['expires'] = cookie['expiry']
         
         s.cookies.set(**all_args)
```

I hope I negotiated the if statement correctly :D

2019-07-19 07:30 UTC, breuerfelix commented
I like the changes :) but I think @converge is more in the topic and lets wait for his review !! :)

Just one question, is it easy to add how many max stories to watch ? maybe per user and per session ?

its now hardcoded to 20 but it could be just a param right ? :)

2019-07-19 07:41 UTC, timgrossmann commented
@christophe-duc @breuerfelix One thing we could also take into account is leaverging

2019-07-19 11:15 UTC, christophe-duc commented on instapy/story_util.py
> +        if (cookie['name'] == "urlgen") or (cookie['name'] == "rur"):
yes, i'll make the change. thanks!

2019-07-19 11:24 UTC, christophe-duc commented
> I like the changes :) but I think @converge is more in the topic and lets wait for his review !! :)
> 
> Just one question, is it easy to add how many max stories to watch ? maybe per user and per session ?
> 
> its now hardcoded to 20 but it could be just a param right ? :) and the default value of this param will be 20. so nothing big will change.

Here 20 is the max amount of reels_item I have seen being able to receive in the JSON response of the graphql query, for the moment I am not able to watch just one or to stop after a certain amount has been viewed as there is a lot of JS events involved and the code is quite obfuscated.

In the traces, I took, there are additional reporting that is done to instagram (when one reel was seen apparently), but I haven't played with it yet. (possibly being able to report something watched even if we haven't, could help with the other comment from @timgrossmann )

2019-07-19 20:03 UTC, breuerfelix commented
so basically, every change requested would mean to put a lot of work into this feature. so I guess we could say thats version 1, we should merge this PR and release it with 1.5.6 :))

2019-07-20 17:18 UTC, converge requested changes
just these small changes and it's all good for me. and just as a note for future code, just a little more documentation, and it will be perfect. great work! 🤘 🤘 🤘

2019-07-20 17:18 UTC, converge commented on instapy/story_util.py
> +def get_story_data(browser, elem: str, action_type: str, logger) -> dict:
are we using strong typing elsewhere on InstaPy? if not, it would be nice to follow the style (weak typing) the majority of the code uses.

2019-07-20 17:18 UTC, converge commented on instapy/story_util.py
> +        graphql_query_url = "https://www.instagram.com/graphql/query/?query_hash" + \
it's "cosmetic" as some people say, but I believe it's important to make it more readable, does it make sense?

```python
# this is just a quick example and doesn't work
graphql_query_url = (
            'https://www.instagram.com/graphql/query/?query_hash={}'
            '&variables={"reel_ids":[],"tag_names":["{}"],"location_ids":[],'
            'highlight_reel_ids": [], "precomposed_overlay": false, '
            'show_story_viewer_list": true, "story_viewer_fetch_count": 50, '
            'story_viewer_cursor": "", "stories_video_dash_manifest": false}'
            .format(query_hash, elem)
        )
```

2019-07-20 17:18 UTC, converge commented on instapy/story_util.py
> +    s = requests.Session()
sorry for more cosmetic things, but I need to point it also, session instead of session will give more sense for what the code is doing.

2019-07-20 20:18 UTC, christophe-duc commented on instapy/story_util.py
> +def get_story_data(browser, elem: str, action_type: str, logger) -> dict:
the strong typing was introduced by @breuerfelix in the first merged branch of stories.

see here: [https://github.com/timgrossmann/InstaPy/pull/4670/commits/2c43359979b3ab9b19742e5575fa9d5e821c63ad](url)

That's why I re-used it, I though it was a new rule. Let me know what you guys decide and i'll update the function prototypes.

2019-07-20 22:56 UTC, christophe-duc commented on instapy/story_util.py
> +        graphql_query_url = "https://www.instagram.com/graphql/query/?query_hash" + \
fixed and rewrote the code to be simpler.

2019-07-20 22:56 UTC, christophe-duc commented on instapy/story_util.py
> +    s = requests.Session()
no problem, fixed.

2019-07-21 09:00 UTC, breuerfelix commented on instapy/story_util.py
> +def get_story_data(browser, elem: str, action_type: str, logger) -> dict:
well typing is not present in instapy at all but I have to get into typing for the gui (at least for the api functions in instapy) so I think that if you are able to write types, you always should because the compiler doesn't care if you give a string or an int (even if you said it should be string) the code won't break BUT as a programmer the code is way easier to understand :)

Sometimes its not possible (or hard possible) for example with the browser object. So yeah don't use types here if its to difficult, but in general I would say, always try to use types :)

what do you think about it ?

2019-07-21 17:18 UTC, christophe-duc commented
@timgrossmann : following your mass story comment, I have tried to evolve the code. I am happy to report that I am fully capable now to completely simulate the control plane of watching stories. It means I am able to make instagram believe you watched the stories, when you actually didn't perform the action on the web page.

Code is ready, I'll create 2 modes for watching stories, a real mode that uses the web interface as a user would do and a simulated mode that just send the commands to instagram.

Let me know if I shall include this into the PR.

2019-07-22 00:47 UTC, converge commented on instapy/story_util.py
> +def get_story_data(browser, elem: str, action_type: str, logger) -> dict:
I would prefer to keep with the old InstaPy code style (weak typing). I think about new contributors facing two code style, can be confusing for them.

2019-07-22 08:21 UTC, breuerfelix requested changes
yep I am the human linter :D

maybe today I will take some time and specify the linter and also specify that the linter fixes whitespace itself (I always do that in my javascript projects) cause this is just a pain in the ass.

sorry that you have to do it manually right now :D

btw you are a beast ! really awesome feature programmed in this short amount of time. I wanna get it merged by today !

2019-07-22 08:21 UTC, breuerfelix commented on instapy/story_util.py
> +            #correct formating for elem_id
no whitespace after hashtag in comments :) since we wanna add that rule to the linter, better start correcting it right away :D

there are couple of these comments, just a small fix

2019-07-22 08:21 UTC, breuerfelix commented on instapy/story_util.py
> +            seen=0
whitespace also for things like this :) its just prettify :D

2019-07-22 08:21 UTC, breuerfelix commented on DOCUMENTATION.md
> +session.set_do_story(enabled = True, percentage = 70, simulate=True)
simulate = True (whitespace)

2019-07-22 08:21 UTC, breuerfelix commented on instapy/instapy.py
> +    def set_do_story(self, enabled: bool = False, percentage: int = 0, simulate: bool=False):
bool = False (whitespace)

2019-07-22 08:21 UTC, breuerfelix commented on instapy/story_util.py
> +def get_story_data(browser, elem: str, action_type: str, logger,simulate: bool=False) -> dict:
logger, simulate: bool = False (3x whitespace)

2019-07-22 12:52 UTC, breuerfelix approved these changes
thanks ! human linter is happy now :D

2019-07-22 17:28 UTC, merged