fix useragent
InstaPy/InstaPy pull request #4701
Opened 2019-07-23 16:59 UTC by breuerfelix

2019-07-23 19:59 UTC, converge requested changes
I see that there is a new parameter random_user_agent, what do you think about to make it less complex?

at the moment InstaPy is quite complex, we have been adding a lot of options, I think we should start to make it less flexible, it opens space for more bugs, and maybe no user will use this option

2019-07-23 19:59 UTC, converge commented on instapy/browser.py
> +        ua = UserAgent(cache = False, fallback = fb_agent)
little mistake, it should be `user_agent` not `fb_agent`

2019-07-23 19:59 UTC, converge commented on instapy/browser.py
> +        # only work in chrome
I did test, it also works in Firefox

2019-07-24 06:58 UTC, breuerfelix commented on instapy/browser.py
> +        ua = UserAgent(cache = False, fallback = fb_agent)
dang I shouldn't have done it quick at work :D thanks for mentioning :)

2019-07-24 06:58 UTC, breuerfelix commented on instapy/browser.py
> +        # only work in chrome
this is really strange because Joe also had errors here on raspberry pi ... I will test it in deep next days, so I put I back until then :)

2019-07-24 07:03 UTC, breuerfelix commented
fixed changes !

2019-07-24 10:09 UTC, converge approved these changes
🤘

2019-07-24 10:25 UTC, merged