Fixed follow_commenters() and updated xpaths
InstaPy/InstaPy pull request #4892
Opened 2019-08-17 20:12 UTC by brnskn

After changing of user agent(iphone x) instagram web page was changed and xpaths need to be changed. I have fixed xpaths and logics that make follow_commenters function worked.

2019-08-18 16:53 UTC, converge requested changes
I believe these small changes will make it better and ready to push to `dev`.

2019-08-18 16:53 UTC, converge commented on instapy/commenters_util.py
> +from .util import get_current_url
Selenium already provide this function, it's called `browser.current_url`

2019-08-18 16:53 UTC, converge commented on instapy/commenters_util.py
> +def check_exists_by_tag_name(element, tag_name):
I believe this is unnecessary, `.find_element_by_xpath` for example will already give us the results we need to (success or error), this would add more code for us to care about. At the moment we're trying to decrease complexity.

2019-08-18 16:53 UTC, converge commented on instapy/commenters_util.py
> +        print("\nError: Couldn't get user profile. Moving on.." + str(e))
that's perfect, we're adding more info to the user.

2019-08-18 17:27 UTC, brnskn commented on instapy/commenters_util.py
> +        print("\nError: Couldn't get user profile. Moving on.." + str(e))
Also, we will be knowing more information about the error from the log.

2019-08-30 12:08 UTC, breuerfelix commented
@converge since you started this review, would be cool if you could resolve your changes :))

2019-09-01 06:26 UTC, merged