Fix verify_liking, window.insta_data is undefined
InstaPy/InstaPy pull request #5057
Opened 2019-09-12 13:48 UTC by turtlebking

as some instagram raw data stored in 'window._sharedData.entry_data.PostPage[0]' but not 'window.__additionalData[Object.keys(window.__additionalData)[0]].data'.

also fixed verify_liking

2019-09-12 14:21 UTC, turtlebking commented
For the pull request, I have an error on 'black' checking at github. it runs ok on my local 'black' checking.  i don't know what to do now. Hope someone can shed me some light.

black run-test: commands[0] | black -t py34 --check .
would reformat /home/travis/build/timgrossmann/InstaPy/instapy/relationshiptools.py
would reformat /home/travis/build/timgrossmann/InstaPy/instapy/util.py
would reformat /home/travis/build/timgrossmann/InstaPy/instapy/instapy.py
All done! :boom: :broken_heart: :boom:
3 files would be reformatted, 30 files would be left unchanged.
ERROR: InvocationError for command /home/travis/build/timgrossmann/InstaPy/.tox/black/bin/black -t py34 --check . (exited with code 1)
__ summary __
ERROR:   black: commands failed

2019-09-13 11:16 UTC, breuerfelix commented
@turtlebking you have to remove the --check option if you run it locally :)

then black will not check your files, It will actually convert them. after that, push the changes and black will pass :)

2019-09-13 18:05 UTC, turtlebking commented
> @turtlebking you have to remove the --check option if you run it locally :)
> 
> then black will not check your files, It will actually convert them. after that, push the changes and black will pass :)

@breuerfelix Thank you!!! now all check pass.

2019-09-13 20:14 UTC, breuerfelix commented
well now you added alot of changes which were not there before :D and some really strange ones.. guess they were cause you were debugging :D I will make some notes

2019-09-13 20:16 UTC, breuerfelix requested changes

2019-09-13 20:16 UTC, breuerfelix commented on instapy/comment_util.py
> +            # browser.execute_script("location.reload()")
why comment these ones out ?

2019-09-13 20:16 UTC, breuerfelix commented on instapy/like_util.py
> +import sys
if we don't need the exit, remove this one too

2019-09-13 20:16 UTC, breuerfelix commented on instapy/like_util.py
> +    # logger.info("Description: {}".format(image_text.encode("utf-8")))
why comment ?

2019-09-13 20:16 UTC, breuerfelix commented on instapy/like_util.py
> +        sys.exit(0)
bot will already do a shutdown... no need to exit that hard here :D

2019-09-13 20:16 UTC, breuerfelix commented on instapy/login_util.py
> +    # if "instagram.com/accounts/onetap" in browser.current_url:
why adding these comments ?

2019-09-13 20:16 UTC, breuerfelix commented on instapy/unfollow_util.py
> +                # browser.execute_script("location.reload()")
why comment out ?

2019-09-14 06:41 UTC, turtlebking commented on instapy/like_util.py
> +    # logger.info("Description: {}".format(image_text.encode("utf-8")))
i switched it off when debugging and forgot to put it back. i will fix it

2019-09-14 06:42 UTC, turtlebking commented on instapy/like_util.py
> +        sys.exit(0)
ok, i will remove that

2019-09-14 06:45 UTC, turtlebking commented on instapy/login_util.py
> +    # if "instagram.com/accounts/onetap" in browser.current_url:
i m new to github. it is the local version running on my raspPi3+, i did not know it will include in pull request. will fix it back

2019-09-14 06:47 UTC, turtlebking commented on instapy/comment_util.py
> +            # browser.execute_script("location.reload()")
i m new to github. it is the local version running on my raspPi3+, i did not know it will include in pull request. will fix it back

2019-09-14 06:48 UTC, turtlebking commented on instapy/like_util.py
> +import sys
ok, will remove this one

2019-09-14 07:02 UTC, turtlebking commented on instapy/unfollow_util.py
> +                # browser.execute_script("location.reload()")
will fix it back

2019-09-14 07:25 UTC, turtlebking commented
@breuerfelix Sorry for the mistakes, some files are my local debugged version upload to github, not expecting they were included on pull request. my 1st time to use github, i apology for the mess.

2019-09-14 20:15 UTC, kailynw commented
You have to have the older version of Firefox installed (59.0.2)
Run these commands to uninstall the current version, install the older version and keep it from updating to newer version

Commands:
sudo apt-get remove firefox         //removes firefox
apt-cache show firefox | grep Version         //Show version of firefox
sudo apt-get install firefox= 45.0.2+build1-0ubuntu1  **OR**  59.0.2+build1-0ubuntu1   //install
 sudo apt-mark hold firefox       //keeps from updating

2019-09-15 03:33 UTC, turtlebking commented
Thank you so much!! I will try :)

2019-09-15 14:58 UTC, breuerfelix commented
@turtlebking thanks for the fixes :) PR looking clean now :)

@kailynw does that mean that this PR is only for older versions of firefox ? so this PR would crash if you have the latest firefox ?

2019-09-15 15:02 UTC, kailynw commented
@breuerfelix 

Correct! Matter of fact, I didn't need to import those new scripts added by @turtlebking

2019-09-15 15:10 UTC, breuerfelix commented
well @turtlebking this is kinda sad because I don't wanna merge this PR if it will crash on newer firefox versions ...

I am sorry for all the work you put into this PR ! but I realised you made some other changes than the fix of the additional data, if you are not tired yet, could you remove breaking changes and just leave the non breaking changes in there ? that way I could merge at least some of your work :)

but I can understand if you are tired of getting hands on this PR again ! would be no problem if you close this one and maybe we can see another PR from you in the future :)

2019-09-15 22:38 UTC, turtlebking commented
> well @turtlebking this is kinda sad because I don't wanna merge this PR if it will crash on newer firefox versions ...
> 
> I am sorry for all the work you put into this PR ! but I realised you made some other changes than the fix of the additional data, if you are not tired yet, could you remove breaking changes and just leave the non breaking changes in there ? that way I could merge at least some of your work :)
> 
> but I can understand if you are tired of getting hands on this PR again ! would be no problem if you close this one and maybe we can see another PR from you in the future :)

I don’t install older version Firefox, They are running on latest Firefox version. No big deal if u don’t include them in the branch. I run them on my raspberry pi raspbian 
buster. Thanks for your help, really appreciate! :)

2019-09-16 05:26 UTC, closed without merging