Solution to #503
InstaPy/InstaPy pull request #521
Opened 2017-08-10 17:08 UTC by NedYork

Clarifai recently changed the way users could access their API (traditionally done with app_id and app_secret). Now they only provide an api_key and will deprecate the old way sometime towards end of 2017. 

This pull request removes app_id and app_secret from the API call and replaces it with api_key and updates the documentation. Clarifai's V2 API also only supports matching input photos against an existing model so that was updated in the clarifai_util.py file as well. 

Documentation was also updated.

2017-08-11 07:53 UTC, timgrossmann commented
@NedYork Awesome!
Thank you for this.

Could you make sure that in the documentation you add the new `api_key=xxx` in the examples?
I'll request changes for one of those, please find the other instances of it.

Thank you for contributing!

2017-08-11 07:56 UTC, timgrossmann requested changes

2017-08-11 07:56 UTC, timgrossmann commented on README.md
>  session.set_use_clarifai(enabled=True, secret='xyz', proj_id='123')
Please replace this with the `session.set_use_clarifai(enabled=True, api_key='xxx')`

2017-08-11 07:56 UTC, timgrossmann commented on docs/index.md
>  session.set_use_clarifai(enabled=True, secret='xyz', proj_id='123')
Same here 😉

2017-08-11 07:56 UTC, timgrossmann commented on docs/index.md
>  session.set_use_clarifai(enabled=True, secret='xyz', proj_id='123')
Here

2017-08-11 07:56 UTC, timgrossmann commented on examples/example.py
>  session.set_use_clarifai(enabled=True, secret='xyz', proj_id='123')
And here 👍

2017-08-11 22:49 UTC, NedYork commented
Example documentation updated. Thanks!

2017-08-12 13:23 UTC, timgrossmann approved these changes

2017-08-12 22:01 UTC, timgrossmann commented
@NedYork Please have a little more patience.
I'll try to find time to make sure this works tomorrow.

2017-08-26 19:25 UTC, timgrossmann commented
@NedYork Quick question, is this the working API V2  version?

2017-08-27 09:40 UTC, merged