Add method to check if selected user is verified (verified badge) #1
InstaPy/InstaPy pull request #5843
Opened 2020-10-23 16:59 UTC by shifenis

Add a simple method that returns `true` or `false` depending on whether the user is verified or not.

Simple usage:

```python
from instapy import InstaPy

session = InstaPy(username="username",password="psw")
session.isUserVerified(username="username1")
```

2020-10-25 19:31 UTC, elulcao requested changes

2020-10-25 19:31 UTC, elulcao commented on instapy/relationship_tools.py
> +def isUserVerified(browser, username, logger):
nit:
what about "is_user_verified( )"
Adding pydoc for arguments, 
logger.info should offer more information:
ie:
```python
logger.info(
            "Please enter a username to check the verified badge  ~leaving out of an invalid value"
)
```

2020-10-25 19:31 UTC, elulcao commented on instapy/instapy.py
> +    def isUserVerified(self, username: str = None):
Already defined in relationship_tools.py

2020-10-25 19:31 UTC, elulcao commented on DOCUMENTATION.md
> +  - [Is selected user is verified](#is-user-verified)
nit:
Check if selected user has the verified blue badge](#is-user-verified)

2020-10-26 09:31 UTC, shifenis commented on instapy/instapy.py
> +    def isUserVerified(self, username: str = None):
Do you want to expose it just from `relationship_tools.py` instead of passing through `instapy.py`?

2020-10-27 03:18 UTC, elulcao commented on instapy/instapy.py
> +    def isUserVerified(self, username: str = None):
Up to you :)
What I think is that the definition could be made in one place, and be called from other places as many times as necessary. Nested calls from the same definition sounds a bit fancy.

2020-10-27 09:53 UTC, timgrossmann commented
@shifenis Thank you very much for this addition!
Could you please format the changes you did using `black` once 😄 

@elulcao Thank you for doing the review!

2020-10-29 12:40 UTC, timgrossmann commented
@shifenis I think you need to format using py34 instead so the linting step for older python versions also passen 😊 

just do `black -t py34` instead

2020-10-29 17:36 UTC, shifenis commented
@timgrossmann No problem  😄

2020-11-09 04:41 UTC, elulcao reviewed
README.md file has been removed, 
it seems that you need to updated your branch to the latest one.

2025-08-26 10:00 UTC, closed without merging