Fixed error with searching 'Follow' and 'Following' buttons
InstaPy/InstaPy pull request #585
Opened 2017-08-24 15:31 UTC by sterid

I found issue when I'm using like by tag. For example:
`session.like_by_tags(['hashtag'], amount=1)`

The main problem was with "find_element_by_xpath", after my fix it starts work properly.

2017-08-24 18:34 UTC, timgrossmann requested changes

2017-08-24 18:34 UTC, timgrossmann commented on instapy/unfollow_util.py
> -        body_elem = browser.find_element_by_tag_name('body')
Why is this needed?

2017-08-26 08:34 UTC, sterid commented on instapy/unfollow_util.py
> -        body_elem = browser.find_element_by_tag_name('body')
I don't exactly know what this code do. I suggest this is some kind searching 'Follow' button with reward to Home. When  I use this code script always gets error like this: 

> [1/2]
Image from: b'motofame'
Link: b'https://www.instagram.com/p/BYPUSudheIw/?tagged=gopro'
Description: b'Car or bike?
--> Image Liked!
--> Not commented
Traceback (most recent call last):
  File "C:/MyData/Instagram-Bot_Test.py", line 13, in <module>
    session.like_by_tags(['gopro'], amount=2)
  File "C:\MyData\\instapy\instapy.py", line 539, in like_by_tags
    followed += follow_user(self.browser, self.follow_restrict, self.username, user_name)
  File "C:\MyData\\instapy\unfollow_util.py", line 138, in follow_user
    follow_button = flwBtn[0]
IndexError: list index out of range

I can't explain why others don't get the same issue.

2017-08-26 19:22 UTC, timgrossmann approved these changes

2017-08-26 19:23 UTC, timgrossmann commented
@sterid Thank you for the changes, I'll test it and merge it once it's working

Thank you for contributing

2017-08-29 14:57 UTC, blakemmw commented
@timgrossmann this seems to have worked for me(RE: #602 ), a bit of a band-aid fix at least. I have received this error once:
```
Image check error: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//img[@class = "_2di5p"]"}
  (Session info: chrome=60.0.3112.113)
  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 10.0.14393 x86_64)
```
 However, it seems to be working fine other than that one post! Would be interested another users opinion on the matter regardless though.

2017-08-29 19:43 UTC, merged