Check if user's account is private - Supplementary PR
InstaPy/InstaPy pull request #5855
Opened 2020-10-29 21:59 UTC by IreneArapogiorgi

This PR is supplementary to PR #5470. Due to several conflicts between the current master branch and my own branch, which I was not able to resolve, I created a new one having the same code contribution that I've already analyzed in pull request #5470. A detailed description of the contribution and examples of usage are provided in that pull request.

2020-10-30 00:31 UTC, elulcao requested changes
Sharing some ideas,
thanks for considering my request.

2020-10-30 00:31 UTC, elulcao commented on instapy/follow_util.py
> +from .util import web_address_navigator
nit: Using the comment for the imports would be nice, ie: check instapy.py
```
# import built-in & third-party modules
# import InstaPy modules
# import exceptions
```

2020-10-30 00:31 UTC, elulcao commented on instapy/follow_util.py
> +            web_address_navigator(browser, ig_homepage + person_new)
ig_homepage`  is possibly unbound,
ig_homepage = "https://www.instagram.com/" needs to be defined before.

2020-10-30 00:31 UTC, elulcao commented on instapy/follow_util.py
> +        if person_new:
one if-else statement can be removed, it only have to check if `if person_new != person:`
if `person_new` is None the report that `The user with the ID of '{}' is unreachable".format(person))`

ie:
```
if person_new != person:
...
else:
```

2020-10-30 08:30 UTC, IreneArapogiorgi commented on instapy/follow_util.py
> +        if person_new:
@elulcao @timgrossmann Do you think we could address these two changes in a new Issue & PR, as they are not connected directly with the main purpose of this PR? And, in addition to that, so that we can check seperately that they work properly? Right now, in my branch, these two methods are the exact same as in upstream/master's unfollow_util.py file.

2020-10-30 19:03 UTC, elulcao commented on instapy/follow_util.py
> +        if person_new:
sounds good to me, 
happy coding :)

2020-11-04 15:14 UTC, IreneArapogiorgi commented on instapy/follow_util.py
> +        if person_new:
@elulcao Could you explain to me why the statement `if person_new:` should be removed? It seems to me that both of the if-else statements are needed.

2020-11-11 22:22 UTC, elulcao commented on instapy/follow_util.py
> +        if person_new:
Hello @IreneArapogiorgi 
here is what I have in mind, use it like reference and
let me know your thoughts

```python
def verify_username_by_id(browser, username, person, logger, logfolder):
    """Check if the given user has changed username after the time of
    followed"""

    # try to find the user by ID
    # Please remove my comments
    # Checking again for the ID is much better than checking if the arg is None
    person_id = load_user_id(username, person, logger, logfolder)

    # If person_id is None, inform to InstaPy user that record does not exist 
    # and return,
    if person_id not in [None, "unknown", "undefined"]:
        # get the [new] username of the user from the stored user ID
        person_new = get_username_from_id(browser, person_id, logger)

        # Please remove my comments
        # Now we can check if person_new is not the same value as person,
        # if person_new is None then just inform to the InstaPy user that 
        # record does not exist.
        if person_new is not None and person_new != person:
            logger.info(
                "User '{}' has changed username and now is called '{}' :S".format(
                    person, person_new
                    )
            )
            return person_new
        
    # Check who call this def, since will receive a None value.
    logger.info("User '{}' doesn't exist in local records".format(person))
    return None
```

2020-11-15 09:30 UTC, IreneArapogiorgi commented on instapy/follow_util.py
> +        if person_new:
@elulcao I totally agree with your perspective! Just updated the function and I think this PR is ready for merge.

2020-11-15 23:10 UTC, elulcao commented on instapy/follow_util.py
> +        if person_new:
@IreneArapogiorgi 
thanks!

2020-11-15 23:13 UTC, elulcao approved these changes
Thanks @IreneArapogiorgi

2020-11-16 14:57 UTC, timgrossmann approved these changes

2020-11-16 14:58 UTC, timgrossmann commented
@IreneArapogiorgi Looks good, thank you for the PR!

@elulcao Perfect, thanks for checking!

2020-11-18 04:14 UTC, merged

2020-11-20 19:54 UTC, elulcao commented
Hello @IreneArapogiorgi 

The txn was reverted, some issues were reported like #5914
it seems that extra argument `self_username` was causing a 
problem with current value `username` in some methods. 
Most of the problems comes from `unfollow_users` and 
cascade calls to other methods.

If you have a chance to take a look again to the txn it would 
be nice.

2020-11-20 20:48 UTC, IreneArapogiorgi commented
@elulcao Thank you for reaching out to me. I think I know how to fix this. I'll be working on it and will keep you posted.