Subject: fix_5890, fix_5886, fix_5867 Problem: Cookie Handling
InstaPy/InstaPy pull request #5894
Opened 2020-11-13 20:26 UTC by v0lumehi

2020-11-14 01:40 UTC, elulcao requested changes

2020-11-14 01:40 UTC, elulcao commented on instapy/xpath_compile.py
> +    "target_profile": "//section/main/div/ul/div/li/div/div/div[2]/h2/div[1]/a"
Could you check if this XPATH can be reduced, using a willdcard; IG could change the levels in the future.

2020-11-14 01:40 UTC, elulcao commented on instapy/login_util.py
> +            if "sameSite" in cookie:
Cool!, 
nit: would be nice to have some comments about the change. 
I mean, the implication of changing None to Strict.

2020-11-14 01:40 UTC, elulcao commented on instapy/comment_util.py
> +def open_target_profile(browser, logger):
Here is missing the Pydoc information about this def()

2020-11-14 01:40 UTC, elulcao commented on .gitignore
> +local_templates/*
`local_templates ` looks like a personal configuration, then it must be placed in your local gitignore.

2020-11-14 01:51 UTC, elulcao requested changes

2020-11-14 01:51 UTC, elulcao commented on instapy/login_util.py
> +def accept_cookies(browser, logger):
Here is missing Pydoc information about this new def()

2020-11-14 02:16 UTC, elulcao commented
@v0lumehi 
For tracking purposes, Could you share a summary for the changes proposed. 
No description provided at the time this PR was created.

2020-11-14 02:16 UTC, v0lumehi commented on instapy/xpath_compile.py
> +    "target_profile": "//section/main/div/ul/div/li/div/div/div[2]/h2/div[1]/a"
I am not that profound with XPATH unfortunately. Do you know a better solution without checking the XPATH in the browser? Or any docs that could help me here? Would love to learn a bit more about that

2020-11-14 02:18 UTC, v0lumehi commented
> @v0lumehi
> For tracking purposes, Could you share a summary for the changes proposed.
> No description provided at the time this PR was created.

Yes I will do that later. It’s 3AM here already :)

2020-11-14 02:21 UTC, v0lumehi commented on instapy/login_util.py
> +            if "sameSite" in cookie:
Should I put the comments in the code or here?

2020-11-14 02:59 UTC, elulcao commented on instapy/xpath_compile.py
> +    "target_profile": "//section/main/div/ul/div/li/div/div/div[2]/h2/div[1]/a"
You need to generalize the xpath for the target user because there must be several users with same xpath.
//section/main/div/ul/div/li/div/div/div[2]/h2/div[1]/a is only valid because you are defined the levels, but you should try other generic forms to reach the target navigation thru the html, 

my suggest:
`//*[contains(@class, "Igw0E")]/*[contains(@href, '{}')]`
then call it like:
`read_xpath(open_target_profile.__name__, "target_profile").format(the_target_user_name)`


each DOCTYPE is different, so you need to spend some time reading the levels and definitions to determine which could be the best for what you want. Just keep in mind that the goal is to make generic definitions that can be used even though the document changes.

here my two cents for explanation:
ie using this pic `https://www.instagram.com/p/CFGLtnygryj/comments/`
you can target the same with two different xpaths:

before;
`//section/main/div/ul/div/li/div/div/div[2]/h2/div[1]/a`
after:
`//*[contains(@class, "Igw0E")]/*[contains(@href, 'adidas')]`

2020-11-14 03:03 UTC, elulcao commented on instapy/login_util.py
> +            if "sameSite" in cookie:
Both places,
here for further references,
in the Pull Request to notify code reviewers about the changes.

2020-11-15 16:02 UTC, v0lumehi commented on instapy/xpath_compile.py
> +    "target_profile": "//section/main/div/ul/div/li/div/div/div[2]/h2/div[1]/a"
Thanks for your explanation! I will apply your comment.

2020-11-15 16:50 UTC, v0lumehi commented
> @v0lumehi
> For tracking purposes, Could you share a summary for the changes proposed.
> No description provided at the time this PR was created.

Done

2020-11-15 20:11 UTC, v0lumehi commented on instapy/login_util.py
> +            if "sameSite" in cookie:
Done

2020-11-15 20:12 UTC, v0lumehi commented on instapy/comment_util.py
> +def open_target_profile(browser, logger):
Added

2020-11-15 20:12 UTC, v0lumehi commented on .gitignore
> +local_templates/*
Removed

2020-11-15 20:12 UTC, v0lumehi commented on instapy/login_util.py
> +def accept_cookies(browser, logger):
Added

2020-11-15 20:13 UTC, v0lumehi commented
@elulcao sorry for putting so many changes into this pull request! I wanted to bring the bot into a running state and fixed a bunch of stuff. I hope you won't have difficulties reviewing this

2020-11-15 23:46 UTC, elulcao requested changes

2020-11-15 23:46 UTC, elulcao commented on instapy/login_util.py
> +    accept_cookies(browser, logger)
This def() needs to be removed, it displays always a warning message, 
I guess the check can be done just after Logged In, but it depends whether IG displays this new option.

This is displayed when cookie is not OK
```bash
INFO [2020-11-15 17:04:44] [internet]  - Hide Selenium Extension: ok
WARNING [2020-11-15 17:04:52] [internet]  --> Accept Cookies Button Not Found!     ~may cause issues with browser windows of smaller widths
WARNING [2020-11-15 17:04:54] [internet]  Issue with cookie for user 'internet'. Creating new cookie...
INFO [2020-11-15 17:04:54] [internet]  Deleting browser cookies...
INFO [2020-11-15 17:05:09] [internet]  Do not save Login Info by now
```

This is displayed when cookie does not exist
```bash
INFO [2020-11-15 17:06:44] [internet]  - Hide Selenium Extension: ok
WARNING [2020-11-15 17:06:52] [internet]  --> Accept Cookies Button Not Found!     ~may cause issues with browser windows of smaller widths
WARNING [2020-11-15 17:06:52] [internet]  Cookie file not found, creating cookie...
INFO [2020-11-15 17:07:09] [internet]  Do not save Login Info by now
```

This is displayed when cookie exist
```bash
INFO [2020-11-15 17:08:18] [internet]  - Hide Selenium Extension: ok
WARNING [2020-11-15 17:08:26] [internet]  --> Accept Cookies Button Not Found!     ~may cause issues with browser windows of smaller widths
...................................................................
```

2020-11-15 23:46 UTC, elulcao commented on instapy/file_manager.py
> -            message = "No any custom workspace provided.\t~using existing.."
Do not change the messages, they are not related to this PR. 
If the text needs to be changed, use another PR only for messages.

2020-11-15 23:46 UTC, elulcao commented on instapy/login_util.py
> +    # accept_cookies(browser, logger)
nit: 
remove if not needed

2020-11-15 23:46 UTC, elulcao commented on instapy/plugins/telegram_util.py
> -                "|> No any statistics to show\n"
Do not change current messages.

2020-11-16 00:17 UTC, v0lumehi commented on instapy/login_util.py
> +    accept_cookies(browser, logger)
I will investigate further into this. I think the function is needed, because there is a accept cookie dialogue showing up. I just need to figure where to set it properly and how to handle all of the existing conditions.

2020-11-16 00:24 UTC, v0lumehi commented on instapy/file_manager.py
> -            message = "No any custom workspace provided.\t~using existing.."
Reverted

2020-11-16 00:24 UTC, v0lumehi commented on instapy/plugins/telegram_util.py
> -                "|> No any statistics to show\n"
Reverted

2020-11-16 01:25 UTC, v0lumehi commented on instapy/login_util.py
> +    accept_cookies(browser, logger)
How did you test this? For me it shows:
Existing cookie:
```
Workspace in use: "/Users/internet/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-11-16 01:47:39] [internet]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-11-16 01:47:39] [internet]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-11-16 01:47:39] [internet]  - Internet Connection Status: ok
INFO [2020-11-16 01:47:39] [internet]  - Current IP is "127.0.0.1" and it's from "My Home"
INFO [2020-11-16 01:47:39] [internet]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-11-16 01:47:39] [internet]  - window.navigator.webdriver response: None
INFO [2020-11-16 01:47:39] [internet]  - Hide Selenium Extension: ok
...................................................................
INFO [2020-11-16 01:47:56] [internet]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
```
When cookie is not OK:
```
InstaPy Version: 0.6.12
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/Users/zaljic/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-11-16 01:50:09] [zialonthebeat]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-11-16 01:50:09] [zialonthebeat]  -- Connection Checklist [1/2] (Internet Connection Status)
/usr/local/lib/python3.8/site-packages/selenium-4.0.0a7-py3.8.egg/selenium/webdriver/remote/webdriver.py:611: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")
INFO [2020-11-16 01:50:10] [zialonthebeat]  - Internet Connection Status: ok
INFO [2020-11-16 01:50:10] [zialonthebeat]  - Current IP is "88.72.223.187" and it's from "Germany/DE"
INFO [2020-11-16 01:50:10] [zialonthebeat]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-11-16 01:50:10] [zialonthebeat]  - window.navigator.webdriver response: None
INFO [2020-11-16 01:50:10] [zialonthebeat]  - Hide Selenium Extension: ok
/usr/local/lib/python3.8/site-packages/selenium-4.0.0a7-py3.8.egg/selenium/webdriver/remote/webdriver.py:470: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")
WARNING [2020-11-16 01:50:16] [zialonthebeat]  Issue with cookie for user 'zialonthebeat'. Creating new cookie...
INFO [2020-11-16 01:50:16] [zialonthebeat]  Deleting browser cookies...
/usr/local/lib/python3.8/site-packages/selenium-4.0.0a7-py3.8.egg/selenium/webdriver/remote/webdriver.py:451: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")
INFO [2020-11-16 01:50:55] [zialonthebeat]  Timed out with failure while explicitly waiting until visibility of element located!

**********************************************************************
If raising an issue, please also upload the file located at:
/var/folders/9y/plw6vzpx3r16tb82t7yql36r0000gp/T/20201116-015100.html
**********************************************************************

INFO [2020-11-16 01:51:01] [zialonthebeat]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 55.58 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-11-16 01:51:01] [zialonthebeat]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "template_typebeats.py", line 11, in <module>
    with smart_run(session):
  File "/usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 115, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield
```
This exception occurs because after deleting the browser's cookies, the accept cookies dialogue appears again. This can be fixed by adding the accept_cookies() function call like this:
```
    if cookie_loaded is False:
        logger.warn(
            "Issue with cookie for user '{}'. Creating new cookie...".format(username)
        )

        # Error could be faced due to "<button class="sqdOP L3NKy y3zKF"
        # type="button"> Cookie could not be loaded" or similar.
        # Session displayed we are in, but then a failure for the first
        # `login_elem` like the element is no longer attached to the DOM.
        # Saw this issue when session hasn't been used for a while; wich means
        # "expiry" values in cookie are outdated.
        try:
            # Since having issues with the cookie a new one can be generated,
            # if cookie cannot be created or deleted stop execution.
            logger.info("Deleting browser cookies...")
            browser.delete_all_cookies()
        except Exception as e:
            # NF: start
            if isinstance(e, WebDriverException):
                logger.exception(
                    "Error occurred while deleting cookies from web browser!\n\t{}".format(
                        str(e).encode("utf-8")
                    )
                )
            return False
            # NF: end

        web_address_navigator(browser, ig_homepage)
        accept_cookies(browser, logger)
```
But then this error appears, when cookie is not ok:
```
InstaPy Version: 0.6.12
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/Users/internet/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-11-16 02:21:58] [internet]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-11-16 02:21:58] [internet]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-11-16 02:21:59] [internet]  - Internet Connection Status: ok
INFO [2020-11-16 02:21:59] [internet]  - Current IP is "127.0.0.1" and it's from "My Home"
INFO [2020-11-16 02:21:59] [internet]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-11-16 02:21:59] [internet]  - window.navigator.webdriver response: None
INFO [2020-11-16 02:21:59] [internet]  - Hide Selenium Extension: ok
WARNING [2020-11-16 02:22:05] [internet]  Issue with cookie for user 'internet'. Creating new cookie...
INFO [2020-11-16 02:22:05] [internet]  Deleting browser cookies...
WARNING [2020-11-16 02:22:11] [internet]  Login A/B test detected! Trying another string...
WARNING [2020-11-16 02:22:16] [internet]  Could not pass the login A/B test. Trying last string...
ERROR [2020-11-16 02:22:21] [internet]  Login A/B test failed!
	b"Message: Unable to locate element: //div[text()='Log In']\nStacktrace:\nWebDriverError@chrome://marionette/content/error.js:181:5\nNoSuchElementError@chrome://marionette/content/error.js:393:5\nelement.find/</<@chrome://marionette/content/element.js:332:16\n"
Traceback (most recent call last):
  File "/Users/internet/playground/InstaPy/instapy/login_util.py", line 330, in login_user
    login_elem = browser.find_element_by_xpath(
  File "/usr/local/lib/python3.8/site-packages/selenium-4.0.0a7-py3.8.egg/selenium/webdriver/remote/webdriver.py", line 452, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.8/site-packages/selenium-4.0.0a7-py3.8.egg/selenium/webdriver/remote/webdriver.py", line 1138, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.8/site-packages/selenium-4.0.0a7-py3.8.egg/selenium/webdriver/remote/webdriver.py", line 368, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium-4.0.0a7-py3.8.egg/selenium/webdriver/remote/errorhandler.py", line 240, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: U [...]

2020-11-16 01:27 UTC, v0lumehi commented on instapy/login_util.py
> +    accept_cookies(browser, logger)
So yeah, you were right about the login not working properly, but the accept_cookies() function is definitely needed. I am just wondering how you were testing because I could not reproduce your error

2020-11-16 01:40 UTC, v0lumehi commented on instapy/login_util.py
> +    accept_cookies(browser, logger)
It might be a dependency problem. It seems like the cookie dialogue is showing up for me (and a bunch of other people as seen in the latest issue reports), while for you it isn‘t. Do you think that different versions of Firefox could cause this behavior?

2020-11-18 04:38 UTC, elulcao commented
@v0lumehi 
is this the new page your PR is handling?
Form where I'm running InstaPy that page is not displayed :s


![unknown](https://user-images.githubusercontent.com/6373960/99484241-924d4b80-2925-11eb-92c2-bb0817b436d0.png)

2020-11-18 05:18 UTC, elulcao commented on instapy/login_util.py
> +    accept_cookies(browser, logger)
@v0lumehi
Seems to be a issue that affects InstaPy users by zones, 
From where I'm using InstaPy there is nothing new, I cannot 
join the new page for the `Cookies`. 

I'm just using the InstaPy 0.6.12 without changes
nor modifications. Actually I tried the docker version to verify InstaPy
with a different OS instead of macOS. running in Ubuntu is the same result to me.

The pic I shared in the comment bellow has been extracted from Discord, 
the guy that posted the pic is from Europe. That could be the main topic here, 
IG is spreading different pages in different areas; similar to the A/B test.

Your code is OK, so you just need to handle the case I described before.
Maybe you can try to avoid the message `Accept Cookies Button Not Found!...`
becase some users (like my case) still do not see that new page. These 3 methods
are doing that `dismiss_get_app_offer` `dismiss_notification_offer` `dismiss_save_information`.

On the other hand, it would be great if you change the name method to something similar: `dismiss...` since your logic is quiete similar. In this case IG forces the IG users to save cookies because the personalized content.

`dismiss_get_app_offer` 
`dismiss_notification_offer` 
`dismiss_save_information`
`dismiss_accept_cookies` <== Here

let me know your thoughts 

My firefox is 82.0.3 (64-bit) btw,

2020-11-18 08:15 UTC, v0lumehi commented on instapy/login_util.py
> +    accept_cookies(browser, logger)
I am from EU as well. So this is pretty likely the issue! I will try to implemented your requested changes

2020-11-18 16:19 UTC, elulcao commented on instapy/login_util.py
> +    accept_cookies(browser, logger)
Thanks so much. 
Appreciate your help 
👍

2020-11-18 22:08 UTC, v0lumehi commented on instapy/login_util.py
> +    accept_cookies(browser, logger)
I was able to fix it the error I reported on my end and implemented a check that checks whether the user is from EU or not from geoip data.
Can you test it on your end as well? It works for me now.

2020-11-18 22:10 UTC, v0lumehi commented on instapy/login_util.py
> +    accept_cookies(browser, logger)
I changed the name from "accept_cookies" to "accept_cookie_dialogue" as we aren't dismissing the dialogue. In fact, we only got one option there, which is "Accept", as seen in the picture you attached

2020-11-19 00:43 UTC, elulcao commented on instapy/login_util.py
> +    accept_cookies(browser, logger)
Thanks mate,

2020-11-19 01:29 UTC, v0lumehi commented on instapy/login_util.py
> +    accept_cookies(browser, logger)
No worries! Did you test my changes yet?

2020-11-20 01:51 UTC, elulcao commented on instapy/login_util.py
> +    accept_cookies(browser, logger)
> No worries! Did you test my changes yet?

I tried once, but I need to check your
branch again.
there is another issue with last PR, 
let me revert the changes and then 
refresh your branch. This is because other 
parts of the bot were affected.

2020-11-20 05:04 UTC, elulcao commented
Hello @v0lumehi 
Could you update your branch with latest changes from main,
Thanks

2020-11-22 19:21 UTC, elulcao commented
Hello @v0lumehi 

I used the txn in my local, and `Log in` session ran smoothly; it ran around ~6h.

```bash
2564  INFO [2020-11-21 17:48:13] [internet]  Session started!
    1 INFO [2020-11-21 17:48:13] [internet]  -- Connection Checklist [1/2] (Internet Connection Status)
    2 INFO [2020-11-21 17:48:14] [internet]  - Internet Connection Status: ok
    3 INFO [2020-11-21 17:48:14] [internet]  - Current IP is "0.0.0.0" and it's from "AC/DC"
    4 INFO [2020-11-21 17:48:14] [internet]  -- Connection Checklist [2/2] (Hide Selenium Extension)
    5 INFO [2020-11-21 17:48:14] [internet]  - window.navigator.webdriver response: None
    6 INFO [2020-11-21 17:48:14] [internet]  - Hide Selenium Extension: ok
    7 INFO [2020-11-21 17:48:30] [internet]  Logged in successfully!
    8 INFO [2020-11-21 17:48:30] [internet]  Saving account progress...
    9 INFO [2020-11-21 17:48:44] [internet]  Getting active users who liked the latest 5 posts:
   10   ~collecting the usernames from posts with the boundary of 500

...

10268 INFO [2020-11-21 23:39:31] [internet]  Sessional Live Report:
    1         |> LIKED 200 images  |  ALREADY LIKED: 10
    2         |> COMMENTED on 3 images
    3         |> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
    4         |> UNFOLLOWED 5 users
    5         |> LIKED 0 comments
    6         |> REPLIED to 0 comments
    7         |> INAPPROPRIATE images: 395
    8         |> NOT VALID users: 128
    9         |> WATCHED 0 story(ies)  |  WATCHED 0 reel(s)
   10
   11 On session start was FOLLOWING 153 users & had 3892 FOLLOWERS
   12 [Session lasted 5.85 hours]
   13 INFO [2020-11-21 23:39:31] [internet]  Session ended!
```

2020-11-22 20:10 UTC, v0lumehi commented
> Hello @v0lumehi
> 
> I used the txn in my local, and `Log in` session ran smoothly; it ran around ~6h.
> 
> ```shell
> 2564  INFO [2020-11-21 17:48:13] [internet]  Session started!
>     1 INFO [2020-11-21 17:48:13] [internet]  -- Connection Checklist [1/2] (Internet Connection Status)
>     2 INFO [2020-11-21 17:48:14] [internet]  - Internet Connection Status: ok
>     3 INFO [2020-11-21 17:48:14] [internet]  - Current IP is "0.0.0.0" and it's from "AC/DC"
>     4 INFO [2020-11-21 17:48:14] [internet]  -- Connection Checklist [2/2] (Hide Selenium Extension)
>     5 INFO [2020-11-21 17:48:14] [internet]  - window.navigator.webdriver response: None
>     6 INFO [2020-11-21 17:48:14] [internet]  - Hide Selenium Extension: ok
>     7 INFO [2020-11-21 17:48:30] [internet]  Logged in successfully!
>     8 INFO [2020-11-21 17:48:30] [internet]  Saving account progress...
>     9 INFO [2020-11-21 17:48:44] [internet]  Getting active users who liked the latest 5 posts:
>    10   ~collecting the usernames from posts with the boundary of 500
> 
> ...
> 
> 10268 INFO [2020-11-21 23:39:31] [internet]  Sessional Live Report:
>     1         |> LIKED 200 images  |  ALREADY LIKED: 10
>     2         |> COMMENTED on 3 images
>     3         |> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
>     4         |> UNFOLLOWED 5 users
>     5         |> LIKED 0 comments
>     6         |> REPLIED to 0 comments
>     7         |> INAPPROPRIATE images: 395
>     8         |> NOT VALID users: 128
>     9         |> WATCHED 0 story(ies)  |  WATCHED 0 reel(s)
>    10
>    11 On session start was FOLLOWING 153 users & had 3892 FOLLOWERS
>    12 [Session lasted 5.85 hours]
>    13 INFO [2020-11-21 23:39:31] [internet]  Session ended!
> ```
Great news! I will merge master today

2020-11-22 20:12 UTC, v0lumehi commented
@elulcao I just merged master. We are good to go now, right?

2020-11-23 01:12 UTC, elulcao requested changes

2020-11-23 01:12 UTC, elulcao commented on instapy/comment_util.py
> +            username,
same here, the extra arg is not needed; 
remove the extra arg in `comment_image()`.

```python
85  def comment_image(
  1     browser, username, target_username, comments, blacklist, logger, logfolder
  2 ):
```

but `instapy.py` call this def() in different places with 6 args,

```python
5527                                 reply_to_comment_state, msg = comment_image(
   1                                     self.browser,
   2                                     commenter,
   3                                     reply_msg,
   4                                     self.blacklist,
   5                                     self.logger,
   6                                     self.logfolder,
   7                                 )
...
5880                         comment_state, msg = comment_image(
   1                             self.browser,
   2                             target_username,
   3                             comments,
   4                             self.blacklist,
   5                             self.logger,
   6                             self.logfolder,
   7                         )
5527                                 reply_to_comment_state, msg = comment_image(
   1                                     self.browser,
   2                                     commenter,
   3                                     reply_msg,
   4                                     self.blacklist,
   5                                     self.logger,
   6                                     self.logfolder,
   7                                 )
```

2020-11-23 01:12 UTC, elulcao commented on instapy/comment_util.py
> -    user_name,
Here this one receives now 13 args,

```python
439 def process_comments(
  1     comments,
  2     clarifai_comments,
  3     delimit_commenting,
  4     max_comments,
  5     min_comments,
  6     comments_mandatory_words,
  7     username, <== Here
  8     target_username, <== Here
  9     blacklist,
 10     browser,
 11     logger,
 12     logfolder,
 13     publish=True,
 14 ):
```
but `instapy.py` call this def() in different places with 12 args,
this is not correct, please check why `def process_comments()`
has the extra arg; this new value is not needed.

```python
1579                                 success = process_comments(
   1                                     comments,
   2                                     temp_comments,
   3                                     self.delimit_commenting,
   4                                     self.max_comments,
   5                                     self.min_comments,
   6                                     self.comments_mandatory_words,
   7                                     self.username,
   8                                     self.target_username,
   9                                     self.blacklist,
  10                                     self.browser,
  11                                     self.logger,
  12                                     self.logfolder,
  13                                 )
...
1790                                 success = process_comments(
   1                                     comments,
   2                                     temp_comments,
   3                                     self.delimit_commenting,
   4                                     self.max_comments,
   5                                     self.min_comments,
   6                                     self.comments_mandatory_words,
   7                                     self.username,
   8                                     self.target_username,
   9                                     self.blacklist,
  10                                     self.browser,
  11                                     self.logger,
  12                                     self.logfolder,
  13                                 )
...
2033                                 success = process_comments(
   1                                     comments,
   2                                     temp_comments,
   3                                     self.delimit_commenting,
   4                                     self.max_comments,
   5                                     self.min_comments,
   6                                     self.comments_mandatory_words,
   7                                     self.username,
   8                                     self.target_username,
   9                                     self.blacklist,
  10                                     self.browser,
  11                                     self.logger,
  12                                     self.logfolder,
  13                                 )
...
etc...
```

2020-11-23 01:12 UTC, elulcao commented on instapy/instapy.py
> +                                    self.target_username,
Same as before,
remove the extra arg in `comment_util.py()`, it has now 13,

```python
439 def process_comments(
  1     comments,
  2     clarifai_comments,
  3     delimit_commenting,
  4     max_comments,
  5     min_comments,
  6     comments_mandatory_words,
  7     username, <== Here
  8     target_username, <== Here
  9     blacklist,
 10     browser,
 11     logger,
 12     logfolder,
 13     publish=True,
 14 ):
```
`instapy.py()` is calling it with 12 args

```python
1579                                 success = process_comments(
   1                                     comments,
   2                                     temp_comments,
   3                                     self.delimit_commenting,
   4                                     self.max_comments,
   5                                     self.min_comments,
   6                                     self.comments_mandatory_words,
   7                                     self.username,
   8                                     self.target_username,
   9                                     self.blacklist,
  10                                     self.browser,
  11                                     self.logger,
  12                                     self.logfolder,
  13                                 )
...
1790                                 success = process_comments(
   1                                     comments,
   2                                     temp_comments,
   3                                     self.delimit_commenting,
   4                                     self.max_comments,
   5                                     self.min_comments,
   6                                     self.comments_mandatory_words,
   7                                     self.username,
   8                                     self.target_username,
   9                                     self.blacklist,
  10                                     self.browser,
  11                                     self.logger,
  12                                     self.logfolder,
  13                                 )
...
2033                                 success = process_comments(
   1                                     comments,
   2                                     temp_comments,
   3                                     self.delimit_commenting,
   4                                     self.max_comments,
   5                                     self.min_comments,
   6                                     self.comments_mandatory_words,
   7                                     self.username,
   8                                     self.target_username,
   9                                     self.blacklist,
  10                                     self.browser,
  11                                     self.logger,
  12                                     self.logfolder,
  13                                 )
...
2333                                 success = process_comments(
   1                                     comments,
   2                                     temp_comments,
   3                                     self.delimit_commenting,
   4                                     self.max_comments,
   5                                     self.min_comments,
   6                                     self.comments_mandatory_words,
   7                                     self.username,
   8                                     self.target_username,
   9                                     self.blacklist,
  10                                     self.browser,
  11                                     self.logger,
  12                                     self.logfolder,
  13                                 )
etc...
```

2020-11-23 01:12 UTC, elulcao commented on instapy/instapy.py
> +                                self.target_username = target_username
I think this is not necessary, since there are extra args not needed. 
check previous comments.

2020-12-22 09:16 UTC, chrisjansky commented
What is the status of this please? I am still getting the cookie error present in the latest master version.

2020-12-31 13:40 UTC, garrywilliams commented
> What is the status of this please? I am still getting the cookie error present in the latest master version.

It doesn't look as though it has been merged into master yet

2021-01-14 12:07 UTC, greyslater commented
Can confirm: with 0.6.13 it's still an issue
I'm running instapy headless inside a docker container and therefore heavily depend on this feature.
I would be very thankful when this is merged into master

2021-01-14 23:03 UTC, trevtravtrev commented
Can this please be merged? This is a code breaking issue...

2021-01-14 23:06 UTC, elulcao commented
Code needs to be updated to match with latest commit. After that everything will run smoothly

2021-01-15 07:47 UTC, webben-de commented
The merge would be great!

2021-01-15 09:51 UTC, greyslater commented
A little update and workaround from my side:

As I didn't wanted to wait for the merge, didn't wanted to change code on my side temporarily and most important continue to run everything within a docker container from the original Instapy Image I found an interim solution that works for me.

Normally my containers run on a headless server but to accept the cookie I just ran it with GUI only once.
The big disadvantage: this was done on a completely different server instance (an interim solution as I said)

There is one thing I mentioned: after the cookie accept page I got another page to "remember the browser for login" or something like this. I think you know what I mean.
Could it be that this is another barrier for the headless login process??

2021-01-15 16:03 UTC, trevtravtrev commented
@greyslater instapy can successfully solve the "remember this login" about 50% of the time. There is a bug (I don't have the trace back) where it will still fail on that about half the time. Manually accepting the cookies once as you did will only temporarily work. I've done the same but the next time I use my program it pops up again.

Unfortunately I've been having to use my own fork of instapy for a long time because code breaking bugs are left in master code for long periods of time with no urgency to merge fixes.

2021-01-15 16:05 UTC, elulcao commented
> @greyslater instapy can successfully solve the "remember this login" about 50% of the time. There is a bug (I don't have the trace back) where it will still fail on that about half the time. Manually accepting the cookies once as you did will only temporarily work. I've done the same but the next time I use my program it pops up again.
> 
> Unfortunately I've been having to use my own fork of instapy for a long time because code breaking bugs are left in master code for long periods of time with no urgency to merge fixes.

@trevtravtrev 
if you can create a PR for merging your changes that would be nice, 
many Users will be happy with that. 
Thanks in advance

2021-01-15 16:08 UTC, trevtravtrev commented
@elulcao unfortunately I have limited time for upkeep and a lot of my forked fixes are implemented as hot fixes. I don't have time for proper PR's that update documentation and all other merge requirements.

2021-01-15 16:09 UTC, elulcao commented
> @elulcao unfortunately I have limited time for upkeep and a lot of my forked fixes are implemented as hot fixes. I don't have time for proper PR's that update documentation and all other merge requirements.

Ohhh, 
well, thanks for the confirmation

2021-01-16 16:54 UTC, greyslater commented
@trevtravtrev 

> Manually accepting the cookies once as you did will only temporarily work. I've done the same but the next time I use my program it pops up again.

You have to keep the _cookie.pkl file between your sessions then you can continue to run it headless

2021-01-16 18:29 UTC, trevtravtrev commented
@greyslater i do and the bug still occurs.

2021-01-22 10:24 UTC, v0lumehi commented
Hi guys! Just a quick update from me. I have been really busy lately. I am working on a new project and didn’t find any time to complete this yet. If someone else has the time to progress things here, please feel free to do it and to contact me on Discord. My nickname on the server is the same as here.

2021-01-22 16:43 UTC, greyslater commented
> @greyslater i do and the bug still occurs.

interestingly
I'm using 2 separate "bots"
one only with `bot.like_by_tags`
the other one only with `bot.unfollow_users`

my "like & follow" bot deletes the cookie every time
my "unfollow" bot keeps the cookie

why? I don't know

2021-01-24 13:15 UTC, greyslater commented
oh guys - if InstaPy would be the only thing with troubles right now
there's the other tool `instagram-profilecrawl` that concerns me since almost 2 weeks (not everyday for luck)

it "crashes" already when `chromedriver` tries to start `google-chrome` as far as I found out
but if someone could fix this, probably we'll get stuck at the same cookie issue like here 😥

https://github.com/timgrossmann/instagram-profilecrawl/issues/184

2021-01-26 21:41 UTC, Ericrobert22 commented
> oh guys - if InstaPy would be the only thing with troubles right now
> there's the other tool `instagram-profilecrawl` that concerns me since almost 2 weeks (not everyday for luck)
> 
> it "crashes" already when `chromedriver` tries to start `google-chrome` as far as I found out
> but if someone could fix this, probably we'll get stuck at the same cookie issue like here 😥
> 
> https://github.com/timgrossmann/instagram-profilecrawl/issues/184

I had similar issues too on till i mete acehack1 on Instagram and he helped me fixed it successfully try him he can be of help

2021-01-27 01:40 UTC, elulcao commented
> oh guys - if InstaPy would be the only thing with troubles right now
> 
> there's the other tool `instagram-profilecrawl` that concerns me since almost 2 weeks (not everyday for luck)
> 
> 
> 
> it "crashes" already when `chromedriver` tries to start `google-chrome` as far as I found out
> 
> but if someone could fix this, probably we'll get stuck at the same cookie issue like here 😥
> 
> 
> 
> https://github.com/timgrossmann/instagram-profilecrawl/issues/184

Ff is the only one to be used by instapy 
Chrome has been unsupported time ago

2021-01-27 08:33 UTC, greyslater commented
> Ff is the only one to be used by instapy
> Chrome has been unsupported time ago

But now we're also stuck with Firefox because of damn stupid cookies 🍪

2021-01-27 08:34 UTC, greyslater commented
> I had similar issues too on till i mete acehack1 on Instagram and he helped me fixed it successfully try him he can be of help

thx, I gave him a call on Insta - let's see what happens

2021-02-03 08:29 UTC, greyslater commented
days go by
weeks go by
we're stuck

2021-02-03 12:14 UTC, elulcao commented
> days go by
> 
> weeks go by
> 
> we're stuck

There is always a solution, and In this case the solution is running the bot in graphic mode. Once the new page is displayed click the ACCEPT button.

2021-02-03 18:17 UTC, greyslater commented
> There is always a solution, and In this case the solution is running the bot in graphic mode. Once the new page is displayed click the ACCEPT button.

and this you call a BOT - shame on you 😅

2021-02-03 18:55 UTC, elulcao commented
> > There is always a solution, and In this case the solution is running the bot in graphic mode. Once the new page is displayed click the ACCEPT button.
> 
> 
> 
> and this you call a BOT - shame on you 😅

Thanks for the feedback. 👌

2021-07-06 06:23 UTC, piof93 commented
Hello, is there any update on that issue? I am still getting the Cookies Pop-up. I have tried modifying the code in login_util as suggested in #5834 but with no luck...
Did anyone manage to make it work?

2021-09-25 18:33 UTC, hasr7 commented
Come On Instapy team!!!!
go and fix this please!!
it had been 3 years!!!!

2021-09-28 14:11 UTC, breuerfelix commented
isnt this fixed by the merge of @elulcao s pull request ?

2021-10-02 18:47 UTC, DennyWeinberg commented
PR doesnt help on Mac OS M1!
`WARNING [2021-10-02 20:44:56] [denny.weinberg]  --> Accept Cookies Button Not Found!       ~dialogue doesn't appear always, so not an issue`

2021-10-02 20:16 UTC, elulcao commented
This PR wasn't completed, I suspect is not complete.

2024-12-20 17:16 UTC, closed without merging