Lloggin session detailed and minor fixes
InstaPy/InstaPy pull request #5954
Opened 2020-12-11 20:05 UTC by elulcao

Hello all,

I created this PR to solve some issues with login session and other minor fixes regarding outdated xpaths,
I've been using this branch past week and everything goes well.
Thanks for considering my request, 
have a nice day.

`instapy/browser.py`: moved user_agent to general settings, now all code
uses the same agent definition

`instapy/commenters_util.py`: Added logger to `get_users_from_dialog()` to
trace actions

`instapy/instapy.py`: Added the Exception to the STDOUT when a failure

`instapy/login_util.py`: `login_user()` reordered to avoid stale elements or
timeouts due to the latest IG changes, id `SameSite` cookie. In a failure
with the cookie a new one will be created to avoid user interaction at
OS level.
In some regions a new question for saving cookies in the machine is
displayed, so it was added `accept_igcookie_dialogue` to accept the new
requirement. This check will be transparent If the page is not released in a
specific zone.

`instapy/relationship_tools.py`: Added extra prints for pretty look traces

`instapy/settings.py`: defined `user_agent` for all settings

`instapy/story_util.py`: ordered imports

`instapy/util.py: Fixed format strings when some double quotes were left.
Added a try-exept to `get_users_from_dialog` to catch stale elements

instapy/xpath_compile.py: Updated xpath for `class_selectors` and typo
in `dismiss_save_information`. Added `accept_igcookie_dialogue` for
changes in `login_util.py`

Note:

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Do not include any personal data.

Fixes # (issue)
#5834 #5886 #5890 #5909 #5912 #5931 #5944 #5837 

## How Has This Been Tested?

Verified with a real IG acct, no errors reported during execution in macOS (p3.8) and ubuntu (p3.7)

- [x] Test

## Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have checked my code and corrected any misspellings
- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project, `black -t py34`
- [x] My changes generate no new warnings

2020-12-12 15:47 UTC, breuerfelix requested changes

2020-12-12 15:47 UTC, breuerfelix commented on instapy/login_util.py
> +                open(cookie_file, "wb"),
you should close the file handler again :) or use it with the `with` statement :)

2020-12-12 15:49 UTC, breuerfelix commented
you are a hero mate! probably already told you that but thanks for putting that much time into the project! i am 100% sure that i will speak for the whole community here :)

i also fixed some bugs again in instapy gui since you are fixing bugs over here, the gui is useable again!

2020-12-13 11:05 UTC, timgrossmann approved these changes
Incredible! Thanks for the updates and fixes.
As @breuerfelix already mentioned, this is huge. Especially fixing the bugs people face.

Love it!

2020-12-13 17:46 UTC, elulcao commented on instapy/login_util.py
> +                open(cookie_file, "wb"),
Fixed, using `with` to auto close the handler.
Squashing commits and closing the PR.
Thanks! 

```python
        try:
            # Open the cookie file to store the data
            with open(cookie_file, "wb") as cookie_f_handler:
                pickle.dump(cookies_list, cookie_f_handler)

        except pickle.PicklingError:
            # Next time, cookie will be created for the session so we are safe
            logger.warn("- Browser cookie list could not be saved to your local...")
```

2020-12-13 18:51 UTC, breuerfelix approved these changes

2020-12-13 20:19 UTC, merged

2020-12-16 09:20 UTC, Sebadier commented
For me the issue is still persistent, even with the latest commits.
INFO [2020-12-16 10:14:41] []  - Cookie file not found, creating cookie...
INFO [2020-12-16 10:15:20] []

  Timed out with failure while explicitly waiting until visibility of element located!
[20201216-101525.html.zip](https://github.com/timgrossmann/InstaPy/files/5701584/20201216-101525.html.zip)

2020-12-16 13:20 UTC, elulcao commented
@Sebadier 
That new windows is not released in the zone I'm living,
so I cannot reproduce the issue in my local, maybe the 
latest PR I sent contains a non updated xpath for that new
page. 
Hope other people send a new PR with more accurate 
information for that new window. 
thanks.

2021-05-23 22:14 UTC, tomnewg commented
@elulcao 
Thanks for all your work on this! 
#5890 started to appear for me 4 days ago. I have never gotten this error message in the months before and I haven't changed any configuration. Any idea why this is appearing again?

Many thanks for your help