Introduced option to ignore pictures from certain users and include owner comments when checking for tags
InstaPy/InstaPy pull request #60
Opened 2017-04-09 19:26 UTC by pekapa

Usage:
    .set_ignore_users([usernames])

Also changed the behaviour when checking for ignores based on keywords, now it includes all the comments made by the owner (sometimes the owner place tags in their first comment, not necessarily the first comment of the picture)

Finally, added some verbosity to track why an image has been flagged as inappropriate (which tag was responsible or the user name if it’s blacklisted).

2017-04-09 21:10 UTC, timgrossmann commented
@pekapa Really like the *include owner comments when checking for tags* part of this, also the ignore users is useful, but I don't really get the difference between this and the already implemented 
```python
set_dont_include([friend1, friend2 ...])
```

Please also add the "documentation" to the Readme and the examples/example.py, so people can see the feature

2017-04-09 21:23 UTC, pekapa commented
Done.
The difference from `set_dont_include` is that it only avoids commenting and unfollowing while my version ignores it completely.
In my case, I'm always checking for a tag that I know a few people use it and I don't want to like the pictures form those.

2017-04-09 22:55 UTC, vlntdds commented
Just got a strange usage of ram/cpu and sometimes chrome just hang while fetching "media.comments.nodes" with photos with a lot of comments.

OSx 10.12, 28gb ram, latest Chrome Stable (also tried with Chromium)

2017-04-09 23:05 UTC, pekapa commented
@vlntdds I'll have a look on that,
My first try was to actually filter it via js before sending it to the browser but I kept getting an unexpected error.

Do you have any link with tons of comments? How many are we talking about? 1k, 100k?
I'm working on OSx 10.12 with 16gb of ram and didn't ran into that kind of problem.

2017-04-09 23:54 UTC, vlntdds commented
Just tested on two droplets w/ 2gb (centos + ubuntu)
The same crash occurs, always if the logged account have `window._sharedData.qe.ebd.p.use_new_styles = true`. 

With accounts that don't have this attribute, the crash didn't happen.
Happened on different posts, with less comments (i.e: 2 or 50)

2017-04-10 00:56 UTC, pekapa commented
The comment filtering and mapping is running via js now reducing a lot the amount of data that needs to be sent back to python.
I was unable to reproduce so, if you could please check if it works now, I would appreciate.
If it's not working, could you show me the traceback?

2017-04-10 01:17 UTC, vlntdds commented
```
Uncaught TypeError: Cannot read property 'filter' of undefined
    at <anonymous>:2:8
```
The `owner_comments `value is always `"\nundefined"`

Only occurs in the account that have the `use_new_styles` flag

2017-04-10 01:46 UTC, pekapa commented
New fix...
My account has the `use_new_styles` flag and I can't reproduce, must be something else.
Anyway, I treated the possibility of `comments.nodes` being `undefined`.
Let me know if the error persists (or if there's a new one)

2017-04-10 03:17 UTC, vlntdds commented
Always return an empty string now, doesn't filter/get the creator's comments/replies.

2017-04-10 11:50 UTC, pekapa commented
Just introduced some console.logs to check
Could you please tell me if `latest_comments` is of type object in those checks?

I really can't reproduce this, is it related to the logged in user account or to the post?
If it's related to the post, can you send me the post link?
If it's related to the user, how can I create a user with / without that flag?
Do the problem persist on your OSx? Should I try to get a droplet to test it there as well?

2017-04-10 15:15 UTC, timgrossmann commented
@vlntdds Any updates on the errors?

2017-04-10 20:17 UTC, vlntdds commented
@timgrossmann will check asap.

@pekapa nice, will send you the output in a few hours!
Not post related, i think (sometimes it passes the posts that the have previously crashed)

It happens on two accounts that i use for testing (logged in), but not on the account that doesn't have the layout flag, as i said.

Also in OSx and on the droplets.

2017-04-11 01:14 UTC, vlntdds commented
With this PR i couldn't start InstaPy without the "ignore_users" setting, currently i can.

Script:
`InstaPy(username='9', password='9')\
  .login()\
  .set_do_comment(True, percentage=10) \
  .set_comments(['Cool!', 'Awesome!', 'Nice!']) \
  .like_by_tags(['#programming', '#reactjs', '#webdevelopment', '#angularjs', '#nodejs', '#java', '#developer', '#coding', '#javascript', '#webdesign'], amount=100) \
  .end()`

Error:
```
  File "/Users/eduardocjr/Desktop/devel/InstaPy/instapy/instapy.py", line 236, in like_by_tags
    self.ignore_if_contains, self.ignore_users,
AttributeError: InstaPy instance has no attribute 'ignore_users'
```

2017-04-11 19:26 UTC, pekapa commented
@vlntdds could you please check again?

2017-04-15 10:01 UTC, timgrossmann requested changes

2017-04-15 10:01 UTC, timgrossmann commented on instapy/instapy.py
> +    if users is None:
Please use:

```python
self.ignore_users = users or []
```

here...

2017-04-15 10:01 UTC, timgrossmann commented on instapy/like_util.py
> +  owner_comments = browser.execute_script('''
@vlntdds This looks pretty error prune, does it work with different OS and devices?

2017-04-15 10:01 UTC, timgrossmann commented on instapy/like_util.py
> +  elif owner_comments is not None:
You could also do:

```python
elif owner_comments:
...
```

2017-04-15 15:04 UTC, pekapa commented
I've updated this to include the changes and solve conflicts but it keep showing "Changes requested", I'm not sure what I should do to solve it.

2017-04-15 19:03 UTC, timgrossmann approved these changes

2017-04-15 19:04 UTC, timgrossmann commented
@pekapa Sorry, this was on my side.
After I request it, I have to approve it.

Did you test your code?
After the problem with the last merge I'd like to make sure you tested it locally before merging it.

Can't test on my own right now

2017-04-15 19:37 UTC, pekapa commented
Yes, I've tested.
All changes were made locally.

The other one was made directly on GitHub as it was supposed to be an "easy" one...

2017-04-16 17:02 UTC, timgrossmann commented
@pekapa  Well, lets see how it works in use then 😉

2017-04-16 17:02 UTC, merged