Adding if condition to unfollow_util.py
InstaPy/InstaPy pull request #6182
Opened 2021-05-13 02:00 UTC by tg1482

# Pull Request Template

## Description

Found an error being generated due to random.sample. The error was being caused due to the number of followers for an instagram user being less than the minimum required to interact. Discovered that its a simple fix with an if statement in unfollow_util.py within get_users_through_dialog_with_graphql function. 

Fixes # (issue)

## How Has This Been Tested?

- [ ] Test

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have checked my code and corrected any misspellings
- [ ] I have performed a self-review of my own code
- [ ] My code follows the style guidelines of this project, `black -t py34`
- [ ] My changes generate no new warnings

2021-09-18 18:12 UTC, elulcao commented
Fix the CI warnings
and complete the check list

2021-09-28 14:24 UTC, breuerfelix commented
the CI pipeline is pretty weird right now since it would like to fix 17 files... only one has changed :) so no worries here :) i will move it to actions anyways

2021-12-19 05:21 UTC, Mensume requested changes
tg1482:master

2021-12-19 05:45 UTC, Mensume approved these changes
> 

>  @``

2023-11-16 09:37 UTC, tg1482 commented
Can we do anything to merge this? Happy to help!

2023-12-07 05:27 UTC, elulcao approved these changes

2023-12-07 05:27 UTC, merged