fix: consent to all cookies before logging in
InstaPy/InstaPy pull request #6262
Opened 2021-07-08 09:11 UTC by michelalbers

## Description

Instagram displays a cookie consent message before we can login. This fix clicks the "accept all cookies" button before moving on.

Fixes # (issue)

#6234 

## How Has This Been Tested?

Its now possible to login

## Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have checked my code and corrected any misspellings
- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project, `black -t py34`
- [x] My changes generate no new warnings

2021-07-10 10:19 UTC, fintzd reviewed
Hey! Thanks for that, there has been many comments about this error in the issues section, however, it seemed to me as if this should have been already fixed by a previous PR, could you check if you have the latest version of instapy installed and that it does not work? 

The last PR that has been merged and which seems to be handling this issue is [#6079](https://github.com/timgrossmann/InstaPy/pull/6079). Did you check that out?

2021-12-11 16:00 UTC, ntelo007 commented
I just made the change locally and I can verify that it works only with this merge.

2022-05-08 07:03 UTC, hadifarnoud commented
why isn't this merged yet?

2022-05-08 09:55 UTC, hadifarnoud requested changes

2022-05-08 09:55 UTC, hadifarnoud commented on instapy/login_util.py
> +        if element.text.strip().lower() == 'accept all':
it does not work with new changes

2022-06-03 08:24 UTC, closed without merging