Addition of issue #14 - Checking the follwer count
InstaPy/InstaPy pull request #91
Opened 2017-04-14 13:39 UTC by littleswany

Adding functionality that checks the numbers of followers a user has
and compares this to a user set value and if this exceeds the value no
further interaction happens.

Command:
.set_upper_follower_count(limit = 250) \

Addition of this to documentation and readme also

2017-04-14 13:53 UTC, AlainPilon commented on instapy/instapy.py
> +    return self
190 to 193 could be replaced with:
`self.like_by_followers_limit = limit or 1000000000

2017-04-14 13:54 UTC, pekapa commented
If I might make a suggestion...

Instead of using a huge number (10000000000), use 0 and add and `if like_by_followers_limit`
Also, the way your are parsing the `.set_upper_follower_count` the user can only set it to `None` if he explicitly do so (change de default `limit` value to `None`). Finally, if it is `None`, the code does break as you set it to `None` and not the huge number (int > None always evaluate to True).

2017-04-14 13:58 UTC, littleswany commented
Thanks @AlainPilon and @pekapa.

@pekapa so are you suggesting to have the default value as 0 and then checking for a 0 value or setting the default to None?

2017-04-14 13:59 UTC, littleswany commented on instapy/instapy.py
> +    return self
Thanks @AlainPilon will look into this

2017-04-14 14:03 UTC, pekapa commented
I'm suggesting to have the default as 0 and in than:

```python
if like_by_followers_limit and (num_followers > like_by_followers_limit):
    return True, user_name
```

2017-04-14 14:04 UTC, littleswany commented
Thanks, yeah Im with you, gimme a sec lemme just update and test

2017-04-14 14:16 UTC, littleswany commented
@pekapa Have updated

2017-04-14 14:42 UTC, AlainPilon commented
BTW a little bit off topic but, what was the thought process to have the functions return `True, user_name` when they should not be liked? I know the variable is `inappropriate` but shouldnt we reverse the boolean logic to make it more intuitive?

2017-04-15 09:51 UTC, timgrossmann requested changes

2017-04-15 09:51 UTC, timgrossmann commented on README.md
> +<img src="https://s3-eu-central-1.amazonaws.com/centaur-wp/designweek/prod/content/uploads/2016/05/11170038/Instagram_Logo-1002x1003.jpg" width="200" align="right">
Please pull the master branch again and rebase on it...
We don't want to alter the readme more than your insertions 😉

2017-04-15 09:51 UTC, timgrossmann commented on instapy/like_util.py
> +  print "Number of Followers: ", num_followers
We only want to print this if we have set the `like_by_followers` to true, don't we?

2017-04-15 09:52 UTC, timgrossmann commented
@littleswany This is really nice! Thank you for the collaboration!
Could you please also add lower_follower_count?
I think that shouldn't be too much work now, since you already added the upper one 😉

2017-04-15 10:22 UTC, littleswany commented on README.md
> +<img src="https://s3-eu-central-1.amazonaws.com/centaur-wp/designweek/prod/content/uploads/2016/05/11170038/Instagram_Logo-1002x1003.jpg" width="200" align="right">
Done, will update shortly.

2017-04-15 10:23 UTC, littleswany commented on instapy/like_util.py
> +  print "Number of Followers: ", num_followers
I have removed as it is not really necessary just had it in there for my testing.

2017-04-15 10:54 UTC, littleswany commented
@timgrossmann Glad you like it and your welcome, glad to be able to get involved!
Have committed the requested updates.

2017-04-15 13:50 UTC, timgrossmann approved these changes

2017-04-15 13:50 UTC, timgrossmann commented on README.md
> +<img src="https://s3-eu-central-1.amazonaws.com/centaur-wp/designweek/prod/content/uploads/2016/05/11170038/Instagram_Logo-1002x1003.jpg" width="200" align="right">
`<img src="http://i.imgur.com/9ZjtveL.png" width="150" align="right">`
<img src="http://i.imgur.com/9ZjtveL.png" width="150" align="right">

sorry, I probably communicated it wrong:
This is the new image link

Also, could you please add  your additions to the index.md in /docs/?
Would be awesome!

2017-04-15 13:54 UTC, littleswany commented
@timgrossmann No worries, have updated!

2017-04-15 14:12 UTC, merged

2017-04-16 20:35 UTC, timgrossmann commented
solved #14