New Following Feature - follow by a list
InstaPy/InstaPy pull request #92
Opened 2017-04-14 16:42 UTC by Albertmoiseev

A new following feature was implemented. 

It allows following not only by tagged photos but by any arbitrary list.

It was also integrated with the logger.

2017-04-14 22:54 UTC, vlntdds commented
Is this really necessary?

2017-04-15 07:37 UTC, Albertmoiseev commented
Dear Contributors,

in my humble opinion, it really is.

For example, all the professional social media programs do offer this feature. In particular, this feature presents in FollowLiker Instagram features list (http://www.followliker.com/checklist.html) and called: "_Follow custom list of users (your own list of users)_". 

Massplanner also provides this feature.

It is useful when you need a more precise targeting for following.

If contributors will not be against, I am also planning to do a PR with the scraping feature - which will scrape the followers of any provided insta account and appends them to a list for the future following by the proposed feature we are discussing.

2017-04-15 09:43 UTC, timgrossmann requested changes

2017-04-15 09:43 UTC, timgrossmann commented on instapy/instapy.py
> +        print('---> ' + acc_to_follow + ' has already been followed more > times than specified')
Please use `self.follow_times` instead of "> times than specified"

2017-04-15 09:43 UTC, timgrossmann commented on README.md
> +
Please shortly describe, what the use case for this feature could be

2017-04-15 09:44 UTC, timgrossmann commented on README.md
> +
Also, please add the documentation into the index.md in the /docs folder

2017-04-15 09:45 UTC, timgrossmann commented
@Albertmoiseev I don't really get the use-case for this, but I can imagine some people wanting this, so make the changes and it'll be merged 😉 

Thank you for collaborating!

2017-04-15 09:57 UTC, timgrossmann requested changes

2017-04-15 09:57 UTC, timgrossmann commented on instapy/instapy.py
> +    self.follow_times = times
Please use:
```python
self.follow_times = times or 0
```

here...

2017-04-15 10:40 UTC, Albertmoiseev commented
Dear @timgrossmann,

I have done the Changes request)

Looking forward for the future collaboration) 

I would like to develop this feature and propose and collaborate on some new (for example, multi-acc support, user-scraper, proxy and e.t.c).

2017-04-15 13:42 UTC, timgrossmann commented on instapy/instapy.py
> +        print('---> ' + acc_to_follow + ' has already been followed more than self.follow_times')
Sorry for another comment, but could you please change this so that the number of self.follow_times is displayed?

```python
print('---> ' + acc_to_follow + ' has already been followed more than ' +  str(self.follow_times) + ' times')
```

2017-04-15 13:43 UTC, timgrossmann commented
@Albertmoiseev Thank you for your work!
Would love to see more features from you!

2017-04-15 15:31 UTC, Albertmoiseev commented on instapy/instapy.py
> +    self.follow_times = times
@timgrossmann, oh, sorry... I have just fixed it

2017-04-15 19:04 UTC, timgrossmann approved these changes

2017-04-15 19:05 UTC, timgrossmann commented
@Albertmoiseev just one more resolve and you're ready to go!

2017-04-17 07:35 UTC, Albertmoiseev commented
Have resolved it. Please check )

2017-04-17 11:16 UTC, timgrossmann requested changes

2017-04-17 11:16 UTC, timgrossmann commented on instapy/instapy.py
> +        print('---> ' + acc_to_follow + ' has already been followed more than ' + str(self.follow_times) + ' times')
We just changed to the `.format() `version, so this sadly has to be refactored...

2017-04-17 11:16 UTC, timgrossmann commented on instapy/unfollow_util.py
> +    print('--> ' + acc_to_follow + ' instagram account is opened...')
Same here, please use `.format()`

2017-04-17 11:16 UTC, timgrossmann commented on .idea/InstaPy.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Please remove

2017-04-17 11:16 UTC, timgrossmann commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Please remove

2017-04-17 11:16 UTC, timgrossmann commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Please remove

2017-04-17 11:16 UTC, timgrossmann commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Please remove

2017-04-17 11:16 UTC, timgrossmann commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Please remove

2017-04-17 11:16 UTC, timgrossmann commented
@Albertmoiseev I'm really sorry this is changing so fast...

But please remove the unnecessary .idea files and change the printing to use `.fomat()`

Thank you for your time and collaboration.

2017-04-17 12:57 UTC, Albertmoiseev commented
Have implemented the change requests. Waiting for new ones or merging. ))

2017-04-17 17:11 UTC, AlainPilon commented on instapy/unfollow_util.py
> +def follow_user_from_list(browser, acc_to_follow, follow_restrict):
Actually, this is not a function to follow users from a list but to follow a single user (`acc_to_follow`).

2017-04-17 21:53 UTC, timgrossmann commented on instapy/unfollow_util.py
> +def follow_user_from_list(browser, acc_to_follow, follow_restrict):
Yeah, the semantics seem to be a bit of with this function declaration...

`follow_given_user` would probably be a more descriptive name

2017-04-17 21:53 UTC, timgrossmann approved these changes

2017-04-18 07:37 UTC, Albertmoiseev commented
Hi all )) I have refactored the function name for the semantics fit.

2017-04-18 15:21 UTC, merged